/* Expense module: PWA view over the existing GAS expense business rules. */
const state={data:null,tab:0,direction:"รายจ่าย",month:new Date().getMonth(),year:new Date().getFullYear(),summary:null,editExpense:null,editInvestment:null,purchase:[],purchaseMeta:{},modal:null,loading:false};
let runtime={api:null,session:"",back:null,toast:()=>{},root:null,user:""};
const esc=v=>String(v==null?"":v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const money=v=>`฿${(Number(v)||0).toLocaleString("th-TH")}`;
const date=v=>{try{return new Date(v).toLocaleDateString("th-TH",{day:"numeric",month:"short",year:"numeric"});}catch(_){return String(v||"");}};
const ymd=v=>{const d=v?new Date(v):new Date();return Number.isNaN(d.getTime())?"":d.toISOString().slice(0,10)};
const select=(a,current,placeholder="-- เลือก --")=>`<option value="">${placeholder}</option>${(a||[]).map(v=>`<option value="${esc(v)}" ${String(v)===String(current)?"selected":""}>${esc(v)}</option>`).join("")}`;
const selected=(v,current)=>String(v)===String(current)?"selected":"";
const isPurchase=(d,cat,kind)=>kind==="expense"&&cat===d.shopPurchaseCategory;
const isAdvance=(d,cat,kind)=>kind==="expense"&&cat===d.advanceWageCategory;
const materialMode=(d,cat,kind)=>{if(kind!=="expense"||isPurchase(d,cat,kind)||isAdvance(d,cat,kind))return "";if(String(cat).includes("ของขาว"))return "ของขาว";return (d.materialCats||[]).includes(cat)?"วัตถุดิบ":"";};

export async function renderExpense(root,api,session,onBack,context={}){
  runtime={api,session,back:onBack,toast:context.toast||(()=>{}),root,user:(context.displayUser||{}).name||""};
  const appHeader=document.querySelector("#appHeader");if(appHeader){appHeader.setAttribute("hidden","");appHeader.style.display="none";}
  if(!state.data){state.loading=true;draw();try{const r=await api.expenseBootstrap(session);if(!r.ok)throw new Error(r.message||"โหลดข้อมูลไม่สำเร็จ");state.data=r.result||{};}catch(error){root.innerHTML=`<section class="expense-failure"><h1>เปิดหน้าค่าใช้จ่ายไม่สำเร็จ</h1><p>${esc(error.message||error)}</p><button data-exp="back">← กลับ</button></section>`;root.onclick=evt=>onClick(evt);return;}finally{state.loading=false;}draw();return;}
  // Render cached master data immediately, then quietly revalidate it.
  draw();
  api.expenseBootstrap(session).then(r=>{if(r.ok&&runtime.root===root){state.data=r.result||state.data;draw();}}).catch(()=>{});
}

function draw(){const root=runtime.root,d=state.data||{},sum=state.summary||d.summary||{};root.innerHTML=`
  <section class="expense-page">
    <header class="expense-top"><button class="expense-back" data-exp="back">← กลับ</button><h1>💸 ค่าใช้จ่าย</h1></header>
    <nav class="expense-tabs">${[[0,"📝 รับ-จ่าย"],[1,"🏠 ค่าใช้ประจำเดือน"],[2,"💰 เงินลงทุน"],[3,"📊 สรุปรายเดือน"]].map(([i,t])=>`<button class="expense-tab ${state.tab===i?"active":""}" data-exp="tab" data-tab="${i}">${t}</button>`).join("")}</nav>
    ${state.loading?`<div class="expense-loading">กำลังโหลดข้อมูล…</div>`:state.tab===0?transactions(d,sum):state.tab===1?fixed(d):state.tab===2?investment(d):summary(d,sum)}
  </section>${modal(d)}`;root.onclick=onClick;root.onsubmit=onSubmit;root.onchange=onChange;root.oninput=onInput;}

function transactions(d,s){const kind=state.direction,cat=(state.editExpense&&state.editExpense.cat)||"",mode=materialMode(d,cat,"expense"),advance=isAdvance(d,cat,"expense"),purchase=isPurchase(d,cat,"expense"),x=state.editExpense||{};return `
  <div class="expense-stats"><div class="expense-stat"><b>${money(s.total)}</b><span>💸 เดือนนี้</span></div><div class="expense-stat"><b>${money(s.fixedTotal)}</b><span>🏠 ค่าประจำ</span></div><div class="expense-stat"><b>${Number(s.count)||0}</b><span>📋 รายการ</span></div></div>
  <form class="expense-form" data-form="expense"><h2>${x.row?"✏️ แก้ไข":"➕ บันทึก"}${kind}</h2>
    <div class="expense-direction"><button type="button" class="expense ${kind==="รายจ่าย"?"active":""}" data-exp="direction" data-direction="รายจ่าย">รายจ่าย</button><button type="button" class="income ${kind==="รายรับ"?"active":""}" data-exp="direction" data-direction="รายรับ">รายรับ</button></div>
    <label class="expense-field"><span>หมวด *</span><select name="cat" data-exp-change="category">${select(kind==="รายรับ"?d.incomeCategories:d.categories,cat,"-- เลือกหมวด --")}</select></label>
    ${advance?advanceFields(d,x):purchase?purchaseFields(d):mode?materialFields(d,x,mode):regularFields(x)}
    <label class="expense-field"><span>วันที่</span><input type="date" name="date" value="${ymd(x.date)}"></label><label class="expense-field"><span>หมายเหตุ</span><input name="note" value="${esc(x.note||"")}"></label>${imageField(x.img)}${purchase?"":`<button class="expense-save">${x.row?"✅ บันทึกการแก้ไข":"✅ บันทึก"}</button>`}${x.row?`<button type="button" class="expense-cancel" data-exp="cancel-expense">ยกเลิกการแก้ไข</button>`:""}
  </form><div class="expense-group-title">📋 รายรับ-รายจ่ายล่าสุด</div><div class="expense-list">${expenseRows(d.expenses||[])}</div>`;}
function regularFields(x){return `<label class="expense-field"><span>รายละเอียด</span><input name="detail" value="${esc(x.detail||"")}"></label><label class="expense-field"><span>จำนวนเงิน (บาท) *</span><input class="expense-amount" type="number" min="0" step="0.01" name="amount" value="${esc(x.amount||"")}"></label>`;}
function advanceFields(d,x){return `<div class="expense-note">เบิกค่าจ้างล่วงหน้า ระบบจะผูกยอดกับช่างโดยตรง</div><label class="expense-field"><span>ชื่อช่าง *</span><select name="workerName">${select((d.workshopEmployees||[]).map(w=>w.name||w),x.workerName,"-- เลือกช่าง --")}</select></label><label class="expense-field"><span>จำนวนเงิน (บาท) *</span><input class="expense-amount" type="number" min="0" step="0.01" name="amount" value="${esc(x.amount||"")}"></label>`;}
function materialFields(d,x,mode){const items=mode==="ของขาว"?d.whitewares:d.rawMaterials,key=mode==="ของขาว"?"whitewareSku":"rawSku",current=x[key]||"",options=items.map(i=>`${i.sku||i.code}|${i.name}`),found=items.find(i=>String(i.sku||i.code)===String(current));return `<div class="expense-note">${mode} — เลือกรายการเดิมหรือเพิ่มรายการใหม่ ระบบจะอ้างอิงยอดเดิมโดยอัตโนมัติ</div><label class="expense-field"><span>${mode} *</span><select name="${key}">${select(options,current?`${current}|${(found&&found.name)||""}`:"","-- เลือกรายการเดิม --")}</select></label><label class="expense-check"><input type="checkbox" name="materialNew"> เพิ่มรายการใหม่</label><label class="expense-field"><span>ชื่อรายการใหม่</span><input name="materialName" value="${esc(x.materialName||"")}"></label><div class="expense-grid"><label class="expense-field"><span>ราคา/หน่วย *</span><input type="number" step="0.01" min="0" name="pricePerUnit" value="${esc(x.pricePerUnit||"")}"></label><label class="expense-field"><span>จำนวน *</span><input type="number" step="0.01" min="0" name="qty" value="${esc(x.qty||"")}"></label></div><label class="expense-field"><span>หน่วย</span><select name="unit">${select(d.units||[],x.unit,"-- เลือกหน่วย --")}</select></label><label class="expense-field"><span>ยอดรวม</span><input class="expense-amount" type="number" name="amount" readonly value="${Number(x.amount)||""}"></label><input type="hidden" name="stockLayer" value="${mode}">`;}
function purchaseFields(d){const rows=state.purchase.map((p,i)=>`<div class="purchase-line"><div><b>${esc(p.name)}</b><small>${p.qty} × ${money(p.price)}${p.isNew?" · รายการใหม่":""}</small></div><b>${money(p.qty*p.price)}</b><button type="button" data-exp="purchase-remove" data-index="${i}">✕</button></div>`).join("")||'<div class="expense-empty compact">ยังไม่มีสินค้าในใบซื้อ</div>',products=d.purchaseProducts||[],m=state.purchaseMeta||{};return `<div class="purchase-box"><h3>📦 ซื้อสินค้าเข้าร้าน</h3><label class="expense-field"><span>ผู้ขาย/ร้านค้า *</span><input name="vendor" value="${esc(m.vendor||"")}"></label><label class="expense-field"><span>เลขที่บิล</span><input name="billNo" value="${esc(m.billNo||"")}"></label><div class="purchase-add"><select name="purchaseProduct">${select(products.map(p=>`${p.code||p.sku}|${p.name}`),"","-- เลือกสินค้าที่มีอยู่ --")}</select><button type="button" data-exp="new-product">➕ สินค้าใหม่</button></div><div class="expense-grid"><label class="expense-field"><span>จำนวน</span><input type="number" name="purchaseQty" min="1" step="1" value="1"></label><label class="expense-field"><span>ราคาต่อชิ้น</span><input type="number" name="purchasePrice" min="0" step="0.01"></label></div><button type="button" class="expense-add" data-exp="purchase-add">＋ เพิ่มเข้ารายการซื้อ</button><div class="purchase-lines">${rows}</div><div class="purchase-total">รวม <b>${money(state.purchase.reduce((n,p)=>n+Number(p.qty)*Number(p.price),0))}</b></div><button class="expense-save" data-exp="purchase-save">✅ บันทึกรับสินค้าเข้าร้าน</button></div>`;}
function imageField(img){return `<label class="expense-field"><span>แนบรูปสลิป/หลักฐาน (ไม่เกิน 6 MB)</span><input type="file" accept="image/jpeg,image/png,image/webp" name="image">${img&&img!=="__KEEP__"?`<a class="expense-image-link" href="${esc(img)}" target="_blank" rel="noopener">ดูรูปที่แนบไว้</a>`:""}</label>`;}
function expenseRows(rows){return rows.map(x=>{const purchase=x.source==="purchase";return `<article class="expense-card ${x.type==="รายรับ"?"income":""}"><div class="expense-info"><div class="expense-cat">${esc(x.cat||"")}${purchase?" · ซื้อสินค้าเข้าร้าน":""}</div><div class="expense-detail">${esc(x.detail||x.cat||"")}</div><div class="expense-date">${date(x.date)}${x.note?` · ${esc(x.note)}`:""}</div></div><b class="expense-money">${x.type==="รายรับ"?"+":"-"}${money(x.amount)}</b>${x.img?`<a class="expense-thumb" href="${esc(x.img)}" target="_blank" rel="noopener">🖼️</a>`:""}${purchase?`<span class="expense-lock">🔒</span>`:`<div class="expense-actions"><button data-exp="expense-edit" data-row="${x.row}">✏️</button><button data-exp="expense-delete" data-row="${x.row}">🗑️</button></div>`}</article>`;}).join("")||'<div class="expense-empty">ยังไม่มีรายการ</div>';}
function fixed(d){const list=d.fixed||[],total=list.filter(x=>x.status==="ยังจ่ายอยู่").reduce((n,x)=>n+Number(x.amount||0),0);return `<div class="expense-toolbar"><div class="expense-stats one"><div class="expense-stat"><b>${money(total)}</b><span>รวมต่อเดือน</span></div></div><button class="expense-new" data-exp="fixed-new">＋ เพิ่มค่าใช้จ่ายประจำ</button></div><div class="expense-group-title">🏠 ค่าใช้จ่ายประจำเดือน</div>${list.map(x=>`<article class="expense-card fixed-card"><div class="expense-info"><div class="expense-detail">${esc(x.name)}</div><div class="expense-date">${x.payDate?`จ่ายทุกวันที่ ${esc(x.payDate)} · `:""}${x.payTo?`จ่ายให้ ${esc(x.payTo)} · `:""}<span class="fixed-status ${x.status==="ยังจ่ายอยู่"?"on":"off"}">${esc(x.status||"")}</span></div></div><b class="expense-money">${money(x.amount)}/เดือน</b><div class="expense-actions"><button data-exp="fixed-edit" data-row="${x.row}">✏️</button><button data-exp="fixed-status" data-row="${x.row}" data-status="${x.status==="ยังจ่ายอยู่"?"หยุดจ่าย":"ยังจ่ายอยู่"}">${x.status==="ยังจ่ายอยู่"?"⏸️":"▶️"}</button></div></article>`).join("")||'<div class="expense-empty">ยังไม่มีรายการ</div>'}`;}
function investment(d){const x=state.editInvestment||{};return `<form class="expense-form" data-form="investment"><h2>${x.row?"✏️ แก้ไขเงินลงทุน":"💰 บันทึกเงินลงทุน"}</h2><label class="expense-field"><span>หมวด *</span><select name="cat">${select(d.investCats||[],x.cat,"-- เลือกหมวด --")}</select></label><label class="expense-field"><span>รายละเอียด</span><input name="detail" value="${esc(x.detail||"")}"></label><label class="expense-field"><span>จำนวนเงิน *</span><input class="expense-amount" type="number" name="amount" min="0" step="0.01" value="${esc(x.amount||"")}"></label><label class="expense-field"><span>วิธีจ่าย</span><select name="payMethod"><option value="เงินสด" ${selected("เงินสด",x.payMethod||"เงินสด")}>เงินสด</option><option value="โอนธนาคาร" ${selected("โอนธนาคาร",x.payMethod)}>โอนธนาคาร</option></select></label><label class="expense-field"><span>วันที่</span><input type="date" name="date" value="${ymd(x.date)}"></label><label class="expense-field"><span>หมายเหตุ</span><input name="note" value="${esc(x.note||"")}"></label>${imageField(x.img)}<button class="expense-save">${x.row?"✅ บันทึกการแก้ไข":"✅ บันทึก"}</button>${x.row?`<button type="button" class="expense-cancel" data-exp="cancel-investment">ยกเลิกการแก้ไข</button>`:""}</form><div class="expense-group-title">📋 ประวัติเงินลงทุน</div>${(d.investments||[]).map(x=>`<article class="expense-card"><div class="expense-info"><div class="expense-cat">${esc(x.cat)}</div><div class="expense-detail">${esc(x.detail||x.cat)}</div><div class="expense-date">${date(x.date)}${x.payMethod?` · ${esc(x.payMethod)}`:""}</div></div><b class="expense-money">-${money(x.amount)}</b>${x.img?`<a class="expense-thumb" href="${esc(x.img)}" target="_blank" rel="noopener">🖼️</a>`:""}<div class="expense-actions"><button data-exp="investment-edit" data-row="${x.row}">✏️</button><button data-exp="investment-delete" data-row="${x.row}">🗑️</button></div></article>`).join("")||'<div class="expense-empty">ยังไม่มีประวัติ</div>'}`;}
function summary(d,s){const by=s.byCat||{},max=Math.max(1,...Object.values(by).map(Number)),months=["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"];return `<div class="summary-nav"><button data-exp="month-prev">‹</button><b>${months[state.month]} ${state.year+543}</b><button data-exp="month-next">›</button></div><div class="expense-stats"><div class="expense-stat"><b>${money(s.total)}</b><span>💸 รายจ่ายรวม</span></div><div class="expense-stat"><b>${money(s.fixedTotal)}</b><span>🏠 ค่าประจำ</span></div><div class="expense-stat"><b>${Number(s.count)||0}</b><span>📋 รายการ</span></div></div><div class="expense-group-title">📊 แยกตามหมวด</div><div class="expense-bars">${Object.keys(by).map(k=>`<div class="expense-bar"><span>${esc(k)}</span><i style="width:${Math.round(Number(by[k])/max*100)}%"></i><b>${money(by[k])}</b></div>`).join("")||'<div class="expense-empty">ไม่มีข้อมูลในเดือนนี้</div>'}</div>`;}
function modal(d){const m=state.modal;if(!m)return "";if(m.kind==="confirm")return `<div class="expense-modal-backdrop"><section class="expense-modal small"><button class="modal-close" data-exp="modal-close">×</button><h2>${esc(m.title)}</h2><p>${esc(m.text||"")}</p><div class="modal-actions"><button data-exp="modal-close">ยกเลิก</button><button class="danger" data-exp="confirm-yes">ยืนยัน</button></div></section></div>`;if(m.kind==="fixed"){const x=m.value||{};return `<div class="expense-modal-backdrop"><form class="expense-modal" data-form="fixed"><button type="button" class="modal-close" data-exp="modal-close">×</button><h2>${x.row?"✏️ แก้ไขค่าใช้จ่ายประจำ":"➕ เพิ่มค่าใช้จ่ายประจำ"}</h2><label class="expense-field"><span>ชื่อรายการ *</span><input name="name" value="${esc(x.name||"")}"></label><label class="expense-field"><span>จำนวนต่อเดือน *</span><input name="amount" type="number" min="0" step="0.01" value="${esc(x.amount||"")}"></label><label class="expense-field"><span>จ่ายทุกวันที่</span><input name="payDate" type="number" min="1" max="31" value="${esc(x.payDate||"")}"></label><label class="expense-field"><span>จ่ายให้</span><input name="payTo" value="${esc(x.payTo||"")}"></label><label class="expense-field"><span>สถานะ</span><select name="status">${select(d.fixedStatus||["ยังจ่ายอยู่","หยุดจ่าย","จ่ายครบแล้ว"],x.status||"ยังจ่ายอยู่","")}</select></label><button class="expense-save">✅ บันทึก</button></form></div>`;}if(m.kind==="new-product")return `<div class="expense-modal-backdrop"><form class="expense-modal" data-form="new-product"><button type="button" class="modal-close" data-exp="modal-close">×</button><h2>➕ สินค้าใหม่เข้าร้าน</h2><label class="expense-field"><span>ชื่อสินค้า *</span><input name="name"></label><label class="expense-field"><span>หมวด *</span><select name="category">${select((d.purchaseOptions&&d.purchaseOptions.categories)||[],"","-- เลือกหมวด --")}</select></label><label class="expense-field"><span>ลาย</span><select name="pattern">${select((d.purchaseOptions&&d.purchaseOptions.patterns)||[],"","")}</select></label><div class="expense-grid"><label class="expense-field"><span>จำนวนรับเข้า *</span><input type="number" name="qty" min="1" step="1" value="1"></label><label class="expense-field"><span>ต้นทุน/ชิ้น *</span><input type="number" name="price" min="0" step="0.01"></label></div><label class="expense-field"><span>ราคา ขายปลีก</span><input type="number" name="priceRetail" min="0" step="0.01"></label><button class="expense-save">เพิ่มเข้ารายการซื้อ</button></form></div>`;return "";}
function formValues(form){return Object.fromEntries(new FormData(form));}
async function onSubmit(event){const form=event.target.closest("form[data-form]");if(!form)return;event.preventDefault();const d=state.data||{},v=formValues(form);if(form.dataset.form==="expense")return saveExpense(form,v,d);if(form.dataset.form==="investment")return saveInvestment(form,v);if(form.dataset.form==="fixed")return saveFixed(v);if(form.dataset.form==="new-product")return newProduct(v);}
function onChange(event){if(event.target.matches('[data-exp-change="category"]')){const old=Object.fromEntries(new FormData(event.target.form));state.editExpense={...(state.editExpense||{}),...old,cat:event.target.value};draw();}}
function onInput(event){if(["pricePerUnit","qty"].includes(event.target.name)){const f=event.target.form,p=Number(f.pricePerUnit&&f.pricePerUnit.value)||0,q=Number(f.qty&&f.qty.value)||0;if(f.amount)f.amount.value=(p*q)||"";}}
async function onClick(event){const b=event.target.closest("[data-exp]");if(!b)return;event.preventDefault();event.stopImmediatePropagation();const a=b.dataset.exp,d=state.data||{};if(a==="back")return runtime.back();if(a==="tab"){state.tab=Number(b.dataset.tab);return draw();}if(a==="direction"){state.direction=b.dataset.direction;state.editExpense=null;return draw();}if(a==="cancel-expense"){state.editExpense=null;return draw();}if(a==="cancel-investment"){state.editInvestment=null;return draw();}if(a==="expense-edit"){const x=(d.expenses||[]).find(v=>Number(v.row)===Number(b.dataset.row));if(x){state.direction=x.type||"รายจ่าย";state.editExpense={...x};draw();window.scrollTo({top:0,behavior:"smooth"});}return;}if(a==="expense-delete")return ask("ลบรายการนี้?","รายการที่ลบแล้วไม่สามารถกู้คืนได้",()=>run(()=>runtime.api.expenseDelete(runtime.session,Number(b.dataset.row))));if(a==="investment-edit"){state.editInvestment=(d.investments||[]).find(v=>Number(v.row)===Number(b.dataset.row))||null;return draw();}if(a==="investment-delete")return ask("ลบเงินลงทุน?","รายการที่ลบแล้วไม่สามารถกู้คืนได้",()=>run(()=>runtime.api.investmentDelete(runtime.session,Number(b.dataset.row))));if(a==="fixed-new"){state.modal={kind:"fixed",value:{}};return draw();}if(a==="fixed-edit"){state.modal={kind:"fixed",value:(d.fixed||[]).find(v=>Number(v.row)===Number(b.dataset.row))||{}};return draw();}if(a==="fixed-status")return run(()=>runtime.api.fixedStatus(runtime.session,Number(b.dataset.row),b.dataset.status));if(a==="modal-close"){state.modal=null;return draw();}if(a==="confirm-yes"){const fn=state.modal&&state.modal.confirm;state.modal=null;draw();if(fn)return fn();return;}if(a==="new-product"){state.modal={kind:"new-product"};return draw();}if(a==="purchase-remove"){state.purchase.splice(Number(b.dataset.index),1);return draw();}if(a==="purchase-add")return addPurchaseLine(b.closest("form"),d);if(a==="purchase-save")return savePurchase(b.closest("form"));if(a==="month-prev"||a==="month-next"){state.month+=a==="month-prev"?-1:1;if(state.month<0){state.month=11;state.year--;}if(state.month>11){state.month=0;state.year++;}return loadSummary();}}
function ask(title,text,confirm){state.modal={kind:"confirm",title,text,confirm};draw();}
async function prepareImage(form,keep){const input=form.querySelector('input[type="file"]'),file=input&&input.files&&input.files[0];if(!file)return keep?"__KEEP__":"";if(file.size>6*1024*1024)throw new Error("รูปมีขนาดเกิน 6 MB");const data=await new Promise((ok,bad)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=bad;r.readAsDataURL(file);});const r=await runtime.api.expenseUploadImage(runtime.session,data,file.name);if(!r.ok)throw new Error(r.message||"อัปโหลดรูปไม่สำเร็จ");return r.result.url||r.result;}
async function saveExpense(form,v,d){try{const edit=state.editExpense||{};if(!v.cat)throw new Error("กรุณาเลือกหมวด");const advance=isAdvance(d,v.cat,"expense"),purchase=isPurchase(d,v.cat,"expense"),mode=materialMode(d,v.cat,"expense");if(purchase)return savePurchase(form);if(advance&&!v.workerName)throw new Error("กรุณาเลือกชื่อช่าง");if(mode){const code=String(mode==="ของขาว"?v.whitewareSku:v.rawSku).split("|")[0];if(!code&&!v.materialName)throw new Error("กรุณาเลือกรายการหรือใส่ชื่อรายการใหม่");if(!(Number(v.pricePerUnit)>0)||!(Number(v.qty)>0))throw new Error("กรุณาใส่ราคาและจำนวน");v[mode==="ของขาว"?"whitewareSku":"rawSku"]=code;v.stockLayer=mode;v.amount=Number(v.pricePerUnit)*Number(v.qty);}else if(!(Number(v.amount)>0))throw new Error("กรุณาใส่จำนวนเงิน");v.type=state.direction;v.by=runtime.user;v.img=await prepareImage(form,Boolean(edit.row));if(edit.row)await run(()=>runtime.api.expenseUpdate(runtime.session,edit.row,v));else await run(()=>runtime.api.expenseAdd(runtime.session,v));}catch(error){runtime.toast(`❌ ${error.message||error}`);}}
async function saveInvestment(form,v){try{if(!v.cat||!(Number(v.amount)>0))throw new Error("กรุณาเลือกหมวดและใส่จำนวนเงิน");const edit=state.editInvestment||{};v.by=runtime.user;v.img=await prepareImage(form,Boolean(edit.row));if(edit.row)await run(()=>runtime.api.investmentUpdate(runtime.session,edit.row,v));else await run(()=>runtime.api.investmentAdd(runtime.session,v));}catch(error){runtime.toast(`❌ ${error.message||error}`);}}
async function saveFixed(v){try{if(!v.name||!(Number(v.amount)>0))throw new Error("กรุณาใส่ชื่อรายการและจำนวนเงิน");const edit=(state.modal&&state.modal.value)||{};state.modal=null;if(edit.row)await run(()=>runtime.api.fixedUpdate(runtime.session,edit.row,v));else await run(()=>runtime.api.fixedAdd(runtime.session,v));}catch(error){runtime.toast(`❌ ${error.message||error}`);}}
function newProduct(v){if(!v.name||!v.category)return runtime.toast("กรุณาใส่ชื่อและหมวดสินค้า");if(!(Number(v.qty)>0)||Number(v.price)<0)return runtime.toast("กรุณาใส่จำนวนและต้นทุนให้ถูกต้อง");state.purchase.push({name:v.name,category:v.category,pattern:v.pattern||"",priceRetail:Number(v.priceRetail)||0,qty:Number(v.qty),price:Number(v.price),isNew:true});state.modal=null;draw();}
function addPurchaseLine(form,d){const v=formValues(form),id=String(v.purchaseProduct||"").split("|")[0],product=(d.purchaseProducts||[]).find(x=>String(x.code||x.sku)===id);state.purchaseMeta={...state.purchaseMeta,vendor:v.vendor||"",billNo:v.billNo||""};if(!product)return runtime.toast("กรุณาเลือกสินค้า");if(!(Number(v.purchaseQty)>0)||Number(v.purchasePrice)<0)return runtime.toast("กรุณาใส่จำนวนและราคาให้ถูกต้อง");state.purchase.push({sku:id,name:product.name,size:product.size||"-",qty:Number(v.purchaseQty),price:Number(v.purchasePrice),isNew:false});draw();}
async function savePurchase(form){try{const v=formValues(form);if(!v.vendor)throw new Error("กรุณาใส่ชื่อผู้ขาย/ร้านค้า");if(!state.purchase.length)throw new Error("ยังไม่มีสินค้าในรายการซื้อ");const items=state.purchase.map(x=>x.isNew?{qty:x.qty,priceEach:x.price,newProduct:{name:x.name,category:x.category,pattern:x.pattern,priceRetail:x.priceRetail,cost:x.price}}:{productSku:x.sku,product:x.name||"",size:x.size||"-",qty:x.qty,priceEach:x.price});await run(()=>runtime.api.expensePurchase(runtime.session,{date:v.date||ymd(),vendor:v.vendor,billNo:v.billNo,note:v.note,img:"",items}));state.purchase=[];state.purchaseMeta={};}catch(error){runtime.toast(`❌ ${error.message||error}`);}}
async function loadSummary(){try{const r=await runtime.api.expenseMonthSummary(runtime.session,state.month,state.year);if(!r.ok)throw new Error(r.message||"โหลดสรุปไม่สำเร็จ");state.summary=r.result||{};draw();}catch(error){runtime.toast(`❌ ${error.message||error}`);}}
async function run(call){try{const r=await call();if(!r.ok)throw new Error(r.message||"บันทึกไม่สำเร็จ");runtime.toast(r.message||"บันทึกสำเร็จ");state.data=null;state.editExpense=null;state.editInvestment=null;state.modal=null;state.summary=null;await renderExpense(runtime.root,runtime.api,runtime.session,runtime.back,{toast:runtime.toast,displayUser:{name:runtime.user}});}catch(error){runtime.toast(`❌ ${error.message||error}`);}}
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&state.modal){state.modal=null;draw();}});
