/* Dashboard PWA — rendering only; every figure is calculated by 14_Report.gs. */
const S={data:null,tab:0,date:new Date(),month:new Date().getMonth()+1,year:new Date().getFullYear(),yearTab:new Date().getFullYear(),costMonth:new Date().getMonth()+1,costYear:new Date().getFullYear(),cashYear:new Date().getFullYear(),topMode:"month",topMonth:new Date().getMonth()+1,topYear:new Date().getFullYear(),cmpA:new Date().getFullYear(),cmpB:new Date().getFullYear()-1,printMonth:new Date().getMonth()+1,printYear:new Date().getFullYear(),cache:{},pending:{},open:{},modal:null,loading:true};
let R={root:null,api:null,token:"",back:null,toast:()=>{},shop:{}},escapeBound=false;
const E=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c]));
const N=v=>(Number(v)||0).toLocaleString("th-TH"),B=v=>`฿${N(v)}`;
const MS=["","มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"];
const tabs=[["📊 รายวัน","daily"],["📅 รายเดือน","month"],["📆 รายปี","year"],["🏆 ขายดี","top"],["🔄 เปรียบเทียบ","compare"],["🖨️ พิมพ์สรุป","print"],["💸 ต้นทุน","cost"],["💵 กระแสเงินสด","cash"]];
const active=()=>R.root?.isConnected&&R.root.dataset.route==="report";
const k=(type,...id)=>`${type}:${id.join(":")}`;
function stat(label,value,kind="blue",sub=""){return `<div class="rpt-stat ${kind}"><b>${value}</b><span>${label}${sub?`<small>${sub}</small>`:""}</span></div>`;}
function nav(label,prev,next){return `<div class="rpt-nav"><button data-rpt="${prev}">◀</button><b>${label}</b><button data-rpt="${next}">▶</button></div>`;}
function bars(rows,color="#43a047",value=x=>x.value||x.income||0,label=x=>x.name||x.day||x.month){const max=Math.max(1,...rows.map(value));return `<div class="rpt-bars">${rows.filter(x=>value(x)||x.expense).map(x=>`<div><span>${E(label(x))}</span><i><em style="width:${Math.round(value(x)/max*100)}%;background:${color}"></em></i><b>${B(value(x))}</b></div>`).join("")||'<div class="rpt-empty">ไม่มีข้อมูล</div>'}</div>`;}
function card(title,body){return `<section class="rpt-card"><h2>${title}</h2>${body}</section>`;}
function details(id,title,body){return `<section class="rpt-card rpt-detail"><button data-rpt="detail" data-id="${id}">${title} ${S.open[id]?"▲":"▼"}</button>${S.open[id]?`<div>${body}</div>`:""}</section>`;}
function daily(d){if(!d)return loading();const sales=d.sales||{},ex=d.expenses||{},inc=d.otherIncome||{};return `${nav(`📅 ${E(d.dateTH||"")}`,"day-prev","day-next")}<div class="rpt-stats">${stat("💰 รายรับรวม",B(d.totalIncome),"green",`ขาย ${B(sales.total)} + อื่นๆ ${B(inc.total)}`)}${stat("🧾 จำนวนบิล",N(sales.bills),"blue")} ${stat("💸 ค่าใช้จ่าย",B(ex.total),"red")} ${stat("📈 กำไรเบื้องต้น",B(d.profit),Number(d.profit)>=0?"green":"red")}</div>${details("sale","📄 ดูรายการขาย",(sales.list||[]).map(x=>`<p class="rpt-line"><b>${E(x.time)} ${E(x.billNo)}</b><span>${B(x.net)} ${E(x.payment)}</span></p>`).join("")||"ไม่มีรายการ")}${details("top","🏆 สินค้าขายดี Top 10",bars(d.topProducts||[],"#ff9800",x=>x.total,x=>x.name))}${details("income","💵 หมวดรายรับอื่น",bars(inc.categories||[],"#43a047"))}${details("expense","💸 หมวดค่าใช้จ่าย",bars(ex.categories||[],"#e53935"))}`;}
function monthly(d){if(!d)return loading();const sales=d.sales||{},ex=d.expenses||{},inc=d.otherIncome||{},c=d.cost||{};return `${nav(`${MS[d.month]||""} ${d.yearBE||""}`,"month-prev","month-next")}<div class="rpt-stats">${stat("💰 รายรับรวม",B(d.totalIncome),"green",`ขาย ${B(sales.total)} + อื่นๆ ${B(inc.total)}`)}${stat("🧾 เฉลี่ยต่อบิล",B(sales.avg),"blue",`${N(sales.bills)} บิล`)}${stat("💸 ค่าใช้จ่าย",B(ex.total),"red")} ${stat("📈 กำไรเบื้องต้น",B(d.profit),Number(d.profit)>=0?"green":"red")}</div>${card("📊 รายรับรวมรายวัน",bars(d.dailyChart||[],"#43a047",x=>x.income,x=>`วันที่ ${x.day}`))}${details("m-channel","🚚 ช่องทางขาย",bars(sales.channels||[],"#2196f3"))}${details("m-pay","💳 วิธีชำระ",bars(sales.payments||[],"#ff9800"))}${details("m-exp","💸 หมวดค่าใช้จ่าย",bars(ex.categories||[],"#e53935"))}${card("🏭 ต้นทุนวิเคราะห์",`<div class="rpt-cost"><p>วัสดุ/อุปกรณ์ <b>${B(c.material)}</b></p><p>Outsource <b>${B(c.outsource)}</b></p><p>ซื้อมาขาย <b>${B(c.purchase)}</b></p><p>ค่าแรงช่าง <b>${B((Number(c.laborPiece)||0)+(Number(c.laborDaily)||0))}</b></p><p class="total">กำไรสุทธิ (เงินสด) <b>${B(d.netProfit)}</b></p></div>`)}`;}
function yearly(d){if(!d)return loading();const t=d.total||{};return `${nav(`ปี พ.ศ. ${d.yearBE||""}`,"year-prev","year-next")}<div class="rpt-stats">${stat("💰 รายรับรวมทั้งปี",B(t.income),"green",`ขาย ${B(t.sales)} + อื่นๆ ${B(t.otherIncome)}`)}${stat("🧾 บิลขาย",N(t.bills),"blue")} ${stat("💸 ค่าใช้จ่ายรวม",B(t.expense),"red")} ${stat("📈 กำไรเบื้องต้น",B(t.profit),Number(t.profit)>=0?"green":"red")}</div>${card("📊 เปรียบเทียบรายเดือน",bars(d.months||[],"#42a5f5",x=>x.income,x=>MS[x.month]))}${card("🏭 ต้นทุนสินค้า (ทั้งปี)",`<div class="rpt-cost">${Object.entries(t.costDetail||{}).filter(([,v])=>typeof v==="number").map(([a,v])=>`<p>${E({material:"วัสดุ/อุปกรณ์",outsource:"Outsource",purchase:"ซื้อมาขาย",laborPiece:"ค่าแรงช่างรายชิ้น",laborDaily:"ค่าแรงช่างรายวัน",recurring:"ค่าใช้จ่ายประจำ",investment:"เงินลงทุน"}[a]||a)} <b>${B(v)}</b></p>`).join("")}<p class="total">กำไรสุทธิ (เงินสด) <b>${B(t.netProfit)}</b></p></div>`)}`;}
function top(d){const p=d?.topProducts||[];return `<div class="rpt-switch"><button class="${S.topMode==="month"?"active":""}" data-rpt="top-mode" data-mode="month">รายเดือน</button><button class="${S.topMode==="year"?"active":""}" data-rpt="top-mode" data-mode="year">รายปี</button></div>${nav(S.topMode==="month"?`${MS[S.topMonth]} ${S.topYear+543}`:`ปี พ.ศ. ${S.topYear+543}`,"top-prev","top-next")}${card("🏆 สินค้าขายดี",bars(p,"#ff9800",x=>x.total,x=>`${x.name} (${N(x.qty)} ชิ้น)`))}`;}
function compare(a,b){if(!a||!b)return loading();const ta=a.total||{},tb=b.total||{};return `<div class="rpt-compare-select"><select data-rpt-field="cmpA">${yearsOptions(S.cmpA)}</select><b>เทียบกับ</b><select data-rpt-field="cmpB">${yearsOptions(S.cmpB)}</select></div><div class="rpt-compare">${stat(`พ.ศ. ${a.yearBE}`,B(ta.income),"green",`กำไร ${B(ta.netProfit)}`)}${stat(`พ.ศ. ${b.yearBE}`,B(tb.income),"blue",`กำไร ${B(tb.netProfit)}`)}</div>${card("📊 เปรียบเทียบรายรับรายเดือน",bars((a.months||[]).map((x,i)=>({month:MS[x.month],income:Number(x.income)||0,expense:Number(b.months?.[i]?.income)||0})),"#42a5f5",x=>x.income,x=>x.month)+`<div class="rpt-legend">สีน้ำเงิน: ${a.yearBE} · สีส้ม: ${b.yearBE}</div>`+bars((b.months||[]).map(x=>({month:MS[x.month],income:x.income})),"#ff9800",x=>x.income,x=>x.month))}`;}
function cost(d){if(!d)return loading();const m=d.monthSummary||{},y=d.yearSummary||{},detailRows=d.details||{};return `${nav(`${MS[S.costMonth]} ${S.costYear+543}`,"cost-prev","cost-next")}<div class="rpt-notice">ℹ️ หน้านี้ใช้วิเคราะห์ต้นทุน ไม่ใช่เงินสดจ่ายเพิ่ม</div><div class="rpt-stats">${stat("🏭 ต้นทุนวิเคราะห์รวม",B(m.total),"red")} ${stat("📈 ต้นทุนรวมทั้งปี",B(y.total),"blue")}</div>${[["🏭 วัตถุดิบ/อุปกรณ์","material"],["🚚 Outsource","outsource"],["🛒 ซื้อมาขาย","purchase"],["🖌️ ค่าแรงช่างรายชิ้น","laborPiece"],["📅 ค่าแรงช่างรายวัน","laborDaily"]].map(([n,key])=>details(`cost-${key}`,`${n} ${B(m[key])}`,(detailRows[key]||[]).map(x=>`<p class="rpt-line"><span>${E(x.date)} ${E(x.desc)}</span><b>${B(x.amount)}</b></p>`).join("")||"ไม่มีรายการ")).join("")}`;}
function cash(d){if(!d)return loading();const rows=(d.months||[]).filter(x=>x.active),inflow=rows.reduce((n,x)=>n+Number(x.inflow||0),0),out=rows.reduce((n,x)=>n+Number(x.outflow||0),0),end=rows.at(-1)?.cumulative;return `${nav(`ปี พ.ศ. ${d.yearBE||""}`,"cash-prev","cash-next")}<section class="rpt-start"><div><small>💰 เงินสดยกมาต้นปี</small><b>${d.brought==null?"-":B(d.brought)}</b></div><button data-rpt="cash-settings">⚙️ ตั้งต้น</button></section><div class="rpt-stats">${stat("💰 เงินเข้าทั้งปี",B(inflow),"green")} ${stat("💸 เงินออกทั้งปี",B(out),"red")} ${stat("🏦 เงินสดสิ้นปี",end==null?"-":B(end),Number(end)>=0?"green":"red")}</div>${card("📈 เงินสดสะสม",bars(rows,"#2196f3",x=>Math.max(0,x.cumulative),x=>MS[x.month]))}${details("cash-table","📋 ตารางรายเดือน",`<div class="rpt-table"><table><thead><tr><th>เดือน</th><th>เข้า</th><th>ออก</th><th>สุทธิ</th><th>คงเหลือ</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${MS[x.month]}</td><td>${B(x.inflow)}</td><td>${B(x.outflow)}</td><td>${B(x.net)}</td><td><b>${B(x.cumulative)}</b></td></tr>`).join("")}</tbody></table></div>`)}${card("📦 มูลค่าสินค้าคงเหลือ",["front","material"].map(x=>`<p class="rpt-line"><span>${x==="front"?"🏺 สินค้าหน้าร้าน":"⚪ ของขาว + วัตถุดิบ"}<small>ราคาขาย ${B(d.stock?.[x]?.sale)} · ต้นทุน ${B(d.stock?.[x]?.cost)}</small></span><b>${N(d.stock?.[x]?.count)} รายการ</b></p>`).join(""))}`;}
function printView(d){if(!d)return `<button class="rpt-run" data-rpt="print-load">🖨️ สร้างรายงานเดือน ${MS[S.printMonth]} ${S.printYear+543}</button>`;const rows=Object.entries(d.days||{}).sort((a,b)=>Number(a[0])-Number(b[0]));return `${nav(`${MS[S.printMonth]} ${S.printYear+543}`,"print-prev","print-next")}<button class="rpt-run" data-rpt="print-window">🖨️ พิมพ์รายงาน</button><section id="reportPrintArea" class="rpt-print"><h2>รายงานเงินสดรับ - จ่าย</h2><p>${E(R.shop.name||"ร้านค้า")}</p><p>ประจำเดือน ${E(d.monthName||"")} พ.ศ. ${E(d.yearBE||"")}</p><table><thead><tr><th>วันที่</th><th>รายการ</th><th>รายรับ</th><th>รายจ่าย</th></tr></thead><tbody>${rows.map(([day,v])=>[...(v.income||[]).map((x,i)=>`<tr><td>${i?"":day}</td><td>${E(x.detail)}</td><td>${N(x.amount)}</td><td></td></tr>`),...(v.expense||[]).map((x,i)=>`<tr><td> </td><td>${E(x.detail)}</td><td></td><td>${N(x.amount)}</td></tr>`)].join("")).join("")}<tr><th colspan="2">รวมเดือน</th><th>${N(d.totalIncome)}</th><th>${N(d.totalExpense)}</th></tr><tr><th colspan="2">กำไร/ขาดทุนเบื้องต้น</th><th colspan="2">${N(d.profit)}</th></tr></tbody></table></section>`;}
function yearsOptions(selected){const years=S.data?.init?.years||[new Date().getFullYear()];return years.map(x=>`<option value="${x}" ${Number(x)===Number(selected)?"selected":""}>พ.ศ. ${Number(x)+543}</option>`).join("");}
function loading(){return '<div class="rpt-loading">⏳ กำลังโหลดข้อมูล…</div>';}
function content(){const dailyData=S.cache[k("daily",dateKey(S.date))]||S.data?.daily;const monthData=S.cache[k("month",S.year,S.month)],yearData=S.cache[k("year",S.yearTab)],topData=S.cache[k(S.topMode==="month"?"month":"year",S.topYear,S.topMode==="month"?S.topMonth:"")],a=S.cache[k("year",S.cmpA)],b=S.cache[k("year",S.cmpB)],co=S.cache[k("cost",S.costYear,S.costMonth)],ca=S.cache[k("cash",S.cashYear)],pr=S.cache[k("print",S.printYear,S.printMonth)];const view=[()=>daily(dailyData),()=>monthly(monthData),()=>yearly(yearData),()=>top(topData),()=>compare(a,b),()=>printView(pr),()=>cost(co),()=>cash(ca)][S.tab];return view?view():"";}
function modal(){if(!S.modal)return "";const d=S.cache[k("cash",S.cashYear)]||{},months=MS.slice(1);return `<div class="rpt-modal"><form class="rpt-modal-card" data-rpt-form="cash"><button type="button" class="rpt-close" data-rpt="modal-close">×</button><h2>💰 ตั้งค่าเงินสดตั้งต้น</h2><label>เงินสดตั้งต้น (บาท)<input name="amount" type="number" value="${Number(d.startAmount)||0}" inputmode="decimal"></label><label>เดือนเริ่ม<select name="month">${months.map((x,i)=>`<option value="${i+1}" ${Number(d.startMonth)===i+1?"selected":""}>${x}</option>`).join("")}</select></label><label>ปี (พ.ศ.)<input name="yearBE" type="number" value="${(Number(d.startYear)||S.cashYear)+543}"></label><p>💡 เงินสดที่มีจริง ณ เดือนที่เริ่มใช้ระบบ</p><button class="rpt-run">✅ บันทึก</button></form></div>`;}
function draw(){if(!active())return;R.root.innerHTML=`<section class="rpt-page"><header class="rpt-top"><button data-rpt="back">← กลับ</button><h1>📊 ดูสรุป</h1></header><nav class="rpt-tabs">${tabs.map(([name],i)=>`<button class="${S.tab===i?"active":""}" data-rpt="tab" data-tab="${i}">${name}</button>`).join("")}</nav><div class="rpt-refresh"><button data-rpt="refresh">🔄 อัปเดตข้อมูลล่าสุด</button></div><main class="rpt-content">${content()}</main></section>`;R.root.querySelectorAll("[data-rpt]").forEach(button=>button.addEventListener("click",click));R.root.querySelectorAll("[data-rpt-field]").forEach(field=>field.addEventListener("change",change));const layer=document.querySelector("#floatingLayer");if(layer){layer.innerHTML=modal();layer.onclick=click;layer.onchange=change;layer.onsubmit=submit;}}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
async function fetchData(type,...args){const key=k(type,...args);if(S.cache[key])return S.cache[key];if(S.pending[key])return S.pending[key];const fn={daily:()=>R.api.reportDaily(R.token,args[0]),month:()=>R.api.reportMonthly(R.token,args[0],args[1]),year:()=>R.api.reportYearly(R.token,args[0]),cost:()=>R.api.reportCost(R.token,args[0],Number(args[1])-1),cash:()=>R.api.reportCashflow(R.token,args[0]),print:()=>R.api.reportPrint(R.token,args[0],Number(args[1])-1)}[type];S.pending[key]=fn().then(r=>{if(!r.ok)throw new Error(r.message||"โหลดข้อมูลไม่สำเร็จ");S.cache[key]=r.result;return r.result;}).finally(()=>delete S.pending[key]);return S.pending[key];}
async function ensure(){const tasks=[[0,"daily",dateKey(S.date)],[1,"month",S.year,S.month],[2,"year",S.yearTab],[6,"cost",S.costYear,S.costMonth],[7,"cash",S.cashYear]];for(const [tab,t,...a] of tasks){try{await fetchData(t,...a);if(active()&&S.tab===tab)draw();}catch(ignore){/* Preload never blocks the tab the user is viewing. */}}}
function shiftMonth(fieldY,fieldM,n){S[fieldM]+=n;if(S[fieldM]>12){S[fieldM]=1;S[fieldY]++;}if(S[fieldM]<1){S[fieldM]=12;S[fieldY]--;}}
async function click(e){const b=e.target.closest("[data-rpt]");if(!b)return;const a=b.dataset.rpt;e.preventDefault();e.stopImmediatePropagation();if(a==="back")return R.back();if(a==="tab"){S.tab=Number(b.dataset.tab);draw();return loadTab();}if(a==="detail"){S.open[b.dataset.id]=!S.open[b.dataset.id];return draw();}if(a==="refresh"){S.cache={};R.toast("⏳ กำลังอัปเดตข้อมูลล่าสุด…");draw();return loadTab(true);}if(a==="day-prev"||a==="day-next"){S.date.setDate(S.date.getDate()+(a==="day-prev"?-1:1));draw();return fetchData("daily",dateKey(S.date)).then(draw);}if(a==="month-prev"||a==="month-next"){shiftMonth("year","month",a==="month-prev"?-1:1);draw();return fetchData("month",S.year,S.month).then(draw);}if(a==="year-prev"||a==="year-next"){S.yearTab+=a==="year-prev"?-1:1;draw();return fetchData("year",S.yearTab).then(draw);}if(a==="top-mode"){S.topMode=b.dataset.mode;draw();return loadTab();}if(a==="top-prev"||a==="top-next"){if(S.topMode==="month")shiftMonth("topYear","topMonth",a==="top-prev"?-1:1);else S.topYear+=a==="top-prev"?-1:1;draw();return loadTab();}if(a==="cost-prev"||a==="cost-next"){shiftMonth("costYear","costMonth",a==="cost-prev"?-1:1);draw();return fetchData("cost",S.costYear,S.costMonth).then(draw);}if(a==="cash-prev"||a==="cash-next"){S.cashYear+=a==="cash-prev"?-1:1;draw();return fetchData("cash",S.cashYear).then(draw);}if(a==="print-prev"||a==="print-next"){shiftMonth("printYear","printMonth",a==="print-prev"?-1:1);S.cache[k("print",S.printYear,S.printMonth)]=null;return draw();}if(a==="print-load"){draw();return fetchData("print",S.printYear,S.printMonth).then(draw);}if(a==="print-window"){const x=document.querySelector("#reportPrintArea");const w=window.open("","_blank");if(w&&x){w.document.write(`<html><head><title>รายงานเงินสดรับ-จ่าย</title><style>body{font-family:sans-serif;padding:20px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccc;padding:6px;text-align:left}</style></head><body>${x.outerHTML}</body></html>`);w.document.close();w.print();}return;}if(a==="cash-settings"){S.modal=true;return draw();}if(a==="modal-close"){S.modal=null;return draw();}}
function change(e){if(e.target.dataset.rptField==="cmpA"||e.target.dataset.rptField==="cmpB"){S[e.target.dataset.rptField]=Number(e.target.value);draw();loadTab();}}
async function submit(e){if(e.target.dataset.rptForm!=="cash")return;e.preventDefault();const f=new FormData(e.target),r=await R.api.reportCashflowStartSave(R.token,Number(f.get("amount")),Number(f.get("yearBE"))-543,Number(f.get("month")));if(!r.ok)return R.toast(`❌ ${r.message||"บันทึกไม่สำเร็จ"}`);S.cache={};S.modal=null;R.toast("✅ บันทึกเงินสดตั้งต้นแล้ว");draw();loadTab();}
function loadTab(){const jobs=[["daily",dateKey(S.date)],["month",S.year,S.month],["year",S.yearTab],[S.topMode==="month"?"month":"year",S.topYear,S.topMode==="month"?S.topMonth:undefined],["year",S.cmpA],["year",S.cmpB],["print",S.printYear,S.printMonth],["cost",S.costYear,S.costMonth],["cash",S.cashYear]];const [type,...args]=jobs[S.tab];return fetchData(type,...args.filter(x=>x!==undefined)).then(()=>active()&&draw()).catch(error=>R.toast(`❌ ${error.message||error}`));}
export async function renderReport(root,api,token,onBack,context={}){R={root,api,token,back:onBack,toast:context.toast||(()=>{}),shop:{}};if(!escapeBound){escapeBound=true;document.addEventListener("keydown",e=>{if(e.key==="Escape"&&S.modal){S.modal=null;draw();}});window.addEventListener("suphan-data-mutated",()=>{S.cache={};});}if(!S.data){S.loading=true;draw();try{const r=await api.reportBootstrap(token);if(!r.ok)throw new Error(r.message||"เปิดหน้าสรุปไม่สำเร็จ");S.data=r.result;R.shop=r.result.shop||{};S.year=S.yearTab=S.costYear=S.cashYear=Number(r.result.init?.curYear)||S.year;S.month=S.costMonth=S.topMonth=Number(r.result.init?.curMonth)||S.month;S.topYear=S.year;S.cmpA=S.year;S.cmpB=(r.result.init?.years||[]).filter(x=>Number(x)!==S.year).at(-1)||S.year-1;}catch(error){if(active())R.toast(`❌ ${error.message||error}`);}finally{S.loading=false;}}if(active()){draw();ensure();}}
