// Workshop PWA is a thin UI over the proven GAS workshop functions.
// Never calculate wage/OT/stock in this file: 08_Workshop.gs remains canonical.
const S={api:null,token:"",onBack:null,toast:()=>{},data:null,tab:"assign",step:"เขียนลายน้ำทอง",date:"",attendance:{},monthly:{},wages:{},selected:null,picker:false,saving:false};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const n=v=>(Number(v)||0).toLocaleString("th-TH");
const iso=d=>{const x=d instanceof Date?d:(d?new Date(d):new Date());return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`;};
const thaiDate=d=>new Date(`${d}T00:00:00`).toLocaleDateString("th-TH",{weekday:"long",year:"numeric",month:"long",day:"numeric"});
const familyEmployees=()=>((S.data?.employees)||[]).filter(x=>x&&x.name);
const today=()=>iso();

function top(){return `<header class="pwa-workshop-topbar"><button data-a="back" type="button">← กลับ</button><h1>🖌️ จัดการงานช่าง</h1><span>${esc(S.displayUser||"")}</span></header>`;}
function tabs(){const list=[["assign","🖌️ จ่ายงานเขียน"],["receive","📦 ช่างส่งงาน"],["firing","🔥 คิวเผา"],["attendance","📅 ลงเวลารายวัน"],["wage","💰 สรุป/ค่าจ้าง"]];return `<nav class="pwa-workshop-tabs">${list.map(([id,label])=>`<button type="button" data-tab="${id}" class="${S.tab===id?"active":""}">${label}</button>`).join("")}</nav>`;}
function productName(x){return [x?.name||x?.product,x?.size,x?.pattern].filter(Boolean).join(" · ");}
function assign(){const workers=familyEmployees();const selected=S.selected;return `<section class="pwa-workshop-panel"><div class="pwa-workshop-step"><button data-step="เขียนลายน้ำทอง" class="active">🖌️ เขียนลายน้ำทอง</button><button data-step="วนทอง">🔁 วนทอง</button></div><form id="workshopJobForm"><label>👤 ช่าง<select id="wsWorker"><option value="">-- เลือกช่าง --</option>${workers.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}${x.type?` (${esc(x.type)})`:""}</option>`).join("")}</select></label><label>⚪ ของขาวที่จ่าย (หักสต๊อก)<button class="pwa-workshop-picker ${selected?"selected":""}" type="button" data-a="picker">${selected?esc(productName(selected)):"🔍 กดเพื่อค้นหาและเลือกของขาว"}<b>›</b></button></label><div class="pwa-workshop-grid"><label>📦 จำนวน<input id="wsQty" inputmode="numeric" min="1" step="1" type="number" value="1"></label><label>💰 ค่าจ้าง/ชิ้น<input id="wsPrice" inputmode="decimal" min="0" step="0.01" type="number"></label><label>🏷️ ติดสติกเกอร์<input id="wsStickerQty" inputmode="numeric" min="0" step="1" type="number" value="0"></label><label>💰 ค่าสติกเกอร์/ชิ้น<input id="wsStickerRate" inputmode="decimal" min="0" step="0.01" type="number" value="5"></label><label>📅 วันที่จ่ายงาน<input id="wsJobDate" type="date" value="${today()}" max="${today()}"></label><label>📅 กำหนดส่ง<input id="wsDueDate" type="date" value="${iso(new Date(Date.now()+259200000))}"></label></div><p class="pwa-workshop-note">ระบบเดิมจะตรวจจำนวนของขาว ตัดสต๊อก และใช้ LockService ก่อนบันทึก</p><button class="pwa-workshop-save" type="submit" ${S.saving?"disabled":""}>${S.saving?"⏳ กำลังบันทึก...":"💾 บันทึกจ่ายงาน"}</button></form></section>`;}
function receive(){return `<section class="pwa-workshop-placeholder"><span>📦</span><h2>ช่างส่งงาน</h2><p>แท็บนี้อยู่ระหว่างออกแบบขั้นตอนใหม่</p><small>ยังไม่มีการแสดงรายการหรือปุ่มบันทึก เพื่อป้องกันการส่งงานผิด workflow</small></section>`;}
function firing(){const rows=S.data?.firing||[];return `<section class="pwa-workshop-panel"><div class="pwa-workshop-title"><h2>🔥 คิวเผา</h2><button data-a="refresh" type="button">↻ รีเฟรช</button></div>${rows.length?`<div class="pwa-fire-list">${rows.map(x=>`<article data-row="${Number(x.row||x.rowIdx)}" data-qty="${Number(x.qty)}"><div><strong>${esc(productName(x))}</strong><small>${esc(x.sku||"")} · รอเผา ${n(x.qty)} ชิ้น</small></div><label>ผ่าน<input data-f="pass" type="number" min="0" value="${Number(x.qty)}"></label><label>เสีย<input data-f="damaged" type="number" min="0" value="0"></label><button data-a="fire" type="button">✅ ยืนยัน</button></article>`).join("")}</div>`:`<p class="pwa-workshop-empty">ไม่มีงานรอเผา</p>`}</section>`;}
function attendance(){const records=S.attendance[S.date]||[];const byName={};records.forEach(x=>byName[x.name]=x);const workers=familyEmployees().filter(x=>String(x.payMethod||x.type||"").includes("วัน")||String(x.type||"").includes("รายวัน"));const people=workers.length?workers:familyEmployees();return `<section class="pwa-workshop-panel"><div class="pwa-workshop-title"><h2>📅 ลงเวลาช่างรายวัน</h2><button data-a="month" type="button">ดูรายเดือน</button></div><div class="pwa-date-nav"><button data-a="prev-date" type="button">◀</button><input id="attDate" type="date" max="${today()}" value="${S.date}"><button data-a="next-date" type="button" ${S.date>=today()?"disabled":""}>▶</button></div><p class="pwa-workshop-note">${thaiDate(S.date)} · OT เป็นการบันทึกโดยเจ้าของร้านเท่านั้น ระบบไม่คิดอัตโนมัติ</p>${S.date<today()?`<label class="pwa-workshop-reason">เหตุผลการแก้ไขย้อนหลัง<input id="attReason" maxlength="200" placeholder="จำเป็นสำหรับวันย้อนหลัง"></label>`:""}<div class="pwa-attendance-list">${people.map((x,i)=>attCard(x,byName[x.name]||{},i)).join("")}</div><button class="pwa-workshop-save" data-a="save-attendance" type="button" ${S.saving?"disabled":""}>${S.saving?"⏳ กำลังบันทึก...":"💾 บันทึกวันทำงาน"}</button></section>`;}
function attCard(x,r,i){const present=String(r.present||"")==="มา";const factor=Number(r.dayFactor)===.5?.5:1;return `<article class="pwa-att-card" data-att="${i}" data-name="${esc(x.name)}" data-type="${esc(x.type||"")}" data-rate="${Number(r.rate??x.rate??0)}"><header><strong>${esc(x.name)}</strong><small>${esc(x.type||"")} · ฿${n(r.rate??x.rate??0)}/วัน</small><label class="pwa-switch"><input data-x="present" type="checkbox" ${present?"checked":""}><span>มาทำงาน</span></label></header><div class="pwa-workshop-grid"><label>เข้า<input data-x="in" type="time" value="${esc(r.timeIn||"")}"></label><label>ออก<input data-x="out" type="time" value="${esc(r.timeOut||"")}"></label><label>คิดค่าแรง<select data-x="factor"><option value="1" ${factor===1?"selected":""}>เต็มวัน</option><option value="0.5" ${factor===.5?"selected":""}>ครึ่งวัน</option></select></label><label>OT (ชม.)<input data-x="ot" inputmode="decimal" min="0" step="0.5" value="${Number(r.otHours)||0}"></label><label class="pwa-att-ot">เริ่ม OT<input data-x="otStart" type="time" value="${esc(r.otStart||"")}"></label><label class="pwa-att-ot">สิ้นสุด OT<input data-x="otEnd" type="time" value="${esc(r.otEnd||"")}"></label></div><label>หมายเหตุ<input data-x="note" maxlength="200" value="${esc(r.note||"")}"></label></article>`;}
function monthly(){const key=S.date.slice(0,7),rows=S.monthly[key]||[];return `<section class="pwa-workshop-panel"><div class="pwa-workshop-title"><h2>📅 รายเดือน</h2><button data-a="daily" type="button">กลับรายวัน</button></div><input id="monthInput" type="month" value="${key}"><div class="pwa-monthly-list">${rows.length?rows.map(x=>`<article><b>วันที่ ${esc(x.date)}</b><strong>${esc(x.name)}</strong><span>${esc(x.timeIn||"–")} – ${esc(x.timeOut||"–")} · ${Number(x.dayFactor)===.5?"ครึ่งวัน":"เต็มวัน"}</span></article>`).join(""):'<p class="pwa-workshop-empty">ยังไม่มีข้อมูลลงเวลาในเดือนนี้</p>'}</div></section>`;}
function periodOptions(){let a=[];const now=new Date();for(let i=0;i<6;i++){const d=new Date(now.getFullYear(),now.getMonth()-i,1),end=new Date(d.getFullYear(),d.getMonth()+1,0);a.push([iso(d),iso(end),d.toLocaleDateString("th-TH",{month:"long",year:"numeric"})]);}return a;}
function wage(){const periods=periodOptions(),key=S.wageKey||`${periods[0][0]}|${periods[0][1]}`,data=S.wages[key];const people=[...(data?.pieceWork||[]),...(data?.dailyWork||[]),...(data?.monthly||[])];return `<section class="pwa-workshop-panel"><div class="pwa-workshop-title"><h2>💰 สรุป/ค่าจ้าง</h2><button data-a="load-wage" type="button">↻ โหลดล่าสุด</button></div><select id="wagePeriod">${periods.map(p=>`<option value="${p[0]}|${p[1]}" ${key===`${p[0]}|${p[1]}`?"selected":""}>${p[2]}</option>`).join("")}</select>${!data?'<p class="pwa-workshop-empty">กำลังโหลดสรุปค่าแรง…</p>':`<div class="pwa-wage-total"><span>รวมค่าแรงงวดนี้</span><b>฿${n(people.reduce((sum,x)=>sum+Number(x.netPay??x.total??x.wage??0),0))}</b></div><div class="pwa-wage-list">${people.length?people.map(x=>`<article><strong>${esc(x.worker||x.name||"")}</strong><small>${esc(x.type||"")} · ${n(x.qty??x.days??x.count??0)} รายการ</small><b>฿${n(x.netPay??x.total??x.wage??0)}</b></article>`).join(""):'<p class="pwa-workshop-empty">ไม่มีข้อมูลค่าแรงในงวดนี้</p>'}</div>`}</section>`;}
function picker(){if(!S.picker)return "";const q=String(S.pickerQuery||"").toLowerCase(),rows=(S.data?.whitewares||[]).filter(x=>[x.sku,x.name,x.product,x.size,x.pattern].join(" ").toLowerCase().includes(q));return `<div class="pwa-workshop-modal"><section role="dialog" class="pwa-workshop-dialog"><header><strong>⚪ เลือกของขาว</strong><button data-a="close-picker" type="button">×</button></header><input id="wsPickerSearch" placeholder="ค้นหาชื่อหรือรหัสสินค้า" value="${esc(S.pickerQuery||"")}"><div>${rows.length?rows.map((x,i)=>`<button data-a="choose" data-i="${(S.data.whitewares||[]).indexOf(x)}" type="button"><strong>${esc(productName(x))}</strong><small>${esc(x.sku||"")} · คงเหลือ ${n(x.balance)} ชิ้น</small></button>`).join(""):'<p class="pwa-workshop-empty">ไม่พบของขาว</p>'}</div></section></div>`;}
function markup(){let body=S.tab==="assign"?assign():S.tab==="receive"?receive():S.tab==="firing"?firing():S.tab==="attendance"?attendance():S.tab==="monthly"?monthly():wage();return `<section class="pwa-workshop-page">${top()}<main>${tabs()}${body}</main>${picker()}</section>`;}
function render(root){root.innerHTML=markup();bind(root);}
function bind(root){root.querySelector(".pwa-workshop-page")?.addEventListener("click",e=>click(root,e));root.querySelector("#workshopJobForm")?.addEventListener("submit",e=>saveJob(root,e));root.querySelector("#attDate")?.addEventListener("change",e=>changeDate(root,e.target.value));root.querySelector("#monthInput")?.addEventListener("change",e=>loadMonth(root,e.target.value));root.querySelector("#wagePeriod")?.addEventListener("change",e=>{S.wageKey=e.target.value;render(root);loadWage(root);});root.querySelector("#wsPickerSearch")?.addEventListener("input",e=>{S.pickerQuery=e.target.value;render(root);root.querySelector("#wsPickerSearch")?.focus();});root.querySelector(".pwa-workshop-modal")?.addEventListener("click",e=>{if(e.target.closest(".pwa-workshop-dialog"))return;S.picker=false;render(root);});}
function click(root,e){const b=e.target.closest("button");if(!b)return;if(b.dataset.tab){S.tab=b.dataset.tab;render(root);if(S.tab==="firing")load(root);if(S.tab==="attendance")loadAttendance(root,S.date);if(S.tab==="wage")loadWage(root);return;}const a=b.dataset.a;if(a==="back")return S.onBack();if(a==="picker"){S.picker=true;S.pickerQuery="";render(root);setTimeout(()=>root.querySelector("#wsPickerSearch")?.focus(),50);return;}if(a==="close-picker"){S.picker=false;render(root);return;}if(a==="choose"){S.selected=(S.data?.whitewares||[])[Number(b.dataset.i)]||null;S.picker=false;render(root);return;}if(a==="refresh")return load(root,true);if(a==="fire")return confirmFire(root,b.closest("article"));if(a==="prev-date")return changeDate(root,iso(new Date(`${S.date}T00:00:00`).getTime()-86400000));if(a==="next-date")return changeDate(root,iso(new Date(`${S.date}T00:00:00`).getTime()+86400000));if(a==="month"){S.tab="monthly";render(root);return loadMonth(root,S.date.slice(0,7));}if(a==="daily"){S.tab="attendance";render(root);return;}if(a==="save-attendance")return saveAttendance(root);if(a==="load-wage")return loadWage(root,true);}
async function load(root,force=false){try{const r=await S.api.workshopBootstrap(S.token);if(!r?.ok)throw new Error(r?.message||r?.error||"โหลดงานช่างไม่สำเร็จ");S.data=r.result||{};render(root);}catch(e){if(!S.data)S.toast(`เปิดหน้าจัดการงานช่างไม่สำเร็จ: ${e.message||e}`);}}
async function saveJob(root,e){e.preventDefault();if(!S.selected)return S.toast("กรุณาเลือกของขาว");const val=id=>root.querySelector(id)?.value||"";const data={worker:val("#wsWorker"),step:"เขียนลายน้ำทอง",whitewareSku:S.selected.sku,product:S.selected.name||S.selected.product,size:S.selected.size||"",pattern:S.selected.pattern||"",sku:S.selected.sku,qty:Number(val("#wsQty")),priceEach:Number(val("#wsPrice")),stickerQty:Number(val("#wsStickerQty")),stickerRate:Number(val("#wsStickerRate")),jobDate:val("#wsJobDate"),dueDate:val("#wsDueDate")};if(!data.worker)return S.toast("กรุณาเลือกช่าง");S.saving=true;render(root);try{const r=await S.api.workshopSaveJob(S.token,data),o=r?.result;if(!r?.ok||!o?.success)throw new Error(o?.message||r?.message||"บันทึกไม่สำเร็จ");S.toast(o.message||"บันทึกจ่ายงานสำเร็จ");S.selected=null;await load(root,true);}catch(x){S.toast(`❌ ${x.message||x}`);}finally{S.saving=false;render(root);}}
async function confirmFire(root,row){const pass=Number(row.querySelector('[data-f="pass"]')?.value),damaged=Number(row.querySelector('[data-f="damaged"]')?.value),qty=Number(row.dataset.qty);if(!Number.isInteger(pass)||!Number.isInteger(damaged)||pass<0||damaged<0||pass+damaged!==qty)return S.toast(`จำนวนผ่าน + เสีย ต้องเท่ากับ ${n(qty)}`);try{const r=await S.api.workshopConfirmFiring(S.token,Number(row.dataset.row),pass,damaged),o=r?.result;if(!r?.ok||!o?.success)throw new Error(o?.message||r?.message||"บันทึกไม่สำเร็จ");S.toast(o.message||"บันทึกผลเผาสำเร็จ");await load(root,true);}catch(e){S.toast(`❌ ${e.message||e}`);}}
async function changeDate(root,date){if(!date||date>today())return;S.date=date;render(root);await loadAttendance(root,date);}
async function loadAttendance(root,date){if(S.attendance[date]){render(root);return;}try{const r=await S.api.workshopAttendance(S.token,date);if(!r?.ok)throw new Error(r?.message||"โหลดลงเวลาไม่สำเร็จ");S.attendance[date]=r.result||[];if(S.tab==="attendance")render(root);}catch(e){S.toast(`โหลดลงเวลาไม่สำเร็จ: ${e.message||e}`);}}
async function loadMonth(root,key){if(!key)return;const [year,month]=key.split("-").map(Number);S.tab="monthly";render(root);if(S.monthly[key])return;try{const r=await S.api.workshopMonthlyAttendance(S.token,year,month);if(!r?.ok)throw new Error(r?.message||"โหลดข้อมูลรายเดือนไม่สำเร็จ");S.monthly[key]=r.result||[];if(S.tab==="monthly")render(root);}catch(e){S.toast(`โหลดข้อมูลรายเดือนไม่สำเร็จ: ${e.message||e}`);}}
async function saveAttendance(root){const isPast=S.date<today(),reason=root.querySelector("#attReason")?.value.trim()||"";if(isPast&&!reason)return S.toast("กรุณาระบุเหตุผลการแก้ไขย้อนหลัง");const items=[...root.querySelectorAll(".pwa-att-card")].map(card=>({name:card.dataset.name,type:card.dataset.type,rate:Number(card.dataset.rate)||0,present:card.querySelector('[data-x="present"]')?.checked,timeIn:card.querySelector('[data-x="in"]')?.value||"",timeOut:card.querySelector('[data-x="out"]')?.value||"",dayFactor:Number(card.querySelector('[data-x="factor"]')?.value)||1,otHours:Number(card.querySelector('[data-x="ot"]')?.value)||0,otStart:card.querySelector('[data-x="otStart"]')?.value||"",otEnd:card.querySelector('[data-x="otEnd"]')?.value||"",otReason:reason,note:card.querySelector('[data-x="note"]')?.value||""}));for(const x of items){if(x.present&&x.timeIn&&x.timeOut&&x.timeOut<x.timeIn)return S.toast(`เวลาออกของ ${x.name} ต้องไม่ก่อนเวลาเข้า`);if(x.otHours>0&&!x.present)return S.toast(`ไม่สามารถบันทึก OT ให้ ${x.name} ที่ไม่มาทำงานได้`);}S.saving=true;render(root);try{const r=await S.api.workshopSaveAttendance(S.token,{targetDate:S.date,items,reason}),o=r?.result;if(!r?.ok||!o?.success)throw new Error(o?.message||r?.message||"บันทึกไม่สำเร็จ");delete S.attendance[S.date];S.wages={};S.toast(o.message||"บันทึกวันทำงานสำเร็จ");await loadAttendance(root,S.date);}catch(e){S.toast(`❌ ${e.message||e}`);}finally{S.saving=false;render(root);}}
async function loadWage(root,force=false){const key=S.wageKey||`${periodOptions()[0][0]}|${periodOptions()[0][1]}`;S.wageKey=key;if(S.wages[key]&&!force){render(root);return;}const [start,end]=key.split("|");try{const r=await S.api.workshopWageSummary(S.token,start,end);if(!r?.ok)throw new Error(r?.message||"โหลดสรุปค่าแรงไม่สำเร็จ");S.wages[key]=r.result||{};if(S.tab==="wage")render(root);}catch(e){S.toast(`โหลดสรุปค่าแรงไม่สำเร็จ: ${e.message||e}`);}}
export function renderWorkshop(root,api,token,onBack,context={}){S.api=api;S.token=token;S.onBack=onBack;S.toast=context.toast||(()=>{});S.displayUser=context.displayUser||"";if(!S.date)S.date=today();render(root);if(!S.data)load(root);else load(root);}
