// UI adapter only.  08_Workshop.gs remains the source of truth for all wages,
// attendance, stock deduction and LockService-protected mutations.
const S={api:null,token:"",back:null,toast:()=>{},data:null,tab:"assign",step:"เขียนลายน้ำทอง",pick:false,pickQ:"",chosen:null,day:"",daily:{},months:{},wages:{},wageMode:"half",wageView:"table",wageKey:"",saving:false};
const e=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const m=v=>(Number(v)||0).toLocaleString("th-TH");
const date=v=>{const x=v instanceof Date?v:(v?new Date(v):new Date());return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`;};
const today=()=>date(); const product=x=>[x?.name||x?.product,x?.size,x?.pattern].filter(Boolean).join(" · ");
const workers=()=>S.data?.employees||[];
function top(){return `<header class="pwa-workshop-topbar"><button data-a="back" type="button">← กลับ</button><div>🖌️ จัดการงานช่าง</div></header>`;}
function tabs(){return `<nav class="pwa-workshop-tabs">${[["assign","🖌️ จ่ายงานช่างเขียน"],["receive","📦 ช่างส่งงาน"],["firing","🔥 คิวเผา"],["daily","📅 ลงเวลาช่างรายวัน"],["wage","💰 สรุป/ค่าจ้าง"]].map(x=>`<button data-tab="${x[0]}" class="${S.tab===x[0]?"active":""}">${x[1]}</button>`).join("")}</nav>`;}
function assign(){
  const isGold=S.step==="วนทอง",q=S.chosen,rate=Number(S.data?.goldCycleRate)||180;
  return `<section class="pwa-workshop-panel pwa-job-form">
    <div class="pwa-workshop-step">
      <button data-step="เขียนลาย" class="${!isGold?"active":""}">🖌️ เขียนลาย</button>
      <button data-step="วนทอง" class="${isGold?"active":""}">🔥 วนทอง</button>
    </div>
    <form id="wsForm">
      <label>👤 ช่าง<select id="worker"><option value="">-- เลือกช่าง --</option>${workers().map(x=>`<option value="${e(x.name)}">${e(x.name)}${x.type?` (${e(x.type)})`:""}</option>`).join("")}</select></label>
      ${!isGold?`<label id="whitewareGroup">⚪ ของขาวที่จ่าย (หักสต๊อก)<button type="button" data-a="pick" class="pwa-workshop-picker ${q?"selected":""}">${q?e(product(q)):"🔍 กดเพื่อค้นหาและเลือกของขาว"}<b aria-hidden="true">›</b></button></label>`:""}
      <p class="pwa-auto-info">${isGold?"วนทอง — คิดค่าแรงตามจำนวนครั้งเผา":"เลือกของขาวเพื่อให้ระบบค้นหาค่าจ้างอัตโนมัติ"}</p>
      <div class="pwa-job-rate-row">
        <label>${isGold?"🔥 จำนวนครั้ง (เผาวนทอง)":"📦 จำนวน"}<input id="qty" type="number" inputmode="numeric" min="1" value="1"></label>
        <label>${isGold?"💰 ค่าแรง/ครั้ง":"💰 ค่าจ้าง/ชิ้น"} ${isGold?'<span class="pwa-auto-badge">auto</span>':""}<input id="price" type="number" inputmode="decimal" min="0" value="${isGold?rate:""}"></label>
        <div class="pwa-total-box"><span>รวมค่าแรง</span><b id="jobTotal">฿${m(isGold?rate:0)}</b></div>
      </div>
      ${!isGold?`<div class="pwa-workshop-grid pwa-sticker-row"><label>🏷️ จำนวนติดสติกเกอร์<input id="stickerQty" type="number" inputmode="numeric" min="0" value="0"></label><label>💰 ค่าติดสติกเกอร์/ชิ้น<input id="stickerRate" type="number" inputmode="decimal" min="0" value="5"></label></div>`:""}
      <div class="pwa-workshop-grid"><label>📅 วันที่จ่ายงาน<input id="jobDate" type="date" value="${today()}" max="${today()}"></label>${!isGold?`<label>📅 กำหนดส่ง<input id="dueDate" type="date" value="${date(Date.now()+259200000)}"></label>`:""}</div>
      <p class="pwa-workshop-note">${isGold?"ระบบจะบันทึกงานวนทองเป็นงานเสร็จทันที ตามหลักการเดิมของ GAS":"ตรวจจำนวนของขาวและตัดสต๊อกด้วยระบบ GAS เดิมก่อนบันทึก"}</p>
      <button class="pwa-workshop-save" ${S.saving?"disabled":""}>${S.saving?"⏳ กำลังบันทึก...":"💾 บันทึกจ่ายงาน"}</button>
    </form>
  </section>`;
}
function receive(){return `<section class="pwa-workshop-placeholder"><span>📦</span><h2>ช่างส่งงาน</h2><p>อยู่ระหว่างออกแบบใหม่</p><small>แท็บนี้ยังไม่มีการแสดงรายการหรือการบันทึก</small></section>`;}
function firing(){let rows=S.data?.firing||[];return `<section class="pwa-workshop-panel"><div class="pwa-workshop-title"><h2>🔥 คิวเผา</h2><button data-a="refresh">🔄 รีเฟรช</button></div><div class="pwa-fire-list">${rows.length?rows.map(x=>`<article data-row="${Number(x.row||x.rowIdx)}" data-qty="${Number(x.qty)}"><div><strong>${e(product(x))}</strong><small>${e(x.sku||"")} · รอเผา ${m(x.qty)} ชิ้น</small></div><label>ผ่าน<input data-k="pass" type="number" min="0" value="${Number(x.qty)}"></label><label>เสีย<input data-k="damaged" type="number" min="0" value="0"></label><button data-a="fire">✅ ยืนยัน</button></article>`).join(""):'<p class="pwa-workshop-empty">ไม่มีงานรอเผา</p>'}</div></section>`;}
function dayControls(){return `<div style="display:flex;gap:6px;max-width:500px;margin:0 auto 12px"><button data-a="daily" class="pwa-mode active">📅 รายวัน</button><button data-a="monthly" class="pwa-mode">📆 รายเดือน</button></div><div class="pwa-date-nav"><button data-a="prev">◀</button><div>${new Date(`${S.day}T00:00:00`).toLocaleDateString("th-TH",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}</div><button data-a="next" ${S.day>=today()?"disabled":""}>▶</button></div><input id="dayPick" type="date" max="${today()}" value="${S.day}" class="pwa-date-picker">`;}
function daily(){let got={};(S.daily[S.day]||[]).forEach(x=>got[x.name]=x);let list=workers().filter(x=>String(x.payMethod||x.type||"").includes("วัน")||String(x.type||"").includes("รายวัน"));if(!list.length)list=workers();const past=S.day<today();return `<section class="pwa-workshop-panel pwa-att-wrap">${dayControls()}<p class="pwa-att-help">💡 <b>หมายเหตุ:</b><br>ระบบเชื่อมกับการสแกน QR Code ของช่างอัตโนมัติ<br>✅ ช่างสแกน QR แล้ว จะแสดงสถานะอัตโนมัติที่หน้านี้<br>✍️ กรณีช่างไม่สะดวกสแกน ให้กดสถานะที่หน้านี้แทนได้</p><div class="pwa-attendance-list">${list.map(x=>attendanceCard(x,got[x.name]||{})).join("")}</div><label class="pwa-workshop-reason">${past?"เหตุผลที่แก้ไขย้อนหลัง":"เหตุผลการแก้ไข / บันทึก OT"}<input id="reason" maxlength="200" placeholder="เช่น ช่างลืมลงเวลา หรืออนุมัติ OT งานเร่งด่วน"></label><button data-a="saveDay" class="pwa-workshop-save" ${S.saving?"disabled":""}>${S.saving?"⏳ กำลังบันทึก...":past?"💾 บันทึกแก้ไขย้อนหลัง":"💾 บันทึกวันทำงาน"}</button></section>`;}
function attendanceCard(x,r){let present=String(r.present||"")==="มา",factor=Number(r.dayFactor)===.5?.5:1,disabled=present?"":"disabled";return `<article class="pwa-att-card" data-name="${e(x.name)}" data-type="${e(x.type||"")}" data-rate="${Number(r.rate??x.rate??0)}" data-present="${present}"><header><div><strong>${e(x.name)}</strong><small>${e(x.type||"")}</small></div><b>฿${m(r.rate??x.rate??0)}/วัน</b></header><div class="pwa-att-edit-grid"><div class="pwa-att-edit-field"><span>สถานะ</span><button type="button" data-a="present" class="pwa-att-status ${present?"present":""}">${present?"✅ มา":"❌ ไม่มา"}</button></div><label class="pwa-att-edit-field">เข้า<input data-k="in" type="time" value="${e(r.timeIn||"")}" ${disabled}></label><label class="pwa-att-edit-field">ออก<input data-k="out" type="time" value="${e(r.timeOut||"")}" ${disabled}></label><label class="pwa-att-edit-field">ประเภทวันทำงาน<select data-k="factor" ${disabled}><option value="1" ${factor===1?"selected":""}>เต็มวัน (100%)</option><option value="0.5" ${factor===.5?"selected":""}>ครึ่งวัน (50%)</option></select></label><label class="pwa-att-edit-field">OT ที่อนุมัติ (ชม.)<input data-k="ot" type="number" inputmode="decimal" min="0" step="0.5" value="${Number(r.otHours)||0}" ${disabled}></label><label class="pwa-att-edit-field">เริ่ม OT<input data-k="otStart" type="time" value="${e(r.otStart||"")}" ${disabled}></label><label class="pwa-att-edit-field">สิ้นสุด OT<input data-k="otEnd" type="time" value="${e(r.otEnd||"")}" ${disabled}></label></div><label class="pwa-att-note">หมายเหตุ<input data-k="note" maxlength="200" value="${e(r.note||"")}" ${disabled}></label></article>`;}
function monthName(key){let [y,mo]=key.split("-").map(Number);return new Date(y,mo-1,1).toLocaleDateString("th-TH",{month:"long",year:"numeric"});}
function monthly(){let key=S.monthKey||S.day.slice(0,7),rows=S.months[key]||[],[year,month]=key.split("-").map(Number),days=new Date(year,month,0).getDate(),map={};rows.forEach(x=>{(map[x.name]??={rate:x.rate||0,days:{},count:0}).days[Number(x.date)]=x;map[x.name].count++;});let names=Object.keys(map),total=names.reduce((sum,n)=>sum+map[n].count*Number(map[n].rate||0),0);return `<section class="pwa-workshop-panel pwa-att-wrap"><div style="display:flex;gap:6px;max-width:500px;margin:0 auto 12px"><button data-a="daily" class="pwa-mode">📅 รายวัน</button><button data-a="monthly" class="pwa-mode active">📆 รายเดือน</button></div><div class="pwa-date-nav"><button data-a="prevMonth">◀</button><div>${monthName(key)}</div><button data-a="nextMonth">▶</button></div>${rows.length?`<table class="pwa-sum-table"><tr><th>ช่าง</th><th>วัน</th><th>อัตรา/วัน</th><th>รวม</th></tr>${names.map(n=>`<tr><td>${e(n)}</td><td class="right">${map[n].count}</td><td class="right">฿${m(map[n].rate)}</td><td class="right">฿${m(map[n].count*map[n].rate)}</td></tr>`).join("")}<tr><td>รวม</td><td></td><td></td><td class="right">฿${m(total)}</td></tr></table><div class="pwa-att-legend"><span>✅ มาทำงาน</span><span>○ ไม่มีข้อมูล</span><span>▧ วันหยุด</span></div><div class="pwa-att-matrix"><table><tr><th>ช่าง</th>${Array.from({length:days},(_,i)=>`<th class="${[0,6].includes(new Date(year,month-1,i+1).getDay())?"weekend":""}">${i+1}</th>`).join("")}<th>รวม</th></tr>${names.map(n=>`<tr><td>${e(n)}</td>${Array.from({length:days},(_,i)=>`<td class="${[0,6].includes(new Date(year,month-1,i+1).getDay())?"weekend":""}"><i class="${map[n].days[i+1]?"present":"absent"}">${map[n].days[i+1]?"✓":""}</i></td>`).join("")}<td class="sum">${map[n].count}</td></tr>`).join("")}</table></div>`:'<p class="pwa-workshop-empty">ไม่มีข้อมูลเดือนนี้</p>'}</section>`;}
function periods(mode){let now=new Date(),o=[];for(let i=0;i<6;i++){let y=now.getFullYear(),mo=now.getMonth()-i,d=new Date(y,mo,1),end=new Date(y,mo+1,0);if(mode==="half"){o.push([date(d),date(new Date(d.getFullYear(),d.getMonth(),15)),`งวด 1-15 ${d.toLocaleDateString("th-TH",{month:"short",year:"numeric"})}`]);o.push([date(new Date(d.getFullYear(),d.getMonth(),16)),date(end),`งวด 16-${end.getDate()} ${d.toLocaleDateString("th-TH",{month:"short",year:"numeric"})}`]);}else o.push([date(d),date(end),d.toLocaleDateString("th-TH",{month:"long",year:"numeric"})]);}return o;}
function wage(){let ps=periods(S.wageMode),key=S.wageKey||`${ps[0][0]}|${ps[0][1]}`,data=S.wages[key],mode=S.wageMode;return `<section class="pwa-workshop-panel pwa-wage-wrap"><div class="pwa-wage-modes"><button data-a="half" class="${mode==="half"?"active":""}">📅 15 วัน</button><button data-a="full" class="${mode==="full"?"active":""}">📆 รายเดือน</button><button data-a="person" class="${mode==="person"?"active":""}">👤 รายคน</button></div><select id="wagePeriod">${ps.map(p=>`<option value="${p[0]}|${p[1]}" ${key===`${p[0]}|${p[1]}`?"selected":""}>${p[2]}</option>`).join("")}</select><div class="pwa-wage-view"><button data-a="table" class="${S.wageView==="table"?"active":""}">📋 ตาราง</button><button data-a="chart" class="${S.wageView==="chart"?"active":""}">📊 กราฟ</button></div>${!data?'<p class="pwa-workshop-empty">⏳ กำลังโหลด...</p>':S.wageView==="chart"?wageChart(data):wageTables(data)}</section>`;}
function wageTables(d){let p=d.pieceWork||[],day=d.dailyWork||[],pc=p.reduce((s,x)=>s+Number(x.completedTotal||0),0),pp=p.reduce((s,x)=>s+Number(x.pendingTotal||0),0),dt=day.reduce((s,x)=>s+Number(x.total||0),0);return `${p.length?`<h3>🖌️ ค่าจ้างรายชิ้นและงานค้างในมือ</h3><p class="pwa-table-note">ยอดรับรู้ใช้วันที่รับงานในงวดที่เลือก ส่วนงานค้างคือรายการที่ยังรอรับคืน</p><table class="pwa-sum-table"><tr><th>ช่าง</th><th class="right">รับรู้แล้ว</th><th class="right">งานค้าง</th><th class="right">รวมคาดการณ์</th></tr>${p.map(x=>`<tr><td>${e(x.name)}<small>เสร็จ ${m(x.jobs)} งาน · ค้าง ${m(x.pendingJobs)} งาน</small></td><td class="right">฿${m(x.completedTotal)}</td><td class="right warn">฿${m(x.pendingTotal)}</td><td class="right strong">฿${m(x.expectedTotal)}</td></tr>`).join("")}<tr><td>รวม</td><td class="right">฿${m(pc)}</td><td class="right">฿${m(pp)}</td><td class="right">฿${m(pc+pp)}</td></tr></table>`:""}${day.length?`<h3>📅 ค่าแรงรายวัน</h3><table class="pwa-sum-table"><tr><th>ช่าง</th><th class="right">วัน</th><th class="right">ค่าแรง</th></tr>${day.map(x=>`<tr><td>${e(x.name)}</td><td class="right">${m(x.days)}</td><td class="right">฿${m(x.total)}</td></tr>`).join("")}<tr><td>รวม</td><td></td><td class="right">฿${m(dt)}</td></tr></table>`:""}${pc+dt?`<div class="pwa-wage-recognized">ยอดค่าแรงที่รับรู้ในงวด: ฿${m(pc+dt)}</div>`:""}${pp?`<div class="pwa-wage-pending">งานค้างในมือ: ฿${m(pp)}<small>ยังไม่นับเป็นยอดจ่ายค่าจ้างของงวด</small></div>`:""}${!p.length&&!day.length?'<p class="pwa-workshop-empty">ไม่มีข้อมูลในงวดนี้</p>':""}`;}
function wageChart(d){let p=d.pieceWork||[],max=Math.max(1,...p.map(x=>Number(x.expectedTotal||0)));return p.length?`<div class="pwa-wage-chart"><h3>📊 ภาพรวมค่าจ้างและงานในมือ</h3><p>ยอดรับรู้แล้ว และมูลค่างานที่ยังอยู่ในมือ</p>${p.map(x=>`<article><div><b>${e(x.name)}</b><strong>฿${m(x.expectedTotal)}</strong></div><i><em style="width:${100*Number(x.completedTotal||0)/max}%"></em><u style="width:${100*Number(x.pendingTotal||0)/max}%"></u></i><small>รับรู้ ฿${m(x.completedTotal)} · ค้าง ฿${m(x.pendingTotal)}</small></article>`).join("")}</div>`:'<p class="pwa-workshop-empty">ไม่มีข้อมูลค่าจ้างรายชิ้นในงวดนี้</p>';}
function picker(){if(!S.pick)return "";let q=S.pickQ.toLowerCase(),all=(S.data?.whitewares||[]).filter(x=>[x.sku,x.name,x.product,x.size,x.pattern].join(" ").toLowerCase().includes(q));return `<div class="pwa-workshop-modal"><section class="pwa-workshop-dialog"><header><b>⚪ เลือกของขาว</b><button data-a="close">×</button></header><input id="searchPick" placeholder="ค้นหาชื่อหรือรหัสสินค้า" value="${e(S.pickQ)}"><div>${all.map(x=>`<button data-a="choose" data-i="${(S.data.whitewares||[]).indexOf(x)}"><strong>${e(product(x))}</strong><small>${e(x.sku||"")} · คงเหลือ ${m(x.balance)} ชิ้น</small></button>`).join("")||'<p class="pwa-workshop-empty">ไม่พบสินค้า</p>'}</div></section></div>`;}
function page(){let body={assign,receive,firing,daily,monthly,wage}[S.tab]();return `<section class="pwa-workshop-page">${top()}<main>${tabs()}${body}</main>${picker()}</section>`;}
function render(root){root.innerHTML=page();bind(root);}
function updateJobTotal(root){const qty=Number(root.querySelector("#qty")?.value)||0,price=Number(root.querySelector("#price")?.value)||0,stickers=S.step==="วนทอง"?0:(Number(root.querySelector("#stickerQty")?.value)||0)*(Number(root.querySelector("#stickerRate")?.value)||0);const out=root.querySelector("#jobTotal");if(out)out.textContent=`฿${m(qty*price+stickers)}`;}
function bind(root){root.onclick=ev=>click(root,ev);root.querySelector("#wsForm")?.addEventListener("submit",ev=>saveJob(root,ev));root.querySelector("#wsForm")?.addEventListener("input",()=>updateJobTotal(root));root.querySelector("#dayPick")?.addEventListener("change",ev=>setDay(root,ev.target.value));root.querySelector("#wagePeriod")?.addEventListener("change",ev=>{S.wageKey=ev.target.value;render(root);loadWage(root);});root.querySelector("#searchPick")?.addEventListener("input",ev=>{S.pickQ=ev.target.value;render(root);root.querySelector("#searchPick")?.focus();});}
function click(root,ev){let b=ev.target.closest("button");if(!b)return;if(b.dataset.tab){S.tab=b.dataset.tab;render(root);if(S.tab==="daily")loadDay(root);if(S.tab==="wage")loadWage(root);return;}if(b.dataset.step){S.step=b.dataset.step;S.chosen=null;render(root);return;}let a=b.dataset.a;if(a==="back")return S.back();if(a==="pick"){S.pick=true;S.pickQ="";render(root);setTimeout(()=>root.querySelector("#searchPick")?.focus(),0);return;}if(a==="close"){S.pick=false;render(root);return;}if(a==="choose"){S.chosen=S.data.whitewares[Number(b.dataset.i)];S.pick=false;render(root);return;}if(a==="present"){const card=b.closest(".pwa-att-card"),present=card.dataset.present!=="true";card.dataset.present=String(present);b.classList.toggle("present",present);b.textContent=present?"✅ มา":"❌ ไม่มา";card.querySelectorAll("input,select").forEach(x=>x.disabled=!present);return;}if(a==="refresh")return load(root);if(a==="fire")return fire(root,b.closest("article"));if(a==="prev")return setDay(root,date(new Date(`${S.day}T00:00`).getTime()-864e5));if(a==="next")return setDay(root,date(new Date(`${S.day}T00:00`).getTime()+864e5));if(a==="daily"){S.tab="daily";render(root);return loadDay(root);}if(a==="monthly"){S.tab="monthly";S.monthKey=S.day.slice(0,7);render(root);return loadMonth(root,S.monthKey);}if(a==="prevMonth"||a==="nextMonth"){let d=new Date(`${S.monthKey}-01T00:00`);d.setMonth(d.getMonth()+(a==="nextMonth"?1:-1));S.monthKey=date(d).slice(0,7);render(root);return loadMonth(root,S.monthKey);}if(a==="saveDay")return saveDay(root);if(["half","full","person"].includes(a)){S.wageMode=a;S.wageKey="";render(root);return loadWage(root);}if(["table","chart"].includes(a)){S.wageView=a;render(root);return;} }
async function load(root){try{let r=await S.api.workshopBootstrap(S.token);if(!r.ok)throw Error(r.message||r.error);S.data=r.result||{};render(root);}catch(x){S.toast(`เปิดหน้าจัดการงานช่างไม่สำเร็จ: ${x.message||x}`);}}
async function saveJob(root,ev){ev.preventDefault();const isGold=S.step==="วนทอง";if(!isGold&&!S.chosen)return S.toast("กรุณาเลือกของขาว");let v=id=>root.querySelector(id)?.value||"",d=isGold?{worker:v("#worker"),step:"วนทอง",whitewareSku:"",product:"วนทอง",size:"",pattern:"",sku:"",refRow:"",autoComplete:true,qty:Number(v("#qty")),priceEach:Number(v("#price")),stickerQty:0,stickerRate:0,jobDate:v("#jobDate"),dueDate:""}:{worker:v("#worker"),step:"เขียนลาย",whitewareSku:S.chosen.sku,product:S.chosen.name||S.chosen.product,size:S.chosen.size||"",pattern:S.chosen.pattern||"",sku:S.chosen.sku,qty:Number(v("#qty")),priceEach:Number(v("#price")),stickerQty:Number(v("#stickerQty")),stickerRate:Number(v("#stickerRate")),jobDate:v("#jobDate"),dueDate:v("#dueDate")};if(!d.worker)return S.toast("กรุณาเลือกช่าง");if(!Number.isInteger(d.qty)||d.qty<=0)return S.toast(isGold?"กรุณาใส่จำนวนครั้งเป็นจำนวนเต็ม":"กรุณาใส่จำนวนเป็นจำนวนเต็ม");if(!Number.isFinite(d.priceEach)||d.priceEach<=0)return S.toast("กรุณาระบุค่าจ้างที่มากกว่า 0");if(!d.jobDate)return S.toast("กรุณาเลือกวันที่จ่ายงาน");S.saving=true;render(root);try{let r=await S.api.workshopSaveJob(S.token,d),o=r.result;if(!r.ok||!o?.success)throw Error(o?.message||r.message);S.toast(o.message||"บันทึกสำเร็จ");S.chosen=null;await load(root);}catch(x){S.toast(`❌ ${x.message||x}`)}finally{S.saving=false;render(root);}}
async function fire(root,row){let pass=Number(row.querySelector('[data-k="pass"]')?.value),bad=Number(row.querySelector('[data-k="damaged"]')?.value),qty=Number(row.dataset.qty);if(!Number.isInteger(pass)||!Number.isInteger(bad)||pass<0||bad<0||pass+bad!==qty)return S.toast(`จำนวนผ่าน + เสีย ต้องเท่ากับ ${m(qty)}`);try{let r=await S.api.workshopConfirmFiring(S.token,Number(row.dataset.row),pass,bad),o=r.result;if(!r.ok||!o?.success)throw Error(o?.message||r.message);S.toast(o.message||"บันทึกสำเร็จ");load(root)}catch(x){S.toast(`❌ ${x.message||x}`)}}
async function setDay(root,d){if(!d||d>today())return;S.day=d;render(root);loadDay(root)}async function loadDay(root){if(S.daily[S.day])return;try{let r=await S.api.workshopAttendance(S.token,S.day);if(!r.ok)throw Error(r.message);S.daily[S.day]=r.result||[];if(S.tab==="daily")render(root)}catch(x){S.toast(`โหลดลงเวลาไม่สำเร็จ: ${x.message||x}`)}}
async function loadMonth(root,key){if(S.months[key])return;let [y,mo]=key.split("-").map(Number);try{let r=await S.api.workshopMonthlyAttendance(S.token,y,mo);if(!r.ok)throw Error(r.message);S.months[key]=r.result||[];if(S.tab==="monthly")render(root)}catch(x){S.toast(`โหลดปฏิทินไม่สำเร็จ: ${x.message||x}`)}}
async function saveDay(root){let reason=root.querySelector("#reason")?.value.trim()||"";if(S.day<today()&&!reason)return S.toast("กรุณาระบุเหตุผลการแก้ไขย้อนหลัง");let items=[...root.querySelectorAll(".pwa-att-card")].map(c=>({name:c.dataset.name,type:c.dataset.type,rate:Number(c.dataset.rate)||0,present:c.dataset.present==="true",timeIn:c.querySelector('[data-k="in"]')?.value||"",timeOut:c.querySelector('[data-k="out"]')?.value||"",dayFactor:Number(c.querySelector('[data-k="factor"]')?.value)||1,otHours:Number(c.querySelector('[data-k="ot"]')?.value)||0,otStart:c.querySelector('[data-k="otStart"]')?.value||"",otEnd:c.querySelector('[data-k="otEnd"]')?.value||"",otReason:reason,note:c.querySelector('[data-k="note"]')?.value||""}));for(let x of items){if(x.timeIn&&x.timeOut&&x.timeOut<x.timeIn)return S.toast(`เวลาออกของ ${x.name} ต้องไม่ก่อนเวลาเข้า`);if(x.otHours>0&&!x.present)return S.toast(`ไม่สามารถบันทึก OT ให้ ${x.name} ที่ไม่มาทำงานได้`)}S.saving=true;render(root);try{let r=await S.api.workshopSaveAttendance(S.token,{targetDate:S.day,items,reason}),o=r.result;if(!r.ok||!o?.success)throw Error(o?.message||r.message);delete S.daily[S.day];S.wages={};S.toast(o.message||"บันทึกสำเร็จ");loadDay(root)}catch(x){S.toast(`❌ ${x.message||x}`)}finally{S.saving=false;render(root)}}
async function loadWage(root){let ps=periods(S.wageMode),key=S.wageKey||`${ps[0][0]}|${ps[0][1]}`;S.wageKey=key;if(S.wages[key])return;let [a,b]=key.split("|");try{let r=await S.api.workshopWageSummary(S.token,a,b);if(!r.ok)throw Error(r.message);S.wages[key]=r.result||{};if(S.tab==="wage")render(root)}catch(x){S.toast(`โหลดสรุปค่าแรงไม่สำเร็จ: ${x.message||x}`)}}
export function renderWorkshop(root,api,token,onBack,context={}){S.api=api;S.token=token;S.back=onBack;S.toast=context.toast||(()=>{});if(!S.day)S.day=today();if(S.step!=="วนทอง")S.step="เขียนลาย";render(root);if(!S.data)load(root);}
