// UI adapter only.  08_Workshop.gs remains the source of truth for all wages,
// attendance, stock deduction and LockService-protected mutations.
const S={api:null,token:"",back:null,toast:()=>{},data:null,tab:"assign",step:"เขียนลายน้ำทอง",pick:false,pickQ:"",chosen:null,day:"",daily:{},months:{},wages:{},handoff:null,handoffConfirm:null,handoffSaving:false,wageMode:"half",wageView:"table",wageKey:"",periodOpen:false,saving:false,wageConfirm:false,wageConfirming:false,wageEdit:null,wageEditSaving:false,wagePrint:false};
const e=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const m=v=>(Number(v)||0).toLocaleString("th-TH");
const date=v=>{const x=v instanceof Date?v:(v?new Date(v):new Date());return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`;};
const today=()=>date(); const product=x=>[x?.name||x?.product,x?.size,x?.pattern].filter(Boolean).join(" · ");
const workers=()=>S.data?.employees||[];
function top(){return `<header class="pwa-workshop-topbar"><button data-a="back" type="button">← กลับ</button><div>🖌️ จัดการงานช่าง</div></header>`;}
function tabs(){return `<nav class="pwa-workshop-tabs">${[["assign","🖌️ จ่ายงานช่างเขียน"],["receive","📦 ช่างส่งงาน"],["firing","🔥 คิวเผา"],["daily","📅 ลงเวลาช่างรายวัน"],["wage","💰 สรุป/ค่าจ้าง"]].map(x=>`<button data-tab="${x[0]}" class="${S.tab===x[0]?"active":""}">${x[1]}</button>`).join("")}</nav>`;}
function assign(){
  const isGold=S.step==="วนทอง",q=S.chosen,rate=Number(S.data?.goldCycleRate)||180;
  return `<section class="pwa-workshop-panel pwa-job-form">
    <div class="pwa-workshop-step">
      <button data-step="เขียนลาย" class="${!isGold?"active":""}">🖌️ เขียนลาย</button>
      <button data-step="วนทอง" class="${isGold?"active":""}">🔥 วนทอง</button>
    </div>
    <form id="wsForm">
      <label>👤 ช่าง<select id="worker"><option value="">-- เลือกช่าง --</option>${workers().map(x=>`<option value="${e(x.name)}">${e(x.name)}${x.type?` (${e(x.type)})`:""}</option>`).join("")}</select></label>
      ${!isGold?`<label id="whitewareGroup">⚪ ของขาวที่จ่าย (หักสต๊อก)<button type="button" data-a="pick" class="pwa-workshop-picker ${q?"selected":""}">${q?e(product(q)):"🔍 กดเพื่อค้นหาและเลือกของขาว"}<b aria-hidden="true">›</b></button></label>`:""}
      <p class="pwa-auto-info">${isGold?"วนทอง — คิดค่าแรงตามจำนวนครั้งเผา":"เลือกของขาวเพื่อให้ระบบค้นหาค่าจ้างอัตโนมัติ"}</p>
      <div class="pwa-job-rate-row">
        <label>${isGold?"🔥 จำนวนครั้ง (เผาวนทอง)":"📦 จำนวน"}<input id="qty" type="number" inputmode="numeric" min="1" value="1"></label>
        <label>${isGold?"💰 ค่าแรง/ครั้ง":"💰 ค่าจ้าง/ชิ้น"} ${isGold?'<span class="pwa-auto-badge">auto</span>':""}<input id="price" type="number" inputmode="decimal" min="0" value="${isGold?rate:""}"></label>
        <div class="pwa-total-box"><span>รวมค่าแรง</span><b id="jobTotal">฿${m(isGold?rate:0)}</b></div>
      </div>
      ${!isGold?`<div class="pwa-workshop-grid pwa-sticker-row"><label>🏷️ จำนวนติดสติกเกอร์<input id="stickerQty" type="number" inputmode="numeric" min="0" value="0"></label><label>💰 ค่าติดสติกเกอร์/ชิ้น<input id="stickerRate" type="number" inputmode="decimal" min="0" value="5"></label></div>`:""}
      <div class="pwa-workshop-grid"><label>📅 วันที่จ่ายงาน<input id="jobDate" type="date" value="${today()}" max="${today()}"></label>${!isGold?`<label>📅 กำหนดส่ง<input id="dueDate" type="date" value="${date(Date.now()+259200000)}"></label>`:""}</div>
      <p class="pwa-workshop-note">${isGold?"ระบบจะบันทึกงานวนทองเป็นงานเสร็จทันที ตามหลักการเดิมของ GAS":"ตรวจจำนวนของขาวและตัดสต๊อกด้วยระบบ GAS เดิมก่อนบันทึก"}</p>
      <button class="pwa-workshop-save" ${S.saving?"disabled":""}>${S.saving?"⏳ กำลังบันทึก...":"💾 บันทึกจ่ายงาน"}</button>
    </form>
  </section>`;
}
function receive(){const d=S.handoff,cards=d?.cards||[];return `<section class="pwa-workshop-panel pwa-handoff-wrap"><div class="pwa-workshop-title"><h2>📥 งานจาก App ช่าง</h2><button data-a="handoffRefresh">🔄 รีเฟรช</button></div><p class="pwa-handoff-note">ยืนยันแต่ละรอบส่งงานโดยเลือก SKU สินค้าหลังเผา; งานเขียนลายต้องเลือกของขาว ระบบจะใช้ flow เดิมเพื่อตัดของขาว สร้าง WJOB และเข้าคิวเผา</p>${!d?'<p class="pwa-workshop-empty">⏳ กำลังโหลด...</p>':cards.length?`<div class="pwa-handoff-list">${cards.map(x=>{const legacy=!!x.sourceId,subs=x.submissions||[];return `<article class="pwa-handoff-card ${legacy?"legacy":"new"}"><header><div><strong>${e(x.worker||"ไม่ระบุช่าง")}</strong><small>${e(x.role||"-")}</small></div><span>${legacy?"นำเข้าจาก App เดิม":"App ช่างใหม่"}</span></header><div class="pwa-handoff-item"><b>${e(x.product||"ไม่ระบุสินค้า")}</b>${x.pattern?` · ${e(x.pattern)}`:""}</div><div class="pwa-handoff-meta">จำนวน ${m(x.qty)} ชิ้น · ค่าแรง ฿${m(x.priceEach)}/ชิ้น${Number(x.stickerQty)>0?` · สติกเกอร์ ${m(x.stickerQty)} ชิ้น`:""}</div>${subs.length?subs.map(sub=>`<div class="pwa-handoff-sub">ส่ง ${e(sub.date||"-")} · ${m(sub.qty)} ชิ้น · ${e(sub.status||"รอตรวจ")}${sub.photoUrl?`<a href="${e(sub.photoUrl)}" target="_blank" rel="noopener"><img src="${e(sub.photoUrl)}" alt="รูปผลงานช่าง"></a>`:""}${sub.status==="รอตรวจ"?`<button data-a="handoffConfirm" data-job="${e(x.id)}" data-sub="${e(sub.id)}">✅ ตรวจและเข้าคิวเผา</button>`:sub.link?.mainJobId?`<small>เชื่อม ${e(sub.link.mainJobId)}</small>`:""}</div>`).join(""):'<div class="pwa-handoff-sub">ช่างยังไม่ได้ส่งงาน</div>'}</article>`;}).join("")}</div>`:'<p class="pwa-workshop-empty">ยังไม่มีงานจาก App ช่าง</p>'}${handoffDialog()}`;}
function handoffDialog(){const c=S.handoffConfirm;if(!c)return "";const d=S.handoff||{},card=(d.cards||[]).find(x=>x.id===c.jobId)||{},writer=String(card.role||"").includes("เขียนลาย"),products=d.products||[],whitewares=d.whitewares||[];return `<div class="pwa-workshop-modal" role="dialog" aria-modal="true"><section class="pwa-workshop-dialog"><button class="pwa-dialog-x" data-a="closeHandoff" aria-label="ปิด">×</button><h2>✅ ยืนยันเข้าคิวเผา</h2><p><b>${e(card.worker||"")}</b> · ${e(card.role||"")} · ส่ง ${m(c.qty)} ชิ้น</p>${writer?`<label>ของขาวที่ตัดสต๊อก<select id="handoffWhiteware"><option value="">-- เลือกของขาว --</option>${whitewares.map(x=>`<option value="${e(x.sku)}">${e(x.sku)} · ${e(x.name)} (เหลือ ${m(x.balance)})</option>`).join("")}</select></label>`:""}<label>SKU สินค้าหลังเผา<select id="handoffFinished"><option value="">-- เลือกสินค้า --</option>${products.map(x=>`<option value="${e(x.code)}">${e(x.code)} · ${e(product(x))}</option>`).join("")}</select></label><label>ค่าจ้าง/หน่วย<input id="handoffPrice" type="number" inputmode="decimal" min="0" value="${Number(card.priceEach)||0}"></label><p class="pwa-handoff-note">ระบบจะส่งจำนวนดีทั้งหมดเข้าคิวเผาโดยตรง ไม่สร้างงานลงสีต่อ</p><div class="pwa-dialog-actions"><button data-a="closeHandoff">ยกเลิก</button><button data-a="saveHandoff" class="primary" ${S.handoffSaving?"disabled":""}>${S.handoffSaving?"⏳ กำลังยืนยัน...":"✅ ยืนยันเข้าคิวเผา"}</button></div></section></div>`;}
function firingDraft(){let rows=S.data?.firing||[];return `<section class="pwa-workshop-panel"><div class="pwa-workshop-title"><h2>🔥 คิวเผา</h2><button data-a="refresh">🔄 รีเฟรช</button></div><div class="pwa-fire-list">${rows.length?rows.map(x=>`<article data-row="${Number(x.row||x.rowIdx)}" data-qty="${Number(x.qty)}"><div><strong>${e(product(x))}</strong><small>${e(x.sku||"")} · รอเผา ${m(x.qty)} ชิ้น</small></div><label>ผ่าน<input data-k="pass" type="number" min="0" value="${Number(x.qty)}"></label><label>เสีย<input data-k="damaged" type="number" min="0" value="0"></label><button data-a="fire">✅ ยืนยัน</button></article>`).join(""):'<p class="pwa-workshop-empty">ไม่มีงานรอเผา</p>'}</div></section>`;}
function dayControls(){return `<div style="display:flex;gap:6px;max-width:500px;margin:0 auto 12px"><button data-a="daily" class="pwa-mode active">📅 รายวัน</button><button data-a="monthly" class="pwa-mode">📆 รายเดือน</button></div><div class="pwa-date-nav"><button data-a="prev">◀</button><div>${new Date(`${S.day}T00:00:00`).toLocaleDateString("th-TH",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}</div><button data-a="next" ${S.day>=today()?"disabled":""}>▶</button></div><input id="dayPick" type="date" max="${today()}" value="${S.day}" class="pwa-date-picker">`;}
function daily(){let got={};(S.daily[S.day]||[]).forEach(x=>got[x.name]=x);let list=workers().filter(x=>String(x.payMethod||x.type||"").includes("วัน")||String(x.type||"").includes("รายวัน"));if(!list.length)list=workers();const past=S.day<today();return `<section class="pwa-workshop-panel pwa-att-wrap">${dayControls()}<p class="pwa-att-help">💡 <b>หมายเหตุ:</b><br>ระบบเชื่อมกับการสแกน QR Code ของช่างอัตโนมัติ<br>✅ ช่างสแกน QR แล้ว จะแสดงสถานะอัตโนมัติที่หน้านี้<br>✍️ กรณีช่างไม่สะดวกสแกน ให้กดสถานะที่หน้านี้แทนได้</p><div class="pwa-attendance-list">${list.map(x=>attendanceCard(x,got[x.name]||{})).join("")}</div><label class="pwa-workshop-reason">${past?"เหตุผลที่แก้ไขย้อนหลัง":"เหตุผลการแก้ไข / บันทึก OT"}<input id="reason" maxlength="200" placeholder="เช่น ช่างลืมลงเวลา หรืออนุมัติ OT งานเร่งด่วน"></label><button data-a="saveDay" class="pwa-workshop-save" ${S.saving?"disabled":""}>${S.saving?"⏳ กำลังบันทึก...":past?"💾 บันทึกแก้ไขย้อนหลัง":"💾 บันทึกวันทำงาน"}</button></section>`;}
function attendanceCard(x,r){let present=String(r.present||"")==="มา",factor=Number(r.dayFactor)===.5?.5:1,disabled=present?"":"disabled";return `<article class="pwa-att-card" data-name="${e(x.name)}" data-type="${e(x.type||"")}" data-rate="${Number(r.rate??x.rate??0)}" data-present="${present}"><header><div><strong>${e(x.name)}</strong><small>${e(x.type||"")}</small></div><b>฿${m(r.rate??x.rate??0)}/วัน</b></header><div class="pwa-att-edit-grid"><div class="pwa-att-edit-field"><span>สถานะ</span><button type="button" data-a="present" class="pwa-att-status ${present?"present":""}">${present?"✅ มา":"❌ ไม่มา"}</button></div><label class="pwa-att-edit-field">เข้า<input data-k="in" type="time" value="${e(r.timeIn||"")}" ${disabled}></label><label class="pwa-att-edit-field">ออก<input data-k="out" type="time" value="${e(r.timeOut||"")}" ${disabled}></label><label class="pwa-att-edit-field">ประเภทวันทำงาน<select data-k="factor" ${disabled}><option value="1" ${factor===1?"selected":""}>เต็มวัน (100%)</option><option value="0.5" ${factor===.5?"selected":""}>ครึ่งวัน (50%)</option></select></label><label class="pwa-att-edit-field">OT ที่อนุมัติ (ชม.)<input data-k="ot" type="number" inputmode="decimal" min="0" step="0.5" value="${Number(r.otHours)||0}" ${disabled}></label><label class="pwa-att-edit-field">เริ่ม OT<input data-k="otStart" type="time" value="${e(r.otStart||"")}" ${disabled}></label><label class="pwa-att-edit-field">สิ้นสุด OT<input data-k="otEnd" type="time" value="${e(r.otEnd||"")}" ${disabled}></label></div><label class="pwa-att-note">หมายเหตุ<input data-k="note" maxlength="200" value="${e(r.note||"")}" ${disabled}></label></article>`;}
function monthName(key){let [y,mo]=key.split("-").map(Number);return new Date(y,mo-1,1).toLocaleDateString("th-TH",{month:"long",year:"numeric"});}
function monthly(){let key=S.monthKey||S.day.slice(0,7),rows=S.months[key]||[],[year,month]=key.split("-").map(Number),days=new Date(year,month,0).getDate(),map={};rows.forEach(x=>{(map[x.name]??={rate:x.rate||0,days:{},count:0}).days[Number(x.date)]=x;map[x.name].count++;});let names=Object.keys(map),total=names.reduce((sum,n)=>sum+map[n].count*Number(map[n].rate||0),0);return `<section class="pwa-workshop-panel pwa-att-wrap"><div style="display:flex;gap:6px;max-width:500px;margin:0 auto 12px"><button data-a="daily" class="pwa-mode">📅 รายวัน</button><button data-a="monthly" class="pwa-mode active">📆 รายเดือน</button></div><div class="pwa-date-nav"><button data-a="prevMonth">◀</button><div>${monthName(key)}</div><button data-a="nextMonth">▶</button></div>${rows.length?`<table class="pwa-sum-table"><tr><th>ช่าง</th><th>วัน</th><th>อัตรา/วัน</th><th>รวม</th></tr>${names.map(n=>`<tr><td>${e(n)}</td><td class="right">${map[n].count}</td><td class="right">฿${m(map[n].rate)}</td><td class="right">฿${m(map[n].count*map[n].rate)}</td></tr>`).join("")}<tr><td>รวม</td><td></td><td></td><td class="right">฿${m(total)}</td></tr></table><div class="pwa-att-legend"><span>✅ มาทำงาน</span><span>○ ไม่มีข้อมูล</span><span>▧ วันหยุด</span></div><div class="pwa-att-matrix"><table><tr><th>ช่าง</th>${Array.from({length:days},(_,i)=>`<th class="${[0,6].includes(new Date(year,month-1,i+1).getDay())?"weekend":""}">${i+1}</th>`).join("")}<th>รวม</th></tr>${names.map(n=>`<tr><td>${e(n)}</td>${Array.from({length:days},(_,i)=>`<td class="${[0,6].includes(new Date(year,month-1,i+1).getDay())?"weekend":""}"><i class="${map[n].days[i+1]?"present":"absent"}">${map[n].days[i+1]?"✓":""}</i></td>`).join("")}<td class="sum">${map[n].count}</td></tr>`).join("")}</table></div>`:'<p class="pwa-workshop-empty">ไม่มีข้อมูลเดือนนี้</p>'}</section>`;}
function periods(mode){const now=new Date(),o=[];if(mode==="half"){let cursor=new Date(now.getFullYear(),now.getMonth(),now.getDate()>15?16:1);for(let i=0;i<6;i++){const startDay=cursor.getDate()===16?16:1,endDay=startDay===1?15:new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate(),start=new Date(cursor.getFullYear(),cursor.getMonth(),startDay),end=new Date(cursor.getFullYear(),cursor.getMonth(),endDay);o.push([date(start),date(end),`งวด ${startDay}-${endDay} ${cursor.toLocaleDateString("th-TH",{month:"short",year:"numeric"})}`]);cursor=startDay===16?new Date(cursor.getFullYear(),cursor.getMonth(),1):new Date(cursor.getFullYear(),cursor.getMonth()-1,16);}return o;}for(let i=0;i<6;i++){const d=new Date(now.getFullYear(),now.getMonth()-i,1),end=new Date(d.getFullYear(),d.getMonth()+1,0);o.push([date(d),date(end),d.toLocaleDateString("th-TH",{month:"long",year:"numeric"})]);}return o;}
function wageDraft(){let ps=periods(S.wageMode),key=S.wageKey||`${ps[0][0]}|${ps[0][1]}`,data=S.wages[key],mode=S.wageMode;return `<section class="pwa-workshop-panel pwa-wage-wrap"><div class="pwa-wage-modes"><button data-a="half" class="${mode==="half"?"active":""}">📅 15 วัน</button><button data-a="full" class="${mode==="full"?"active":""}">📆 รายเดือน</button><button data-a="person" class="${mode==="person"?"active":""}">👤 รายคน</button></div><select id="wagePeriod">${ps.map(p=>`<option value="${p[0]}|${p[1]}" ${key===`${p[0]}|${p[1]}`?"selected":""}>${p[2]}</option>`).join("")}</select><div class="pwa-wage-view"><button data-a="table" class="${S.wageView==="table"?"active":""}">📋 ตาราง</button><button data-a="chart" class="${S.wageView==="chart"?"active":""}">📊 กราฟ</button></div>${!data?'<p class="pwa-workshop-empty">⏳ กำลังโหลด...</p>':S.wageView==="chart"?wageChart(data):wageTables(data)}</section>`;}
function wageTables(d){let p=d.pieceWork||[],day=d.dailyWork||[],pc=p.reduce((s,x)=>s+Number(x.completedTotal||0),0),pp=p.reduce((s,x)=>s+Number(x.pendingTotal||0),0),dt=day.reduce((s,x)=>s+Number(x.total||0),0);return `${p.length?`<h3>🖌️ ค่าจ้างรายชิ้นและงานค้างในมือ</h3><p class="pwa-table-note">ยอดรับรู้ใช้วันที่รับงานในงวดที่เลือก ส่วนงานค้างคือรายการที่ยังรอรับคืน</p><table class="pwa-sum-table"><tr><th>ช่าง</th><th class="right">รับรู้แล้ว</th><th class="right">งานค้าง</th><th class="right">รวมคาดการณ์</th></tr>${p.map(x=>`<tr><td>${e(x.name)}<small>เสร็จ ${m(x.jobs)} งาน · ค้าง ${m(x.pendingJobs)} งาน</small></td><td class="right">฿${m(x.completedTotal)}</td><td class="right warn">฿${m(x.pendingTotal)}</td><td class="right strong">฿${m(x.expectedTotal)}</td></tr>`).join("")}<tr><td>รวม</td><td class="right">฿${m(pc)}</td><td class="right">฿${m(pp)}</td><td class="right">฿${m(pc+pp)}</td></tr></table>`:""}${day.length?`<h3>📅 ค่าแรงรายวัน</h3><table class="pwa-sum-table"><tr><th>ช่าง</th><th class="right">วัน</th><th class="right">ค่าแรง</th></tr>${day.map(x=>`<tr><td>${e(x.name)}</td><td class="right">${m(x.days)}</td><td class="right">฿${m(x.total)}</td></tr>`).join("")}<tr><td>รวม</td><td></td><td class="right">฿${m(dt)}</td></tr></table>`:""}${pc+dt?`<div class="pwa-wage-recognized">ยอดค่าแรงที่รับรู้ในงวด: ฿${m(pc+dt)}</div>`:""}${pp?`<div class="pwa-wage-pending">งานค้างในมือ: ฿${m(pp)}<small>ยังไม่นับเป็นยอดจ่ายค่าจ้างของงวด</small></div>`:""}${!p.length&&!day.length?'<p class="pwa-workshop-empty">ไม่มีข้อมูลในงวดนี้</p>':""}`;}
function wageChart(d){let p=d.pieceWork||[],max=Math.max(1,...p.map(x=>Number(x.expectedTotal||0)));return p.length?`<div class="pwa-wage-chart"><h3>📊 ภาพรวมค่าจ้างและงานในมือ</h3><p>ยอดรับรู้แล้ว และมูลค่างานที่ยังอยู่ในมือ</p>${p.map(x=>`<article><div><b>${e(x.name)}</b><strong>฿${m(x.expectedTotal)}</strong></div><i><em style="width:${100*Number(x.completedTotal||0)/max}%"></em><u style="width:${100*Number(x.pendingTotal||0)/max}%"></u></i><small>รับรู้ ฿${m(x.completedTotal)} · ค้าง ฿${m(x.pendingTotal)}</small></article>`).join("")}</div>`:'<p class="pwa-workshop-empty">ไม่มีข้อมูลค่าจ้างรายชิ้นในงวดนี้</p>';}
function picker(){if(!S.pick)return "";let q=S.pickQ.toLowerCase(),all=(S.data?.whitewares||[]).filter(x=>[x.sku,x.name,x.product,x.size,x.pattern].join(" ").toLowerCase().includes(q));return `<div class="pwa-workshop-modal"><section class="pwa-workshop-dialog"><header><b>⚪ เลือกของขาว</b><button data-a="close">×</button></header><input id="searchPick" placeholder="ค้นหาชื่อหรือรหัสสินค้า" value="${e(S.pickQ)}"><div>${all.map(x=>`<button data-a="choose" data-i="${(S.data.whitewares||[]).indexOf(x)}"><strong>${e(product(x))}</strong><small>${e(x.sku||"")} · คงเหลือ ${m(x.balance)} ชิ้น</small></button>`).join("")||'<p class="pwa-workshop-empty">ไม่พบสินค้า</p>'}</div></section></div>`;}
function page(){let body={assign,receive,firing,daily,monthly,wage}[S.tab]();return `<section class="pwa-workshop-page">${top()}<main>${tabs()}${body}</main>${picker()}${wageConfirmDialog()}${closedWageDialog()}${wagePrintDialog()}</section>`;}
function render(root){root.innerHTML=page();bind(root);if(S.tab==="receive"&&!S.handoff)setTimeout(()=>loadHandoff(root),0);}
function updateJobTotal(root){const qty=Number(root.querySelector("#qty")?.value)||0,price=Number(root.querySelector("#price")?.value)||0,stickers=S.step==="วนทอง"?0:(Number(root.querySelector("#stickerQty")?.value)||0)*(Number(root.querySelector("#stickerRate")?.value)||0);const out=root.querySelector("#jobTotal");if(out)out.textContent=`฿${m(qty*price+stickers)}`;}
function bindDraft(root){root.onclick=ev=>click(root,ev);root.querySelector("#wsForm")?.addEventListener("submit",ev=>saveJob(root,ev));root.querySelector("#wsForm")?.addEventListener("input",()=>updateJobTotal(root));root.querySelector("#dayPick")?.addEventListener("change",ev=>setDay(root,ev.target.value));root.querySelector("#wagePeriod")?.addEventListener("change",ev=>{S.wageKey=ev.target.value;render(root);loadWage(root);});root.querySelector("#searchPick")?.addEventListener("input",ev=>{S.pickQ=ev.target.value;render(root);root.querySelector("#searchPick")?.focus();});}
function clickDraft(root,ev){let b=ev.target.closest("button");if(!b)return;if(b.dataset.tab){S.tab=b.dataset.tab;render(root);if(S.tab==="daily")loadDay(root);if(S.tab==="wage")loadWage(root);return;}if(b.dataset.step){S.step=b.dataset.step;S.chosen=null;render(root);return;}let a=b.dataset.a;if(a==="back")return S.back();if(a==="pick"){S.pick=true;S.pickQ="";render(root);setTimeout(()=>root.querySelector("#searchPick")?.focus(),0);return;}if(a==="close"){S.pick=false;render(root);return;}if(a==="choose"){S.chosen=S.data.whitewares[Number(b.dataset.i)];S.pick=false;render(root);return;}if(a==="present"){const card=b.closest(".pwa-att-card"),present=card.dataset.present!=="true";card.dataset.present=String(present);b.classList.toggle("present",present);b.textContent=present?"✅ มา":"❌ ไม่มา";card.querySelectorAll("input,select").forEach(x=>x.disabled=!present);return;}if(a==="refresh")return load(root);if(a==="fire")return fire(root,b.closest("article"));if(a==="prev")return setDay(root,date(new Date(`${S.day}T00:00`).getTime()-864e5));if(a==="next")return setDay(root,date(new Date(`${S.day}T00:00`).getTime()+864e5));if(a==="daily"){S.tab="daily";render(root);return loadDay(root);}if(a==="monthly"){S.tab="monthly";S.monthKey=S.day.slice(0,7);render(root);return loadMonth(root,S.monthKey);}if(a==="prevMonth"||a==="nextMonth"){let d=new Date(`${S.monthKey}-01T00:00`);d.setMonth(d.getMonth()+(a==="nextMonth"?1:-1));S.monthKey=date(d).slice(0,7);render(root);return loadMonth(root,S.monthKey);}if(a==="saveDay")return saveDay(root);if(["half","full","person"].includes(a)){S.wageMode=a;S.wageKey="";render(root);return loadWage(root);}if(["table","chart"].includes(a)){S.wageView=a;render(root);return;} }
async function load(root){try{let r=await S.api.workshopBootstrap(S.token);if(!r.ok)throw Error(r.message||r.error);S.data=r.result||{};render(root);}catch(x){S.toast(`เปิดหน้าจัดการงานช่างไม่สำเร็จ: ${x.message||x}`);}}
async function saveJob(root,ev){ev.preventDefault();const isGold=S.step==="วนทอง";if(!isGold&&!S.chosen)return S.toast("กรุณาเลือกของขาว");let v=id=>root.querySelector(id)?.value||"",d=isGold?{worker:v("#worker"),step:"วนทอง",whitewareSku:"",product:"วนทอง",size:"",pattern:"",sku:"",refRow:"",autoComplete:true,qty:Number(v("#qty")),priceEach:Number(v("#price")),stickerQty:0,stickerRate:0,jobDate:v("#jobDate"),dueDate:""}:{worker:v("#worker"),step:"เขียนลาย",whitewareSku:S.chosen.sku,product:S.chosen.name||S.chosen.product,size:S.chosen.size||"",pattern:S.chosen.pattern||"",sku:S.chosen.sku,qty:Number(v("#qty")),priceEach:Number(v("#price")),stickerQty:Number(v("#stickerQty")),stickerRate:Number(v("#stickerRate")),jobDate:v("#jobDate"),dueDate:v("#dueDate")};if(!d.worker)return S.toast("กรุณาเลือกช่าง");if(!Number.isInteger(d.qty)||d.qty<=0)return S.toast(isGold?"กรุณาใส่จำนวนครั้งเป็นจำนวนเต็ม":"กรุณาใส่จำนวนเป็นจำนวนเต็ม");if(!Number.isFinite(d.priceEach)||d.priceEach<=0)return S.toast("กรุณาระบุค่าจ้างที่มากกว่า 0");if(!d.jobDate)return S.toast("กรุณาเลือกวันที่จ่ายงาน");S.saving=true;render(root);try{let r=await S.api.workshopSaveJob(S.token,d),o=r.result;if(!r.ok||!o?.success)throw Error(o?.message||r.message);S.toast(o.message||"บันทึกสำเร็จ");S.chosen=null;await load(root);}catch(x){S.toast(`❌ ${x.message||x}`)}finally{S.saving=false;render(root);}}
async function fire(root,row){let pass=Number(row.querySelector('[data-k="pass"]')?.value),bad=Number(row.querySelector('[data-k="damaged"]')?.value),qty=Number(row.dataset.qty);if(!Number.isInteger(pass)||!Number.isInteger(bad)||pass<0||bad<0||pass+bad!==qty)return S.toast(`จำนวนผ่าน + เสีย ต้องเท่ากับ ${m(qty)}`);try{let r=await S.api.workshopConfirmFiring(S.token,Number(row.dataset.row),pass,bad),o=r.result;if(!r.ok||!o?.success)throw Error(o?.message||r.message);S.toast(o.message||"บันทึกสำเร็จ");load(root)}catch(x){S.toast(`❌ ${x.message||x}`)}}
async function setDay(root,d){if(!d||d>today())return;S.day=d;render(root);loadDay(root)}async function loadDay(root){if(S.daily[S.day])return;try{let r=await S.api.workshopAttendance(S.token,S.day);if(!r.ok)throw Error(r.message);S.daily[S.day]=r.result||[];if(S.tab==="daily")render(root)}catch(x){S.toast(`โหลดลงเวลาไม่สำเร็จ: ${x.message||x}`)}}
async function loadMonth(root,key){if(S.months[key])return;let [y,mo]=key.split("-").map(Number);try{let r=await S.api.workshopMonthlyAttendance(S.token,y,mo);if(!r.ok)throw Error(r.message);S.months[key]=r.result||[];if(S.tab==="monthly")render(root)}catch(x){S.toast(`โหลดปฏิทินไม่สำเร็จ: ${x.message||x}`)}}
async function saveDay(root){let reason=root.querySelector("#reason")?.value.trim()||"";if(S.day<today()&&!reason)return S.toast("กรุณาระบุเหตุผลการแก้ไขย้อนหลัง");let items=[...root.querySelectorAll(".pwa-att-card")].map(c=>{const dayFactor=Number(c.querySelector('[data-k="factor"]')?.value)||1;return {name:c.dataset.name,type:c.dataset.type,rate:Number(c.dataset.rate)||0,present:c.dataset.present==="true",timeIn:c.querySelector('[data-k="in"]')?.value||"",timeOut:c.querySelector('[data-k="out"]')?.value||"",dayFactor,dayType:dayFactor===.5?"ครึ่งวัน":"เต็มวัน",otHours:Number(c.querySelector('[data-k="ot"]')?.value)||0,otStart:c.querySelector('[data-k="otStart"]')?.value||"",otEnd:c.querySelector('[data-k="otEnd"]')?.value||"",otReason:reason,note:c.querySelector('[data-k="note"]')?.value||""};});for(let x of items){if(x.timeIn&&x.timeOut&&x.timeOut<x.timeIn)return S.toast(`เวลาออกของ ${x.name} ต้องไม่ก่อนเวลาเข้า`);if(x.otHours>0&&!x.present)return S.toast(`ไม่สามารถบันทึก OT ให้ ${x.name} ที่ไม่มาทำงานได้`)}S.saving=true;render(root);try{let r=await S.api.workshopSaveAttendance(S.token,{targetDate:S.day,items,reason}),o=r.result;if(!r.ok||!o?.success)throw Error(o?.message||r.message);delete S.daily[S.day];S.wages={};S.toast(o.message||"บันทึกสำเร็จ");loadDay(root)}catch(x){S.toast(`❌ ${x.message||x}`)}finally{S.saving=false;render(root)}}
async function loadWage(root){const periodMode=S.wageMode==="person"?(S.personPeriod||"half"):S.wageMode,ps=periods(periodMode),key=S.wageKey||`${ps[0][0]}|${ps[0][1]}`;S.wageKey=key;if(S.wages[key])return;let [a,b]=key.split("|");try{let r=await S.api.workshopWageSummary(S.token,a,b);if(!r.ok)throw Error(r.message);S.wages[key]=r.result||{};if(S.tab==="wage")render(root)}catch(x){S.toast(`โหลดสรุปค่าแรงไม่สำเร็จ: ${x.message||x}`)}}
/* Override the first-pass compact views with the same information hierarchy as GAS. */
function firing(){
  const rows=S.data?.firing||[];
  return `<section class="pwa-firing-wrap"><div class="pwa-workshop-title"><h2>🔥 คิวเผา</h2></div><div class="pwa-firing-list">${rows.length?rows.map(x=>{
    const pre=String(x.destination||"")==="Preorder",qty=Number(x.qty)||0;
    return `<article class="pwa-firing-card" data-row="${Number(x.row)}" data-qty="${qty}"><div class="pwa-firing-card-head"><div><div class="pwa-firing-card-name">${e(x.product||"")}</div><div class="pwa-firing-card-code">${e(x.id||"")}${x.finishedSku?` · ${e(x.finishedSku)}`:""}</div><div class="pwa-firing-destination ${pre?"preorder":"shop"}">${pre?`📋 งาน Preorder${x.preorderNo?` · ${e(x.preorderNo)}`:""}`:"🏪 เข้าสต๊อกร้าน"}</div></div><div class="pwa-firing-card-qty">รอเผา ${m(qty)} ชิ้น</div></div>${pre?`<div class="pwa-firing-preorder">${x.preorderNo?`อ้างอิง: ${e(x.preorderNo)}`:""}${x.trackingId?`${x.preorderNo?"<br>":""}รหัสติดตาม: ${e(x.trackingId)}`:""}${x.specialDetail?`<br>งานพิเศษ: ${e(x.specialDetail)}`:""}</div>`:""}<div class="pwa-firing-note ${pre?"preorder":"shop"}">${pre?"ผลผ่านจะบันทึกเข้า Preorder โดยไม่เพิ่มสต๊อกร้าน":"ผลผ่านจะรับเข้าสต๊อกสินค้าสำเร็จ"}</div><div class="pwa-firing-result-grid"><label class="pwa-firing-result-box pass"><span>✅ ผ่าน</span><input data-k="pass" type="number" min="0" max="${qty}" value="${qty}" inputmode="numeric"></label><label class="pwa-firing-result-box damage"><span>❌ เสีย</span><input data-k="damaged" type="number" min="0" max="${qty}" value="0" inputmode="numeric"></label></div><button class="pwa-firing-confirm-btn" data-a="fire">✅ ยืนยันหลังเปิดเตา</button></article>`;
  }).join(""):'<p class="pwa-workshop-empty">ไม่มีงานรอเผา</p>'}</div></section>`;
}
function wageBase(){
  const personMode=S.wageMode==="person", periodMode=personMode?(S.personPeriod||"half"):S.wageMode, ps=periods(periodMode),key=S.wageKey||`${ps[0][0]}|${ps[0][1]}`,data=S.wages[key];
  const names=[...new Map((S.data?.employees||[]).filter(x=>x?.name).map(x=>[x.name,{name:x.name,type:x.type||""}])).values()];
  return `<section class="pwa-workshop-panel pwa-wage-wrap"><div class="pwa-wage-modes"><button data-a="half" class="${S.wageMode==="half"?"active":""}">📅 15 วัน</button><button data-a="full" class="${S.wageMode==="full"?"active":""}">📆 รายเดือน</button><button data-a="person" class="${personMode?"active":""}">👤 รายคน</button></div>${personMode?`<div class="pwa-person-period"><button data-a="personHalf" class="${periodMode==="half"?"active":""}">งวด 15 วัน</button><button data-a="personFull" class="${periodMode==="full"?"active":""}">รายเดือน</button></div><label class="pwa-person-select">เลือกช่าง<select id="wagePerson"><option value="">-- เลือกช่าง --</option>${names.map(x=>`<option value="${e(x.name)}" ${S.wagePerson===x.name?"selected":""}>${e(x.name)}${x.type?` (${e(x.type)})`:""}</option>`).join("")}</select></label>`:""}${periodPicker(ps,key)}${!personMode?`<div class="pwa-wage-view"><button data-a="table" class="${S.wageView==="table"?"active":""}">📋 ตาราง</button><button data-a="chart" class="${S.wageView==="chart"?"active":""}">📊 กราฟ</button></div>`:""}${!data?'<p class="pwa-workshop-empty">⏳ กำลังโหลด...</p>':personMode?(S.wagePerson?personWage(data,S.wagePerson):'<p class="pwa-workshop-empty">เลือกช่างเพื่อดูรายละเอียดค่าจ้าง</p>'):S.wageView==="chart"?wageChart(data):wageTables(data)}</section>`;
}
function periodPicker(ps,key){const selected=ps.find(p=>`${p[0]}|${p[1]}`===key)||ps[0];return `<div class="pwa-period-picker"><button type="button" class="pwa-period-trigger" data-a="togglePeriods" aria-expanded="${S.periodOpen}"><span>${e(selected?.[2]||"เลือกงวด")}</span><b>⌄</b></button>${S.periodOpen?`<div class="pwa-period-menu" role="listbox">${ps.map(p=>{const value=`${p[0]}|${p[1]}`;return `<button type="button" data-a="selectPeriod" data-period="${value}" class="${value===key?"active":""}">${e(p[2])}</button>`}).join("")}</div>`:""}</div>`;}
function wage(){
  const periodMode=S.wageMode==="person"?(S.personPeriod||"half"):S.wageMode;
  if(periodMode!=="half"||S.wageMode==="person")return wageBase();
  const ps=periods("half"),key=S.wageKey||`${ps[0][0]}|${ps[0][1]}`,data=S.wages[key];
  return wageBase().replace("</section>",`${data?wagePeriodAction(data):""}</section>`);
}
function wagePeriodTotals(d){return Object.values(d?.advanceWageByWorker||{}).reduce((t,x)=>{t.workers++;t.wageTotal+=Number(x.wageTotal)||0;t.advance+=Number(x.deductedThisPeriod)||0;t.social+=Number(x.socialSecurityDeducted)||0;t.net+=Number(x.netPaid)||0;return t;},{workers:0,wageTotal:0,advance:0,social:0,net:0});}
function wagePeriodAction(d){const t=wagePeriodTotals(d),s=String(d?.wagePeriodStatus?.status||"not_saved"),st=d?.wagePeriodStatus||{},changed=s==="changed";if(!t.workers)return "";return `<section class="pwa-wage-period-action"><div class="pwa-wage-period-status ${s}">${s==="saved"?"✅ บันทึกค่าใช้จ่ายงวดนี้แล้ว":changed?"⚠️ ยอดเปลี่ยนหลังจากบันทึก":"ตรวจสอบยอดของช่างทุกคนก่อนบันทึก"}</div><div class="pwa-wage-period-totals"><span>รวมค่าแรง</span><b>฿${m(t.wageTotal)}</b>${t.advance?`<span>หักเงินเบิกล่วงหน้า</span><b>-฿${m(t.advance)}</b>`:""}${t.social?`<span>หักประกันสังคม</span><b>-฿${m(t.social)}</b>`:""}<strong>ยอดสุทธิที่จ่าย</strong><strong>฿${m(t.net)}</strong></div>${changed?`<div class="pwa-wage-period-difference"><span>ยอดเดิม ฿${m(st.savedNetPaid)}</span><span>ยอดล่าสุด ฿${m(st.latestNetPaid)}</span><b>ส่วนต่าง ${Number(st.difference)>=0?"+":"-"}฿${m(Math.abs(Number(st.difference)||0))}</b></div>`:""}${s==="saved"?'<p>ยอดในระบบตรงกับยอดคำนวณล่าสุด</p>':`<button data-a="confirmWages" class="pwa-wage-period-save">${changed?"🔄 ตรวจสอบแล้ว อัปเดตค่าใช้จ่ายงวดนี้":"✅ ตรวจสอบแล้ว บันทึกค่าใช้จ่ายงวดนี้"}</button>`}</section>`;}
function wageConfirmDialog(){if(!S.wageConfirm)return "";const t=wagePeriodTotals(S.wages[S.wageKey]||{});return `<div class="pwa-workshop-modal" role="dialog" aria-modal="true"><div class="pwa-workshop-dialog pwa-wage-confirm-dialog"><button class="pwa-dialog-x" data-a="closeWageConfirm" aria-label="ปิด">×</button><h2>ยืนยันบันทึกค่าใช้จ่ายงวด</h2><p>ระบบจะบันทึกยอดสุทธิค่าจ้างงวดนี้เป็นค่าใช้จ่ายจริง</p><div class="pwa-wage-confirm-total">ยอดสุทธิที่จ่าย <strong>฿${m(t.net)}</strong></div><div class="pwa-dialog-actions"><button data-a="closeWageConfirm">ยกเลิก</button><button data-a="submitWageConfirm" class="primary" ${S.wageConfirming?"disabled":""}>${S.wageConfirming?"⏳ กำลังบันทึก...":"✅ ยืนยันบันทึก"}</button></div></div></div>`;}
async function confirmWagePeriod(root){const [start,end]=S.wageKey.split("|");S.wageConfirming=true;render(root);try{const r=await S.api.workshopConfirmWagePeriod(S.token,start,end);if(!r.ok)throw Error(r.message);S.wageConfirm=false;delete S.wages[S.wageKey];S.toast("บันทึกค่าใช้จ่ายงวดนี้แล้ว");await loadWage(root);}catch(x){S.toast(`❌ ${x.message||x}`)}finally{S.wageConfirming=false;render(root);}}
function wageItemName(x){const parts=[],name=String(x?.whitewareName||x?.product||x?.name||"").trim(),size=String(x?.size||"").trim(),pattern=String(x?.pattern||"").trim();if(name)parts.push(name);if(size&&name.indexOf(size)<0)parts.push(size);if(pattern)parts.push(pattern);return parts.join(" · ")||"ไม่ระบุรายการ";}
function personItemSummary(items){if(!items.length)return "";const total=items.reduce((sum,x)=>sum+(Number(x.total)||0),0),qty=items.reduce((sum,x)=>sum+(Number(x.jobQty)||0),0),good=items.reduce((sum,x)=>sum+(Number(x.goodQty)||0),0),damaged=items.reduce((sum,x)=>sum+(Number(x.damagedQty)||0),0);return `<div class="pwa-person-job-summary">รวม ${m(items.length)} รายการ<br>จำนวนคิดค่าแรง ${m(qty)} ชิ้น · ดี ${m(good)} ชิ้น · เสีย ${m(damaged)} ชิ้น<br>รวมค่าแรงรายชิ้น ฿${m(total)}</div>`;}
function personWage(d,name){
  const piece=(d.pieceWork||[]).find(x=>x.name===name),daily=(d.dailyWork||[]).find(x=>x.name===name); if(!piece&&!daily)return '<p class="pwa-workshop-empty">ไม่พบข้อมูล</p>';
  const wage=(Number(piece?.completedTotal)||0)+(Number(daily?.total)||0),pending=Number(piece?.pendingTotal)||0,advance=d.advanceWageByWorker?.[name]||{},social=Number(advance.socialSecurityDeducted)||0,deduct=Number(advance.deductedThisPeriod)||0,net=advance.netPaid===undefined?Math.max(0,wage-social-deduct):Number(advance.netPaid)||0;
  const items=Array.isArray(piece?.completedItems)?piece.completedItems:[];
  return `<h3>👤 ${e(name)}</h3>${piece?`<table class="pwa-sum-table"><tr><th colspan="2">งานรายชิ้น</th></tr><tr><td>งานที่รับคืนในงวด</td><td class="right">${m(piece.jobs)} งาน</td></tr><tr><td>จำนวนคิดค่าแรง</td><td class="right">${m(piece.pieces)} ชิ้น</td></tr><tr><td>ผลรับคืน</td><td class="right">ดี ${m(piece.goodPieces)} · เสีย ${m(piece.damagedPieces)}</td></tr><tr><td>ค่าแรงที่รับรู้แล้ว</td><td class="right">฿${m(piece.completedTotal)}</td></tr><tr><td>งานที่อยู่ในมือ</td><td class="right">${m(piece.pendingJobs)} งาน · ${m(piece.pendingPieces)} ชิ้น</td></tr><tr><td>มูลค่างานค้าง</td><td class="right warn">฿${m(piece.pendingTotal)}</td></tr><tr><td>รวมคาดการณ์</td><td class="right strong">฿${m(piece.expectedTotal)}</td></tr></table>${items.length?`<section class="pwa-person-jobs"><h4>📋 รายการงานที่รับคืนในงวด</h4>${items.map((x,i)=>closedWageCard(x,i)).join("")}${personItemSummary(items)}</section>`:""}`:""}${daily?`<table class="pwa-sum-table"><tr><th colspan="2">งานรายวัน</th></tr><tr><td>วันทำงาน</td><td class="right">${m(daily.days)} วัน</td></tr><tr><td>อัตราต่อวัน</td><td class="right">฿${m(daily.rate)}</td></tr><tr><td>OT</td><td class="right">฿${m(daily.ot)}</td></tr><tr><td>ค่าแรงรวม</td><td class="right">฿${m(daily.total)}</td></tr></table>`:""}<div class="pwa-person-total">รวมค่าแรง ฿${m(wage)}${social?`<br>ฐานประกันสังคม ฿${m(advance.socialSecurityBase)}`:""}${social?`<br>หักประกันสังคม ${m(advance.socialSecurityRate)}% ฿${m(social)}`:""}${deduct?`<br>หักเงินเบิกล่วงหน้า ฿${m(deduct)}`:""}<strong>ยอดสุทธิที่จ่าย ฿${m(net)}</strong>${pending?`<small>งานค้างในมือ ฿${m(pending)} ยังไม่รวมยอดจ่าย</small>`:""}</div><button type="button" data-a="printWage" class="pwa-wage-print">🖨️ พิมพ์ใบสรุป</button>`;
}
function closedWageCard(x,i){const writing=String(x.step||"").includes("เขียนลาย"),qty=Number(x.jobQty)||0,rate=Number(x.priceEach)||0,stickerQty=Number(x.stickerQty)||0,stickerRate=Number(x.stickerRate)||0,total=Number(x.total)||0;return `<article class="pwa-person-job"><div><strong>${e(wageItemName(x))}</strong><small>${e(x.receiveDate||"")}${x.step?` · ${e(x.step)}`:""}<br>จำนวนคิดค่าแรง ${m(qty)} ชิ้น · ดี ${m(x.goodQty)} · เสีย ${m(x.damagedQty)}</small></div><div class="pwa-person-job-money">ค่าแรง ${m(qty)} × ฿${m(rate)}${writing&&stickerQty?`<br>ติดสติกเกอร์ ${m(stickerQty)} × ฿${m(stickerRate)}`:""}<b>รวม ฿${m(total)}</b></div><button type="button" data-a="editClosedWage" data-item="${i}">✏️ แก้ไขข้อมูลค่าแรง</button></article>`;}
function closedWageDialog(){const x=S.wageEdit;if(!x)return "";const writing=String(x.step||"").includes("เขียนลาย"),qty=Number(x.jobQty)||0,rate=Number(x.priceEach)||0,stickerQty=Number(x.stickerQty)||0,stickerRate=Number(x.stickerRate)||0,total=(qty*rate)+(stickerQty*stickerRate);return `<div class="pwa-workshop-modal" role="dialog" aria-modal="true"><section class="pwa-workshop-dialog pwa-closed-wage-dialog"><button class="pwa-dialog-x" data-a="closeClosedWage" aria-label="ปิด">×</button><h2>✏️ แก้ไขข้อมูลค่าแรง</h2><strong>${e(x.product||x.name||x.jobId||"รายการงาน")}</strong><p>จำนวนงานผลิตจริง ${m(x.productionQty??x.jobQty)} ชิ้น</p><div class="pwa-wage-warning">⚠️ แก้ได้เฉพาะจำนวนที่ใช้คิดค่าแรง ไม่เปลี่ยนสต๊อก ผล QC คิวเผา หรือ Preorder</div><div class="pwa-closed-wage-grid"><label>จำนวนคิดค่าแรง<input id="closedWageQty" type="number" min="0" step="1" value="${qty}"></label><label>อัตราค่าจ้าง<input id="closedWageRate" type="number" min="0" value="${rate}"></label>${writing?`<label>จำนวนติดสติกเกอร์<input id="closedStickerQty" type="number" min="0" step="1" value="${stickerQty}"></label><label>ค่าสติกเกอร์/ชิ้น<input id="closedStickerRate" type="number" min="0" value="${stickerRate}"></label>`:""}</div><div class="pwa-closed-wage-total">รวมค่าแรง <b id="closedWageTotal">฿${m(total)}</b></div><label>เหตุผลที่แก้ค่าแรง<input id="closedWageReason" maxlength="200" placeholder="เช่น บันทึกจำนวนหรืออัตราผิด"></label><div class="pwa-dialog-actions"><button data-a="closeClosedWage">ยกเลิก</button><button data-a="saveClosedWage" class="primary" ${S.wageEditSaving?"disabled":""}>${S.wageEditSaving?"⏳ กำลังบันทึก...":"💾 บันทึกแก้ไขค่าแรง"}</button></div></section></div>`;}
function wagePrintDialog(){if(!S.wagePrint)return "";return `<div class="pwa-workshop-modal" role="dialog" aria-modal="true"><section class="pwa-workshop-dialog pwa-wage-print-dialog"><button class="pwa-dialog-x" data-a="closeWagePrint" aria-label="ปิด">×</button><h2>🖨️ พิมพ์ใบสรุปค่าจ้าง</h2><div class="pwa-sign-choice"><button data-a="signDefault" class="${S.wagePrint.signerMode!=="other"?"active":""}">ผู้จ่ายเงินตามค่าเริ่มต้น</button><button data-a="signOther" class="${S.wagePrint.signerMode==="other"?"active":""}">ระบุชื่อผู้จ่ายเงิน</button></div>${S.wagePrint.signerMode==="other"?`<label>ชื่อผู้จ่ายเงิน<input id="wagePrintSigner" value="${e(S.wagePrint.signer||"")}"></label>`:""}<label>วันที่เอกสาร<input id="wagePrintDate" type="date" value="${e(S.wagePrint.date||today())}"></label><div class="pwa-dialog-actions"><button data-a="closeWagePrint">ยกเลิก</button><button data-a="confirmWagePrint" class="primary">🖨️ พิมพ์</button></div></section></div>`;}
function refreshClosedWageTotal(){const q=Number(document.querySelector("#closedWageQty")?.value)||0,r=Number(document.querySelector("#closedWageRate")?.value)||0,sq=Number(document.querySelector("#closedStickerQty")?.value)||0,sr=Number(document.querySelector("#closedStickerRate")?.value)||0;const out=document.querySelector("#closedWageTotal");if(out)out.textContent=`฿${m(q*r+sq*sr)}`;}
async function saveClosedWage(root){const x=S.wageEdit;if(!x)return;const wageQty=Number(root.querySelector("#closedWageQty")?.value),wageRate=Number(root.querySelector("#closedWageRate")?.value),stickerQty=Number(root.querySelector("#closedStickerQty")?.value||0),stickerRate=Number(root.querySelector("#closedStickerRate")?.value||0),reason=String(root.querySelector("#closedWageReason")?.value||"").trim();if(!Number.isInteger(wageQty)||wageQty<0)return S.toast("จำนวนคิดค่าแรงไม่ถูกต้อง");if(!Number.isFinite(wageRate)||wageRate<0)return S.toast("อัตราค่าจ้างไม่ถูกต้อง");if(!Number.isInteger(stickerQty)||stickerQty<0||stickerQty>wageQty)return S.toast("จำนวนสติกเกอร์ไม่ถูกต้อง");if(!Number.isFinite(stickerRate)||stickerRate<0)return S.toast("อัตราสติกเกอร์ไม่ถูกต้อง");if(!reason)return S.toast("กรุณาระบุเหตุผลที่แก้ค่าแรง");S.wageEditSaving=true;render(root);try{const r=await S.api.workshopUpdateClosedWage(S.token,{rowIdx:Number(x.rowIdx),wageQty,wageRate,stickerQty,stickerRate,reason});if(!r.ok||!r.result?.success)throw Error(r.result?.message||r.message||"บันทึกไม่สำเร็จ");S.wageEdit=null;S.wages={};S.toast(`✅ ${r.result.message||"บันทึกแก้ไขค่าแรงแล้ว"}`);await loadWage(root);}catch(error){S.toast(`❌ ${error.message||error}`)}finally{S.wageEditSaving=false;render(root)}}
function thaiPrintDate(value){const d=new Date(`${value}T00:00`);return d.toLocaleDateString("th-TH",{year:"numeric",month:"long",day:"numeric"});}
function wagePrintMarkup(data,name,periodText,signer,documentDate){
  const piece=(data.pieceWork||[]).find(x=>x.name===name),daily=(data.dailyWork||[]).find(x=>x.name===name),advance=data.advanceWageByWorker?.[name]||{},items=Array.isArray(piece?.completedItems)?piece.completedItems:[],groups=new Map(),shop=S.data?.shop||{};
  items.forEach(x=>{const label=wageItemName(x),step=String(x.step||"").trim(),rate=Number(x.priceEach)||0,key=`${label}|${step}|${rate}`,row=groups.get(key)||{label,step,qty:0,rate,total:0};row.qty+=Number(x.jobQty)||0;row.total+=Number(x.writingTotal)||0;groups.set(key,row);if(Number(x.stickerQty)>0){const sk=`ค่าติดสติกเกอร์||${Number(x.stickerRate)||0}`,sr=groups.get(sk)||{label:"ค่าติดสติกเกอร์",step:"",qty:0,rate:Number(x.stickerRate)||0,total:0};sr.qty+=Number(x.stickerQty)||0;sr.total+=Number(x.stickerTotal)||0;groups.set(sk,sr);}});
  const rows=[...groups.values()],wage=(Number(piece?.completedTotal)||0)+(Number(daily?.total)||0),social=Number(advance.socialSecurityDeducted)||0,deduct=Number(advance.deductedThisPeriod)||0,after=Number(advance.balance)||0,net=advance.netPaid===undefined?Math.max(0,wage-social-deduct):Number(advance.netPaid)||0,addr=[shop.address,shop.phone?`โทร ${shop.phone}`:""].filter(Boolean).join(" | ");
  const detail=rows.length?rows.map((x,i)=>`<tr><td class="text-center">${i+1}</td><td>${e(x.label)}${x.step&&x.label.indexOf(x.step)<0?` · ${e(x.step)}`:""}</td><td class="text-right">${m(x.qty)}</td><td class="text-right">฿${m(x.rate)}</td><td class="text-right">฿${m(x.total)}</td></tr>`).join(""):`${daily&&Number(daily.days)>0?"":'<tr><td colspan="5" class="text-center">ไม่มีรายการค่าแรงในงวดนี้</td></tr>'}`;
  const dailyRow=daily&&Number(daily.days)>0?`<tr><td class="text-center">${rows.length+1}</td><td>ค่าแรงรายวัน${Number(daily.ot)>0?" รวม OT":""}</td><td class="text-right">${m(daily.days)} วัน</td><td class="text-right">฿${m(daily.rate)}</td><td class="text-right">฿${m(daily.total)}</td></tr>`:"";
  return `<div id="pwaWagePrint" class="pwa-wage-print-sheet"><div class="pf-header">${shop.logo?`<img class="pf-logo" src="${e(shop.logo)}" alt="โลโก้ร้าน">`:""}<div class="pf-shop">${e(shop.name||"สุพรรณบุรีเบญจรงค์")}</div>${addr?`<div class="pf-addr">${e(addr)}</div>`:""}<div class="pf-title">ใบสรุปค่าจ้างช่าง</div><div class="pf-period">ชื่อช่าง: ${e(name)}${periodText?` | งวด: ${e(periodText)}`:""}</div></div><table class="pf-table"><tr><th style="width:45px">ลำดับ</th><th>รายการงาน</th><th style="width:75px">จำนวน</th><th style="width:85px">อัตรา</th><th style="width:100px">รวม</th></tr>${detail}${dailyRow}</table><table class="pf-summary"><tr><td class="pf-summary-label">รวมค่าแรง</td><td class="pf-summary-value">฿${m(wage)}</td></tr>${social?`<tr><td class="pf-summary-label">ฐานประกันสังคม</td><td class="pf-summary-value">฿${m(advance.socialSecurityBase)}</td></tr><tr><td class="pf-summary-label">หักประกันสังคม ${m(advance.socialSecurityRate)}%</td><td class="pf-summary-value">-฿${m(social)}</td></tr>`:""}${deduct?`<tr><td class="pf-summary-label">หักเงินเบิกล่วงหน้า</td><td class="pf-summary-value">-฿${m(deduct)}</td></tr>`:""}<tr class="pf-net-row"><td class="pf-summary-label">ยอดสุทธิที่จ่าย</td><td class="pf-summary-value">฿${m(net)}</td></tr>${after?`<tr><td class="pf-summary-label">ยอดเบิกเหลือหักงวดหน้า</td><td class="pf-summary-value">฿${m(after)}</td></tr>`:""}</table><div class="pf-sign"><div class="pf-sign-box"><div class="pf-sign-line"></div><div>${e(signer)}</div><div class="pf-sign-label">ผู้จ่ายเงิน</div><div class="pf-sign-label">วันที่ ${e(thaiPrintDate(documentDate))}</div></div><div class="pf-sign-box"><div class="pf-sign-line"></div><div>${e(name)}</div><div class="pf-sign-label">ผู้รับเงิน</div><div class="pf-sign-label">วันที่ ${e(thaiPrintDate(documentDate))}</div></div></div><div class="pf-note">เอกสารฉบับนี้เป็นใบสรุปค่าจ้างประจำงวด</div></div>`;
}
function printWage(root){const dateValue=String(root.querySelector("#wagePrintDate")?.value||""),other=String(root.querySelector("#wagePrintSigner")?.value||"").trim(),signer=S.wagePrint.signerMode==="other"?other:"นายวรากร วงศธรบุญรัศมิ์";if(!signer)return S.toast("กรุณาระบุชื่อผู้จ่ายเงิน");if(!dateValue)return S.toast("กรุณาเลือกวันที่เอกสาร");const option=(periods(S.personPeriod||"half").find(x=>`${x[0]}|${x[1]}`===S.wageKey)||[])[2]||"";const data=S.wages[S.wageKey]||{};const sheet=wagePrintMarkup(data,S.wagePerson,option,signer,dateValue);S.wagePrint=false;render(root);const holder=document.createElement("div");holder.className="pwa-wage-print-host";holder.innerHTML=sheet;document.body.appendChild(holder);const clean=()=>{holder.remove();window.removeEventListener("afterprint",clean)};window.addEventListener("afterprint",clean);setTimeout(()=>{try{window.print()}catch(error){clean();S.toast("เปิดหน้าพิมพ์ไม่สำเร็จ")}},120);}
function bind(root){
  root.onclick=ev=>{
    if(S.periodOpen&&!ev.target.closest(".pwa-period-picker")){S.periodOpen=false;root.querySelector(".pwa-period-menu")?.remove();root.querySelector(".pwa-period-trigger")?.setAttribute("aria-expanded","false");return;}
    if(ev.target.classList?.contains("pwa-workshop-modal")){
      if(S.handoffConfirm&&!S.handoffSaving)S.handoffConfirm=null;
      else if(S.wageEdit&&!S.wageEditSaving)S.wageEdit=null;
      else if(S.wagePrint)S.wagePrint=false;
      else if(S.wageConfirm&&!S.wageConfirming)S.wageConfirm=false;
      else if(S.pick)S.pick=false;
      render(root);return;
    }
    const button=ev.target.closest("button"),a=button?.dataset.a;
    if(a==="handoffRefresh"){S.handoff=null;render(root);return;}
    if(a==="handoffConfirm"){const card=(S.handoff?.cards||[]).find(x=>x.id===button.dataset.job),sub=(card?.submissions||[]).find(x=>x.id===button.dataset.sub);if(sub){S.handoffConfirm={jobId:card.id,submissionId:sub.id,qty:Number(sub.qty)||0};render(root);}return;}
    if(a==="closeHandoff"){if(!S.handoffSaving){S.handoffConfirm=null;render(root);}return;}
    if(a==="saveHandoff"){saveHandoff(root);return;}
    if(a==="confirmWages"){S.wageConfirm=true;render(root);return;}
    if(a==="closeWageConfirm"){S.wageConfirm=false;render(root);return;}
    if(a==="submitWageConfirm"){confirmWagePeriod(root);return;}
    if(a==="togglePeriods"){S.periodOpen=!S.periodOpen;render(root);return;}
    if(a==="selectPeriod"){S.wageKey=button.dataset.period;S.periodOpen=false;render(root);loadWage(root);return;}
    if(a==="editClosedWage"){const data=S.wages[S.wageKey],item=(data?.pieceWork||[]).find(x=>x.name===S.wagePerson)?.completedItems?.[Number(button.dataset.item)];if(item){S.wageEdit={...item};render(root);}return;}
    if(a==="closeClosedWage"){if(!S.wageEditSaving){S.wageEdit=null;render(root);}return;}
    if(a==="saveClosedWage"){saveClosedWage(root);return;}
    if(a==="printWage"){S.wagePrint={signerMode:"default",signer:"",date:today()};render(root);return;}
    if(a==="closeWagePrint"){S.wagePrint=false;render(root);return;}
    if(a==="signDefault"||a==="signOther"){S.wagePrint={...S.wagePrint,signerMode:a==="signOther"?"other":"default"};render(root);return;}
    if(a==="confirmWagePrint"){printWage(root);return;}
    click(root,ev);
  };
  root.querySelector("#wsForm")?.addEventListener("submit",ev=>saveJob(root,ev));
  root.querySelector("#wsForm")?.addEventListener("input",()=>updateJobTotal(root));
  root.querySelector("#dayPick")?.addEventListener("change",ev=>setDay(root,ev.target.value));
  root.querySelector("#wagePerson")?.addEventListener("change",ev=>{S.wagePerson=ev.target.value;render(root);});
  root.querySelector(".pwa-closed-wage-dialog")?.addEventListener("input",refreshClosedWageTotal);
  root.querySelector("#searchPick")?.addEventListener("input",ev=>{S.pickQ=ev.target.value;render(root);root.querySelector("#searchPick")?.focus();});
  S.root=root;
  if(!S.escapeBound){S.escapeBound=true;document.addEventListener("keydown",ev=>{if(ev.key!=="Escape")return;if(S.periodOpen){S.periodOpen=false;S.root?.querySelector(".pwa-period-menu")?.remove();S.root?.querySelector(".pwa-period-trigger")?.setAttribute("aria-expanded","false");ev.preventDefault();return;}let changed=false;if(S.handoffConfirm&&!S.handoffSaving){S.handoffConfirm=null;changed=true;}else if(S.wageEdit&&!S.wageEditSaving){S.wageEdit=null;changed=true;}else if(S.wagePrint){S.wagePrint=false;changed=true;}else if(S.wageConfirm&&!S.wageConfirming){S.wageConfirm=false;changed=true;}else if(S.pick){S.pick=false;changed=true;}if(changed){ev.preventDefault();render(S.root);}});}
}
async function saveHandoff(root){const c=S.handoffConfirm;if(!c)return;const card=(S.handoff?.cards||[]).find(x=>x.id===c.jobId)||{},whitewareSku=String(root.querySelector("#handoffWhiteware")?.value||""),finishedSku=String(root.querySelector("#handoffFinished")?.value||""),priceEach=Number(root.querySelector("#handoffPrice")?.value);if(String(card.role||"").includes("เขียนลาย")&&!whitewareSku)return S.toast("กรุณาเลือกของขาว");if(!finishedSku)return S.toast("กรุณาเลือก SKU สินค้าหลังเผา");if(!Number.isFinite(priceEach)||priceEach<=0)return S.toast("กรุณาระบุค่าจ้างที่มากกว่า 0");S.handoffSaving=true;render(root);try{const r=await S.api.workerPortalConfirmToFiring(S.token,{submissionId:c.submissionId,whitewareSku,finishedSku,priceEach});if(!r.ok||!r.result?.success)throw Error(r.result?.message||r.message||"ยืนยันไม่สำเร็จ");S.handoffConfirm=null;S.handoff=null;S.toast(`✅ ${r.result.message||"ส่งเข้าคิวเผาแล้ว"}`);render(root);}catch(error){S.toast(`❌ ${error.message||error}`);S.handoffSaving=false;render(root);}}
function click(root,ev){let b=ev.target.closest("button");if(!b)return;if(b.dataset.tab){S.tab=b.dataset.tab;render(root);if(S.tab==="daily")loadDay(root);if(S.tab==="wage")loadWage(root);return;}if(b.dataset.step){S.step=b.dataset.step;S.chosen=null;render(root);return;}let a=b.dataset.a;if(a==="back")return S.back();if(a==="pick"){S.pick=true;S.pickQ="";render(root);setTimeout(()=>root.querySelector("#searchPick")?.focus(),0);return;}if(a==="close"){S.pick=false;render(root);return;}if(a==="choose"){S.chosen=S.data.whitewares[Number(b.dataset.i)];S.pick=false;render(root);return;}if(a==="present"){const card=b.closest(".pwa-att-card"),present=card.dataset.present!=="true";card.dataset.present=String(present);b.classList.toggle("present",present);b.textContent=present?"✅ มา":"❌ ไม่มา";card.querySelectorAll("input,select").forEach(x=>x.disabled=!present);return;}if(a==="refresh")return load(root);if(a==="fire")return fire(root,b.closest("article"));if(a==="prev")return setDay(root,date(new Date(`${S.day}T00:00`).getTime()-864e5));if(a==="next")return setDay(root,date(new Date(`${S.day}T00:00`).getTime()+864e5));if(a==="daily"){S.tab="daily";render(root);return loadDay(root);}if(a==="monthly"){S.tab="monthly";S.monthKey=S.day.slice(0,7);render(root);return loadMonth(root,S.monthKey);}if(a==="prevMonth"||a==="nextMonth"){let d=new Date(`${S.monthKey}-01T00:00`);d.setMonth(d.getMonth()+(a==="nextMonth"?1:-1));S.monthKey=date(d).slice(0,7);render(root);return loadMonth(root,S.monthKey);}if(a==="saveDay")return saveDay(root);if(["half","full","person"].includes(a)){S.wageMode=a;S.wageKey="";render(root);return loadWage(root);}if(a==="personHalf"||a==="personFull"){S.personPeriod=a==="personHalf"?"half":"full";S.wageKey="";render(root);return loadWage(root);}if(["table","chart"].includes(a)){S.wageView=a;render(root);return;} }
async function loadHandoff(root){try{const r=await S.api.workerPortalOwnerQueue(S.token);if(!r.ok)throw Error(r.message||r.error);S.handoff=r.result||{};if(S.tab==="receive")render(root);}catch(x){S.toast(`โหลดงานจาก App ช่างไม่สำเร็จ: ${x.message||x}`);}}
export function renderWorkshop(root,api,token,onBack,context={}){S.api=api;S.token=token;S.back=onBack;S.toast=context.toast||(()=>{});if(!S.day)S.day=today();if(S.step!=="วนทอง")S.step="เขียนลาย";render(root);if(!S.data)load(root);}
