import assert from 'node:assert/strict';
import fs from 'node:fs';

const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const worker=fs.readFileSync(new URL('../service-worker.js',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../js/app.js',import.meta.url),'utf8');

assert.match(html,/\.\/js\/app\.js\?v=app-v86/,'HTML must request the current app bundle');
assert.match(html,/\.\/css\/app\.css\?v=login-v2/,'HTML must request the login-preview stylesheet by a new URL');
assert.match(worker,/const VERSION="suphan-pwa-v211"/,'service worker cache must be replaced for this release');
assert.match(worker,/\.\/js\/app\.js\?v=app-v86/,'offline shell must match the new app bundle');
assert.match(worker,/\.\/css\/app\.css\?v=login-v2/,'offline shell must match the new stylesheet');
assert.match(html,/\.\/css\/home-depth\.css\?v=home-depth-v7/,'HTML must request the updated home design');
assert.match(worker,/\.\/css\/home-depth\.css\?v=home-depth-v7/,'offline shell must cache the updated home design');
assert.match(html,/\.\/css\/stock-fixes\.css\?v=stock-fix-v5/,'HTML must request the mobile stock fix');
assert.match(worker,/\.\/css\/stock-fixes\.css\?v=stock-fix-v5/,'offline shell must cache the mobile stock fix');
assert.match(html,/\.\/css\/pos\.css\?v=pos-v24/,'HTML must request the updated POS print styles');
assert.match(worker,/\.\/css\/pos\.css\?v=pos-v24/,'offline shell must cache the updated POS print styles');
assert.match(worker,/\.\/js\/pos\.js\?v=pos-v25/,'offline shell must cache the current POS module');
assert.match(html,/\.\/css\/expense-day-groups\.css\?v=expense-v12/,'HTML must request expense category icons');
assert.match(worker,/\.\/css\/expense-day-groups\.css\?v=expense-v12/,'offline shell must cache expense category icons');
assert.match(worker,/\.\/js\/expense\.js\?v=expense-v14/,'offline shell must cache the current expense module');
assert.match(html,/\.\/css\/menu-icons\.css\?v=menu-icons-v1/,'HTML must request the menu icon stylesheet');
assert.match(worker,/\.\/css\/menu-icons\.css\?v=menu-icons-v1/,'offline shell must cache the menu icon stylesheet');
assert.match(app,/\.\/menu-icons\.js\?v=menu-icons-v1/,'app must import the versioned menu icons');
assert.match(worker,/\.\/js\/menu-icons\.js\?v=menu-icons-v1/,'offline shell must cache the menu icons module');
assert.match(html,/\.\/css\/list-performance\.css\?v=list-performance-v1/,'HTML must request the catalog performance stylesheet');
assert.match(worker,/\.\/css\/list-performance\.css\?v=list-performance-v1/,'offline shell must cache the catalog performance stylesheet');
assert.match(app,/service-worker\.js\?v=163/,'the browser must check the updated service worker');
assert.match(html,/preorder-fixes\.css\?v=preorder-fix-v11/,'HTML must request QT/PO multipage print styles');
assert.match(worker,/preorder-fixes\.css\?v=preorder-fix-v11/,'offline shell must cache QT/PO print styles');
assert.match(worker,/preorder\.js\?v=preorder-v19/,'offline shell must cache the current QT/PO module');
assert.match(html,/workshop\.css\?v=workshop-v20/,'HTML must request multipage wage print styles');
assert.match(worker,/workshop\.css\?v=workshop-v20/,'offline shell must cache multipage wage print styles');
assert.match(app,/workshop\.js\?v=workshop-v30/,'app must import the multipage wage print module');
assert.match(worker,/workshop\.js\?v=workshop-v30/,'offline shell must cache the multipage wage print module');
console.log('release cache bust: PASS');
