import {ApiClient} from "../js/api.js?v=worker-login-v2";
// Same loading animation as the main app (bowl + ring).
import {installLoader,loaderFull} from "../js/loader.js?v=loader-v1";
const api=new ApiClient(),app=document.querySelector("#app"),toastEl=document.querySelector("#toast");
const KEY="suphan.worker.portal.session",NAME_KEY="suphan.worker.portal.user";
let state={token:sessionStorage.getItem(KEY)||"",user:readUser(),pending:"",users:[],data:null,syncing:false,tab:"jobs",role:"เขียนลาย",kind:"เบญจรงค์",photos:{}};
const OP_KEY="suphan.worker.portal.pending-operations";
// Day-paid workers record wage-free day jobs only (เคลือบมุก / ติดสติกเกอร์):
// the owner picks the whiteware and finished SKU when confirming.
const DAILY_ROLES=["เคลือบมุก","ติดสติกเกอร์"],PIECE_ROLES=["เขียนลาย","ลงสี","วนทอง"];
const isDaily=role=>DAILY_ROLES.includes(String(role||""));
// The owner's test account previews every form; its records never reach the real queue.
const roles=()=>state.user?.isOwnerTest?[...PIECE_ROLES,...DAILY_ROLES]:state.user?.daily?DAILY_ROLES:PIECE_ROLES;
const priceText=j=>isDaily(j.role)?"ตามวันทำงาน":`฿${money(j.priceEach)}`;
let workerPinScreen=false,workerUpdateReloading=false,workerUpdateCheckQueued=false;
function checkWorkerUpdate(){if(!("serviceWorker" in navigator)||workerUpdateCheckQueued)return;workerUpdateCheckQueued=true;const run=()=>{workerUpdateCheckQueued=false;if(!workerPinScreen)return;navigator.serviceWorker.getRegistration("./").then(reg=>{if(!reg)return;return reg.update().then(()=>{if(workerPinScreen&&reg.waiting)reg.waiting.postMessage({type:"SKIP_WAITING"})})}).catch(()=>{})};if("requestIdleCallback" in window)window.requestIdleCallback(run,{timeout:2000});else setTimeout(run,1200)}
navigator.serviceWorker?.addEventListener("controllerchange",()=>{if(workerPinScreen&&!workerUpdateReloading){workerUpdateReloading=true;location.reload()}});
function operationId(action,key){try{const all=JSON.parse(sessionStorage.getItem(OP_KEY)||"{}"),slot=`${action}|${key}`;if(!all[slot]){all[slot]=`wp_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,12)}`;sessionStorage.setItem(OP_KEY,JSON.stringify(all));}return all[slot]}catch{return `wp_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,12)}`}}
function finishOperation(action,key){try{const all=JSON.parse(sessionStorage.getItem(OP_KEY)||"{}"),slot=`${action}|${key}`;delete all[slot];sessionStorage.setItem(OP_KEY,JSON.stringify(all))}catch{}}
function readUser(){try{return JSON.parse(sessionStorage.getItem(NAME_KEY)||"null")}catch{return null}}
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const money=v=>(Number(v)||0).toLocaleString("th-TH"),today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};// the phone's local date: toISOString() is UTC and gave yesterday before 07:00

function toast(v){toastEl.textContent=v;toastEl.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>toastEl.classList.remove("show"),2600)}
function busy(button,label){if(!button)return()=>{};const original=button.innerHTML;button.disabled=true;button.classList.add("is-saving");button.textContent=`⏳ ${label}`;return()=>{button.disabled=false;button.classList.remove("is-saving");button.innerHTML=original}}
function brand(s="บันทึกรับงานและส่งงานให้เจ้าของตรวจ"){/* data-bj: the header line is a title, never a loading placeholder */return `<header class="brand" data-bj="1"><img src="../assets/worker-app-icon.png" alt="โลโก้"><div><h1>ระบบบันทึกงานช่าง</h1><p>${esc(s)}</p></div></header>`}
function loading(stage="กำลังยืนยัน PIN ช่าง...",detail="โปรดรอสักครู่ ระบบกำลังเตรียมข้อมูลของคุณ"){app.innerHTML=`<div class="page worker-loading">${brand(stage)}<section class="card worker-loading-card">${loaderFull()}<p class="hint">${esc(detail)}</p></section></div>`}
function clear(){sessionStorage.removeItem(KEY);sessionStorage.removeItem(NAME_KEY);state.token="";state.user=null;state.data=null}
function pin(msg=""){workerPinScreen=true;checkWorkerUpdate();app.innerHTML=`<div class="page"><section class="card pin">${brand("ใส่ PIN ช่าง 4–8 หลัก")}<input id="pin" type="password" inputmode="numeric" maxlength="8" autocomplete="current-password"><p class="hint">${esc(msg)}</p><button class="btn" id="login">เข้าสู่ระบบ</button><p class="hint">เข้าครั้งแรกหรือลืม PIN: ใส่รหัสตั้ง PIN ที่ได้จากเจ้าของร้าน</p></section></div>`;const e=document.querySelector("#pin");e.focus();e.oninput=()=>{e.value=e.value.replace(/\D/g,"")};e.onkeydown=x=>{if(x.key==="Enter")login(e.value)};document.querySelector("#login").onclick=()=>login(e.value)}
async function login(v){if(!/^\d{4,8}$/.test(v))return toast("กรุณาใส่ PIN 4–8 หลัก");workerPinScreen=false;loading();try{const r=await api.workerLogin(v);if(!r.ok||r.level!=="worker")throw Error(r.message||r.error||"PIN ไม่ถูกต้อง หรือยังไม่ได้เปิดสิทธิ์ช่าง");if(r.setup)return setupPin(r);state.pending=r.session;state.users=Array.isArray(r.users)?r.users:[];if(r.user?.name)return signedIn(r);if(!state.users.length)throw Error("ไม่พบรายชื่อช่างที่ทำงานอยู่");picker()}catch(e){pin(e?.message||String(e)||"เข้าสู่ระบบไม่สำเร็จ")}}
function signedIn(r){state.token=r.session;state.user=r.user;state.data={worker:r.user,jobs:[],submissions:[]};state.syncing=true;sessionStorage.setItem(KEY,state.token);sessionStorage.setItem(NAME_KEY,JSON.stringify(state.user));render();refreshBackground()}
// First sign-in or after the owner reset the PIN: the worker chooses their own.
function setupPin(r,msg=""){workerPinScreen=false;const name=r.user?.name||"";app.innerHTML=`<div class="page"><section class="card pin">${brand("ตั้ง PIN ของคุณ")}<p class="hint">สวัสดี <b>${esc(name)}</b> · ตั้ง PIN 4–8 หลักที่จำได้ง่าย ใช้เข้าแอปช่างครั้งต่อไป</p><input id="pin1" type="password" inputmode="numeric" maxlength="8" autocomplete="new-password" placeholder="PIN ใหม่"><input id="pin2" type="password" inputmode="numeric" maxlength="8" autocomplete="new-password" placeholder="ใส่อีกครั้ง"><p class="hint" id="setup-msg">${esc(msg)}</p><button class="btn" id="setup-save">บันทึก PIN</button><button class="btn secondary" id="setup-cancel">ยกเลิก</button></section></div>`;const a=document.querySelector("#pin1"),b=document.querySelector("#pin2");[a,b].forEach(e=>e.oninput=()=>{e.value=e.value.replace(/\D/g,"")});a.focus();document.querySelector("#setup-cancel").onclick=()=>pin();const save=async()=>{if(!/^\d{4,8}$/.test(a.value))return toast("PIN ต้องเป็นตัวเลข 4–8 หลัก");if(a.value!==b.value)return toast("PIN สองช่องไม่ตรงกัน");const done=busy(document.querySelector("#setup-save"),"กำลังบันทึก PIN...");try{const x=await api.workerPinSet(r.setupToken,a.value);if(!x.ok||!x.session||!x.user?.name){if(x.error==="SESSION_EXPIRED")return pin(x.message||"หมดเวลาตั้ง PIN กรุณาเริ่มใหม่");throw Error(x.message||x.error||"ตั้ง PIN ไม่สำเร็จ")}toast("ตั้ง PIN เรียบร้อยแล้ว");signedIn(x)}catch(e){done();const m=document.querySelector("#setup-msg");if(m)m.textContent=e.message||"ตั้ง PIN ไม่สำเร็จ";toast(e.message||"ตั้ง PIN ไม่สำเร็จ")}};document.querySelector("#setup-save").onclick=save;b.onkeydown=x=>{if(x.key==="Enter")save()}}
// Opened from the check-in page: the link already proves whose phone this is.
async function linkLogin(token){history.replaceState(null,"",location.pathname+location.search);clear();loading("กำลังเปิดแอปช่าง...","ตรวจสอบลิงก์จากหน้าลงเวลา");try{const r=await api.workerLinkLogin(token);if(!r.ok)throw Error(r.message||r.error||"ลิงก์ใช้ไม่ได้");if(r.setup)return setupPin(r);if(!r.session||!r.user?.name)throw Error("ลิงก์ใช้ไม่ได้");signedIn(r)}catch(e){pin(e?.message||"เปิดจากลิงก์ไม่สำเร็จ กรุณาใส่ PIN")}}
async function refreshBackground(){try{const r=await api.workerPortalBootstrap(state.token);if(!r.ok)throw Error(r.message||r.error);state.data=r.result;state.user=r.result.worker||state.user;sessionStorage.setItem(NAME_KEY,JSON.stringify(state.user));}catch(e){toast("โหลดรายการงานไม่สำเร็จ · กดรีเฟรชภายหลังได้")}finally{state.syncing=false;render()}}
function picker(){app.innerHTML=`<div class="page">${brand("เลือกชื่อของคุณก่อนเริ่มงาน")}<section class="people">${state.users.map((u,i)=>`<button class="person" data-user="${i}"><span>🧑‍🎨</span><strong>${esc(u.name)}</strong><small>${esc(u.role)}</small></button>`).join("")}</section></div>`;app.querySelectorAll("[data-user]").forEach(b=>b.onclick=()=>choose(state.users[+b.dataset.user]))}
async function choose(u){loading("กำลังเปิดงานของคุณ...","ตรวจสอบชื่อช่างและโหลดรายการที่ได้รับ");try{let token=u?.token;if(!u?.name)throw Error("ไม่พบชื่อช่าง");if(!token){const r=await api.selectUser(state.pending,u.name);if(!r.ok||!r.token)throw Error(r.message||r.error||"เลือกชื่อช่างไม่สำเร็จ");token=r.token}const r=await api.workerPortalBootstrap(token);if(!r.ok)throw Error(r.message||r.error||"ยังโหลดข้อมูลงานไม่ได้");state.token=token;state.user=r.result.worker||{name:u.name,role:u.role||""};state.data=r.result;sessionStorage.setItem(KEY,token);sessionStorage.setItem(NAME_KEY,JSON.stringify(state.user));render()}catch(e){clear();pin(`เลือกชื่อช่างไม่สำเร็จ: ${e.message||"กรุณาใส่ PIN ใหม่"}`)}}
async function refreshData(quiet){state.lastRefresh=Date.now();const r=await api.workerPortalBootstrap(state.token);if(!r.ok)throw Error(r.message||r.error||"เชื่อมต่อข้อมูลช่างไม่สำเร็จ");state.data=r.result;state.user=r.result.worker||state.user;sessionStorage.setItem(NAME_KEY,JSON.stringify(state.user));if(!(quiet&&state.tab==="jobs"))render()}
// Mutations already return only after GAS has committed.  Refresh the complete
// workbook payload later so a worker is never held at a button for a second trip.
function refreshSoon(){setTimeout(()=>refreshData().catch(()=>toast("บันทึกแล้ว · โหลดรายการล่าสุดภายหลัง")),0)}
async function load(){loading("กำลังโหลดงานของช่าง...","กำลังตรวจสอบรายการรับงานและประวัติของคุณ");try{await refreshData()}catch(e){if(/SESSION|USER_REQUIRED|FORBIDDEN/.test(String(e.message)))clear();app.innerHTML=`<div class="page"><section class="card pin">${brand("ยังโหลดข้อมูลงานไม่ได้")}<p class="hint">${esc(e.message||"เชื่อมต่อข้อมูลช่างไม่สำเร็จ")}</p><button class="btn" id="retry">ลองอีกครั้ง</button><button class="btn secondary" id="out">ออกจากระบบ</button></section></div>`;document.querySelector("#retry").onclick=state.token?load:()=>pin("กรุณาใส่ PIN ใหม่");document.querySelector("#out").onclick=()=>{clear();pin()}}}
function identity(){return `<section class="worker-identity"><span class="avatar">ช</span><div><small>กำลังใช้งานในชื่อ</small><b>${esc(state.user?.name)}</b></div><button id="out">ออกจากระบบ</button></section>`}
function roleButtons(){if(!roles().includes(state.role))state.role=roles()[0];return `<div class="role-choice">${roles().map(v=>`<button data-role="${v}" class="${state.role===v?"active":""}">${v}</button>`).join("")}</div>`}
function select(id,selected="ชิ้น"){return `<select id="${id}">${["ชิ้น","อัน","ชุด","ใบ"].map(x=>`<option ${x===selected?"selected":""}>${x}</option>`).join("")}</select>`}
function form(){if(!roles().includes(state.role))state.role=roles()[0];const daily=isDaily(state.role),dailyForm=`<label>ชื่อสินค้า<input id="product" placeholder="เช่น ถ้วยกาแฟ"></label><label>รายละเอียด <span class="help">ไม่บังคับ</span><input id="pattern" placeholder="เช่น ลาย/สี หรือขนาด"></label><div class="two"><label>จำนวน<input id="qty" type="number" min="1"></label><label>หน่วยนับ${select("unit")}</label></div><div class="gold-rate"><small>งานช่างรายวัน</small><b>ไม่มีค่าจ้างรายชิ้น · ค่าแรงคิดตามวันทำงาน</b></div>`,gold=state.role==="วนทอง",mook=state.role==="เขียนลาย"&&state.kind==="มุก";const normal=`<span class="form-label">ประเภทงาน</span>${state.role==="ลงสี"?`<div class="type-choice"><button class="active">เบญจรงค์</button></div>`:`<div class="type-choice"><button data-kind="เบญจรงค์" class="${!mook?"active":""}">เบญจรงค์</button><button data-kind="มุก" class="${mook?"active":""}">มุก</button></div>`}<label>รูปแบบงาน${mook?`<select id="style"><option>เขียนทองเต็มใบ</option><option>เขียนทองครึ่งใบ</option></select>`:`<select id="style"><option>เต็มใบ</option><option>ครึ่งใบ (ลูกคั่น)</option><option>ลายขอบ</option></select>`}</label><label>ชื่อสินค้า<input id="product" placeholder="เช่น จานเบญจรงค์"></label><label>ชื่อลาย / รายละเอียด<input id="pattern" placeholder="เช่น ลายพิกุล"></label><div class="two"><label>จำนวน<input id="qty" type="number" min="1"></label><label>หน่วยนับ${select("unit")}</label></div><label>ราคา/หน่วย<input id="price" type="number" min="0" step=".01"></label>${state.role==="เขียนลาย"&&!mook?`<label>จำนวนงานติดสติกเกอร์<input id="sticker" type="number" min="0" value="0"><span class="help">ไม่ติดสติกเกอร์ให้ใช้ 0</span></label>`:""}`;const goldForm=`<div class="gold-rate"><small>ค่าจ้างกำหนดอัตโนมัติ</small><b>180 บาท/เตา</b></div><div class="two"><label>จำนวนเตา<input id="qty" type="number" min="1"></label><label>ราคา/หน่วย<input id="price" readonly value="180"></label></div>`;return `<div class="page-heading"><div><small>กรอกตามที่นายจ้างแจ้ง</small><h2>บันทึกการรับงาน</h2></div><span>${state.user?.isOwnerTest?"บัญชีทดสอบ · แยกจากคิวงานจริง":"ข้อมูลจะรอเจ้าของร้านตรวจ"}</span></div>${state.user?.isOwnerTest?`<section class="card hint">รายการจากบัญชีทดสอบจะบันทึกแยกไว้ตรวจในแท็บส่งงานของบัญชีนี้ และไม่แสดงในคิวเจ้าของร้านจริง</section>`:""}<section class="card form-card"><div class="fixed-worker"><small>ชื่อช่าง</small><b>${esc(state.user?.name)}</b><span>ระบบบันทึกเป็นชื่อของคุณอัตโนมัติ</span></div><span class="form-label">${state.user?.daily?"งานที่ทำ":"หน้าที่"}</span>${roleButtons()}${daily?dailyForm:gold?goldForm:normal}<label>วันที่รับงาน<input id="received" type="date" value="${today()}"></label><label>หมายเหตุ <span class="help">ไม่บังคับ</span><textarea id="note" rows="2"></textarea></label><button class="primary-wide" id="save">บันทึกการรับงาน</button></section>`}
function job(id){return(state.data?.jobs||[]).find(j=>j.id===id)}function remaining(j){return Math.max(0,(+j.qty||0)-(+j.acceptedQty||0)-(+j.pendingQty||0))}
function route(j){return isDaily(j.role)?'<p class="worker-route-card">🔥 งานช่างรายวัน · ส่งเผาเลย</p>':j.role==="เขียนลาย"?`<p class="worker-route-card">${j.workType==="เบญจรงค์"?"🎨 เบญจรงค์ · ส่งลงสีต่อ":"🔥 มุก · ส่งเผาเลย"}</p>`:""}
function card(j,buttons){const unit=j.role==="วนทอง"?"เตา":j.unit||"ชิ้น",editable=buttons&&!j.acceptedQty&&!j.pendingQty&&!j.returnedQty;return `<article class="card job"><div class="job-title"><div><small>${esc(j.id)}</small><h3>${esc(j.role==="วนทอง"?"งานวนทอง":j.product)}</h3></div><span class="badge">${esc(j.status)}</span></div><p>${esc(j.role)}${j.role==="วนทอง"?" · 180 บาท/เตา":` · ${esc(j.workType)} · ${esc(j.workStyle||j.pattern)}`}</p>${route(j)}<div class="job-detail-grid"><div><small>รับทั้งหมด</small><b>${money(j.qty)} ${unit}</b></div><div><small>ผ่านแล้ว</small><b>${money(j.acceptedQty)} ${unit}</b></div><div><small>${isDaily(j.role)?"ค่าแรง":"ราคา/หน่วย"}</small><b>${isDaily(j.role)?"ตามวันทำงาน":`${money(j.priceEach)} บาท/${unit}`}</b></div><div><small>วันที่รับงาน</small><b>${esc(j.receivedDate||"-")}</b></div></div>${j.stickerQty?`<p class="hint">ติดสติกเกอร์ ${money(j.stickerQty)} ชิ้น</p>`:""}${editable?`<div class="job-correction-actions"><button data-edit="${esc(j.id)}">แก้ไขข้อมูล</button><button data-delete="${esc(j.id)}">ลบรายการ</button></div>`:""}${buttons&&remaining(j)>0?`<button class="primary-wide" data-send="${esc(j.id)}">ยืนยันส่งงาน</button>`:""}</article>`}
function submit(){if(state.syncing)return `<section class="card"><div class="hint">กำลังโหลดรายการส่งงาน...</div></section>`;const ready=(state.data?.jobs||[]).filter(j=>remaining(j)>0).sort((a,b)=>String(b.receivedDate||"").localeCompare(String(a.receivedDate||""))||String(b.id).localeCompare(String(a.id))),pending=(state.data?.submissions||[]).filter(s=>s.status==="รอตรวจ").map(s=>({s,j:job(s.jobId)})).filter(x=>x.j);return `<div class="page-heading"><div><small>แนบรูปและยืนยันบนการ์ดได้ทันที</small><h2>งานของฉัน</h2></div><span>ต้องแนบรูปผลงานทุกครั้ง</span></div>${ready.map(sendCard).join("")}${pending.length?`<div class="page-heading"><div><small>แก้ไขได้จนกว่าเจ้าของร้านจะรับรอง</small><h2>รายการรอตรวจ</h2></div></div>${pending.map(pendingCard).join("")}`:""}${ready.length||pending.length?"":`<section class="card"><div class="hint">ยังไม่มีงานที่รอส่ง</div></section>`}`}
function render(){app.innerHTML=`<div class="page">${brand("บันทึกงานด้วยข้อมูลที่นายจ้างแจ้ง")}${identity()}<nav class="tabs">${[["jobs","＋<br>รับงาน"],["submit","✓<br>ส่งงาน"],["history","↺<br>ประวัติของฉัน"]].map(x=>`<button data-tab="${x[0]}" class="${state.tab===x[0]?"active":""}">${x[1]}</button>`).join("")}</nav><section class="content" id="content">${state.tab==="jobs"?form():state.tab==="submit"?submit():workerHistoryView()}</section></div>`;bindWorkerUi()}
async function save(){const q=x=>document.querySelector(x)?.value||"",b=document.querySelector("#save"),done=busy(b,"กำลังบันทึกรับงาน..."),d={role:state.role,workType:isDaily(state.role)?"งานรายวัน":state.role==="วนทอง"?"วนทอง":state.role==="ลงสี"?"เบญจรงค์":state.kind,workStyle:q("#style"),product:q("#product"),pattern:q("#pattern"),qty:q("#qty"),unit:q("#unit")||"ชิ้น",priceEach:q("#price"),stickerQty:q("#sticker"),receivedDate:q("#received"),note:q("#note")},key=[d.role,d.workType,d.workStyle,d.product,d.pattern,d.qty,d.unit,d.priceEach,d.stickerQty,d.receivedDate,d.note].join("|");d.clientRequestId=operationId("create",key);try{const r=await api.workerPortalCreateJob(state.token,d);if(!r.ok)throw Error(r.message||r.error);const id=String(r.result?.id||"");if(r.result?.success!==true||!id)throw Error(r.message||"ระบบยังยืนยันการบันทึกรายการไม่ได้ กรุณาลองใหม่อีกครั้ง");finishOperation("create",key);(state.data?.jobs||[]).unshift({id,worker:state.user?.name||"",role:d.role,workType:d.workType,workStyle:d.workStyle,product:d.role==="วนทอง"?"งานวนทอง":d.product,pattern:d.role==="วนทอง"?"-":d.pattern,qty:+d.qty,unit:d.unit,priceEach:+d.priceEach||0,status:"รอส่งงาน",acceptedQty:0,pendingQty:0,returnedQty:0,stickerQty:+d.stickerQty||0,receivedDate:d.receivedDate,note:d.note});state.tab="submit";render();toast(state.user?.isOwnerTest?"บันทึกงานทดสอบแล้ว · ไม่เข้าคิวเจ้าของร้านจริง":r.result.message||"บันทึกงานและยืนยันในระบบแล้ว");refreshSoon()}catch(e){done();toast(e.message||"บันทึกไม่สำเร็จ")}}
async function compressPhoto(file){const source=URL.createObjectURL(file);try{const image=await new Promise((resolve,reject)=>{const x=new Image();x.onload=()=>resolve(x);x.onerror=reject;x.src=source});const scale=Math.min(1,1600/Math.max(image.naturalWidth||1,image.naturalHeight||1));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.82));if(!blob)throw Error("ไม่สามารถเตรียมรูปได้");return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({data:reader.result,name:file.name.replace(/\.[^.]+$/,".jpg")});reader.onerror=reject;reader.readAsDataURL(blob)})}finally{URL.revokeObjectURL(source)}}
async function photo(e,id){const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024)return toast("รูปต้องไม่เกิน 8 MB");toast("กำลังเตรียมรูปสำหรับส่ง...");try{state.photos[id]=await compressPhoto(f);render();toast("แนบรูปแล้ว · รูปถูกย่อเพื่อส่งได้เร็วขึ้น")}catch(error){toast("เตรียมรูปไม่สำเร็จ โปรดลองใหม่")}}
async function send(id){const p=state.photos[id],q=document.querySelector(`[data-qty="${CSS.escape(id)}"]`)?.value,b=document.querySelector(`[data-submit="${CSS.escape(id)}"]`);if(!p?.data)return toast("กรุณาแนบรูปผลงาน");const key=[id,q,p.name].join("|"),done=busy(b,"กำลังยืนยันส่งงาน...");try{const r=await api.workerPortalSubmit(state.token,{jobId:id,qty:q,photoData:p.data,photoName:p.name,submittedDate:today(),clientRequestId:operationId("submit",key)});if(!r.ok)throw Error(r.message||r.error);finishOperation("submit",key);const j=job(id),n=+q||0;if(j)j.pendingQty=(+j.pendingQty||0)+n;(state.data?.submissions||[]).unshift({id:r.result?.id||`LOCAL-${Date.now()}`,jobId:id,qty:n,submittedDate:today(),status:"รอตรวจ",acceptedQty:0,photoUrl:p.data});delete state.photos[id];toast(r.result?.message||"ส่งงานให้เจ้าของตรวจแล้ว");state.tab="submit";render();refreshSoon()}catch(e){done();toast(e.message||"ส่งงานไม่สำเร็จ")}}
async function savePending(submissionId,jobId){const p=state.photos[submissionId],q=x=>document.querySelector(`${x}[data-pending-qty="${CSS.escape(submissionId)}"],${x}[data-pending-price="${CSS.escape(submissionId)}"]`)?.value||"",j=job(jobId),done=busy(document.querySelector(`[data-pending-save="${CSS.escape(submissionId)}"]`),"กำลังบันทึก...");try{const qty=+q("[data-pending-qty]"),price=+q("[data-pending-price]"),r=await api.workerPortalUpdatePendingSubmission(state.token,{submissionId,qty,priceEach:price,jobQty:j?.qty,photoData:p?.data||"",photoName:p?.name||""});if(!r.ok)throw Error(r.message||r.error);const s=(state.data?.submissions||[]).find(x=>x.id===submissionId);if(j){j.priceEach=price;j.pendingQty=(state.data?.submissions||[]).filter(x=>x.jobId===jobId&&x.status==="รอตรวจ"&&x.id!==submissionId).reduce((sum,x)=>sum+(+x.qty||0),0)+qty}if(s){s.qty=qty;if(p?.data)s.photoUrl=p.data}delete state.photos[submissionId];toast(r.result?.message||"บันทึกการแก้ไขแล้ว");state.tab="submit";render();refreshSoon()}catch(e){done();toast(e.message||"แก้ไขไม่สำเร็จ")}}
function deletePending(jobId){ask("ถอนรายการรอตรวจ","ยืนยันถอนรายการนี้ก่อนเจ้าของร้านตรวจหรือไม่?",async(button)=>{const done=busy(button,"กำลังถอนรายการ...");try{const r=await api.workerPortalDeletePendingJob(state.token,{jobId});if(!r.ok)throw Error(r.message||r.error);state.data.jobs=(state.data?.jobs||[]).filter(x=>x.id!==jobId);state.data.submissions=(state.data?.submissions||[]).filter(x=>x.jobId!==jobId);toast(r.result?.message||"ถอนรายการแล้ว");state.tab="submit";render();refreshSoon()}catch(error){done();throw error}})}
function edit(id){const j=job(id);if(!j)return;document.querySelector("#content").innerHTML=`<section class="card form-card"><h2>แก้ไขข้อมูล</h2><label>ชื่อสินค้า<input id="ep" value="${esc(j.product)}"></label><label>ชื่อลาย<input id="ea" value="${esc(j.pattern)}"></label><div class="two"><label>จำนวน<input id="eq" type="number" value="${esc(j.qty)}"></label><label>หน่วย${select("eu",j.unit||"ชิ้น")}</label></div>${isDaily(j.role)?"":`<label>ราคา/หน่วย<input id="er" value="${esc(j.priceEach)}"></label><label>จำนวนงานติดสติกเกอร์<input id="es" value="${esc(j.stickerQty||0)}"></label>`}<label>วันที่รับงาน<input id="ed" type="date" value="${esc(j.receivedDate)}"></label><label>หมายเหตุ<textarea id="en">${esc(j.note||"")}</textarea></label><div class="edit-actions"><button id="cancel">ยกเลิก</button><button id="update">บันทึกการแก้ไข</button></div></section>`;document.querySelector("#cancel").onclick=render;document.querySelector("#update").onclick=async()=>{const q=x=>document.querySelector(x)?.value||"",done=busy(document.querySelector("#update"),"กำลังบันทึก...");try{const data={jobId:id,product:q("#ep"),pattern:q("#ea"),qty:q("#eq"),unit:q("#eu"),priceEach:q("#er"),stickerQty:q("#es"),receivedDate:q("#ed"),note:q("#en")},r=await api.workerPortalUpdateJob(state.token,data);if(!r.ok)throw Error(r.message||r.error);Object.assign(j,{product:data.product,pattern:data.pattern,qty:+data.qty,unit:data.unit,priceEach:+data.priceEach||0,stickerQty:+data.stickerQty||0,receivedDate:data.receivedDate,note:data.note});toast(r.result?.message||"แก้ไขเรียบร้อยแล้ว");state.tab="submit";render();refreshSoon()}catch(e){done();toast(e.message||"แก้ไขไม่สำเร็จ")}}}
function ask(title,message,action){const el=document.createElement("div");el.className="modal-backdrop";el.innerHTML=`<section class="confirm-modal"><h2>${esc(title)}</h2><p>${esc(message)}</p><div class="confirm-actions"><button id="ask-cancel">ยกเลิก</button><button id="ask-ok">ยืนยัน</button></div></section>`;document.body.append(el);const close=()=>el.remove(),onKey=e=>{if(e.key==="Escape"){close();document.removeEventListener("keydown",onKey)}};document.addEventListener("keydown",onKey);el.onclick=e=>{if(e.target===el)close()};el.querySelector("#ask-cancel").onclick=close;el.querySelector("#ask-ok").onclick=async()=>{try{await action(el.querySelector("#ask-ok"));close()}catch(e){toast(e.message||"ทำรายการไม่สำเร็จ")}}}
function remove(id){const j=job(id);ask("ลบรายการนี้?",`${j?.product||"งานช่าง"}\n${j?.pattern||""}`,async(button)=>{const done=busy(button,"กำลังลบ...");try{const r=await api.workerPortalDeleteJob(state.token,{jobId:id});if(!r.ok)throw Error(r.message||r.error);state.data.jobs=(state.data?.jobs||[]).filter(x=>x.id!==id);state.data.submissions=(state.data?.submissions||[]).filter(x=>x.jobId!==id);toast(r.result?.message||"ลบรายการแล้ว");state.tab="submit";render();refreshSoon()}catch(error){done();throw error}})}
function view(url){const x=document.createElement("div");x.className="modal-backdrop photo-modal";x.innerHTML=`<button>×</button><img src="${esc(url)}" alt="รูปผลงานช่าง">`;x.onclick=()=>x.remove();document.body.append(x)}
function workerPeriod(date){const d=new Date(`${String(date||today()).slice(0,10)}T00:00:00`),day=d.getDate(),months=['ม.ค.','ก.พ.','มี.ค.','เม.ย.','พ.ค.','มิ.ย.','ก.ค.','ส.ค.','ก.ย.','ต.ค.','พ.ย.','ธ.ค.'];return `${day<=15?'1–15':'16–'+new Date(d.getFullYear(),d.getMonth()+1,0).getDate()} ${months[d.getMonth()]} ${d.getFullYear()+543}`}
// Sortable key of a pay period (two per month), e.g. 2026-10-1.
function workerPeriodOrder(date){const s=String(date||today()).slice(0,10);return `${s.slice(0,7)}-${Number(s.slice(8,10))<=15?1:2}`}
function workerHistoryView(){const jobs=state.data?.jobs||[],subs=state.data?.submissions||[],byJob={};subs.forEach(s=>(byJob[s.jobId]??=[]).push(s));const groups={};jobs.forEach(j=>{const s=(byJob[j.id]||[]).sort((a,b)=>String(b.submittedDate).localeCompare(String(a.submittedDate)))[0],q=+j.acceptedQty||0,w=q*(+j.priceEach||0)+(j.role==='เขียนลาย'?Math.min(q,+j.stickerQty||0)*5:0),date=s?.submittedDate||j.receivedDate||today(),key=workerPeriod(date);(groups[key]??={rows:[],total:0,order:workerPeriodOrder(date)}).rows.push({j,s,q,w});if(q)groups[key].total+=w});/* The current period is always offered and comes first, even with no work yet. */const nowKey=workerPeriod(today());groups[nowKey]??={rows:[],total:0,order:workerPeriodOrder(today())};const keys=Object.keys(groups).sort((a,b)=>groups[b].order.localeCompare(groups[a].order));if(!state.historyPeriod||!groups[state.historyPeriod])state.historyPeriod=nowKey;const g=groups[state.historyPeriod];return `<div class="page-heading"><div><small>${esc(state.user?.name)}</small><h2>ประวัติของฉัน</h2></div><span>แสดงทั้งงานที่รอตรวจและงานที่คิดค่าแรงแล้ว</span></div><section class="card worker-history-period">${keys.length?`<label class="field">เลือกงวด<select id="history-period">${keys.map(k=>`<option ${k===state.historyPeriod?'selected':''}>${esc(k)}</option>`).join('')}</select></label><div class="job-title"><h3>งวด ${esc(state.historyPeriod)}</h3><span class="badge">${state.user?.daily?'ค่าแรงตามวันทำงาน':`คิดแล้ว ฿${money(g.total)}`}</span></div>${g.rows.length?'':'<div class="hint">ยังไม่มีงานในงวดนี้</div>'}${g.rows.map(({j,s,q,w})=>`<article class="worker-history-row"><div><b>${esc(j.role==='วนทอง'?'งานวนทอง':j.product)}</b><small>${esc(j.pattern||j.workStyle||'-')} · ${money(q||j.qty)} ${esc(j.unit||'ชิ้น')}${s?` · ส่ง ${esc(s.submittedDate||'')}`:''}</small>${s?.photoUrl?`<button class="photo-link" data-photo-view="${esc(s.photoUrl)}">ดูรูปที่แนบ</button>`:''}</div><strong class="${q?'paid':'unpaid'}">${q?(isDaily(j.role)?'ผ่านแล้ว':`฿${money(w)}`):s?.status==='รอตรวจ'?'รอเจ้าของตรวจ':s?'ยังไม่ได้คิดเงิน':'ยังไม่ส่งงาน'}</strong></article>`).join('')}${state.user?.daily?'<p class="worker-history-total">งานช่างรายวันไม่มีค่าจ้างรายชิ้น · ค่าแรงคิดตามวันทำงาน</p>':`<p class="worker-history-total">รวมค่าจ้างที่คิดแล้วในงวดนี้ <b>฿${money(g.total)}</b></p>`}`:`<div class="hint">ยังไม่มีประวัติงาน</div>`}</section>`}
function sendCard(j){const p=state.photos[j.id]||{},id=esc(j.id),canEdit=!j.acceptedQty&&!j.pendingQty&&!j.returnedQty;return `<article class="card job"><div class="job-title"><h3>${esc(j.role==='วนทอง'?'งานวนทอง':j.product)}</h3><span class="badge">คงส่ง ${money(remaining(j))}</span></div>${route(j)}<div class="job-detail-grid"><div><small>จำนวน</small><b>${money(remaining(j))} ${esc(j.role==="วนทอง"?"เตา":(j.unit||"ชิ้น"))}</b></div><div><small>${isDaily(j.role)?"ค่าแรง":"ราคา/หน่วย"}</small><b>${priceText(j)}</b></div></div><label class="field">จำนวนส่ง<input data-qty="${id}" type="number" min="1" max="${remaining(j)}" value="${remaining(j)}"></label><div class="photo-actions"><label class="photo-action">📷<input data-photo="${id}" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"><b>ถ่ายรูปจากกล้อง</b></label><label class="photo-action">🖼️<input data-photo="${id}" type="file" accept="image/jpeg,image/png,image/webp"><b>เลือกรูปจากเครื่อง</b></label></div>${p.data?`<img class="photo-preview show" src="${p.data}" alt="ตัวอย่างรูปผลงาน">`:''}<p class="photo-ready">${p.data?'✓ แนบรูปแล้ว · เลือกใหม่ได้':'กรุณาแนบรูปผลงานก่อนส่ง'}</p>${canEdit?`<div class="job-correction-actions"><button class="btn secondary" data-edit="${id}">แก้ไขข้อมูลงาน</button><button data-delete="${id}">ยกเลิกรายการ</button></div>`:''}<button class="primary-wide" data-submit="${id}">ยืนยันส่งงาน</button></article>`}
function pendingCard(x){const {j,s}=x,p=state.photos[s.id]||{},id=esc(s.id);return `<article class="card job"><div class="job-title"><h3>${esc(j.role==='วนทอง'?'งานวนทอง':j.product)}</h3><span class="badge">รอตรวจ</span></div>${route(j)}<div class="job-detail-grid"><div><small>จำนวน</small><b>${money(remaining(j))} ${esc(j.role==="วนทอง"?"เตา":(j.unit||"ชิ้น"))}</b></div><div><small>${isDaily(j.role)?"ค่าแรง":"ราคา/หน่วย"}</small><b>${priceText(j)}</b></div></div><label class="field">จำนวนส่ง<input data-pending-qty="${id}" type="number" min="1" value="${esc(s.qty)}"></label>${isDaily(j.role)?"":`<label class="field">ราคา/หน่วย<input data-pending-price="${id}" type="number" min="0" value="${esc(j.priceEach)}"></label>`}<div class="photo-actions"><label class="photo-action">📷<input data-pending-photo="${id}" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"><b>ถ่ายรูปใหม่</b></label><label class="photo-action">🖼️<input data-pending-photo="${id}" type="file" accept="image/jpeg,image/png,image/webp"><b>เลือกรูปใหม่</b></label></div>${p.data?`<img class="photo-preview show" src="${p.data}" alt="ตัวอย่างรูปผลงาน">`:s.photoUrl?`<img class="photo-preview show" src="${esc(s.photoUrl)}" alt="รูปผลงานช่าง">`:''}<div class="job-correction-actions"><button data-pending-save="${id}" data-job="${esc(j.id)}">บันทึกการแก้ไข</button><button data-pending-delete="${esc(j.id)}">ถอนรายการ</button></div></article>`}
function bindWorkerUi(){document.querySelector('#out')?.addEventListener('click',()=>{clear();pin()});app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();if(state.tab!=="jobs"&&Date.now()-(state.lastRefresh||0)>15000)refreshData(true).catch(()=>{})});app.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{state.role=b.dataset.role;state.kind='เบญจรงค์';render()});app.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{state.kind=b.dataset.kind;render()});document.querySelector('#history-period')?.addEventListener('change',e=>{state.historyPeriod=e.target.value;render()});document.querySelector('#save')?.addEventListener('click',save);app.querySelectorAll('[data-photo]').forEach(e=>e.onchange=x=>photo(x,e.dataset.photo));app.querySelectorAll('[data-pending-photo]').forEach(e=>e.onchange=x=>photo(x,e.dataset.pendingPhoto));app.querySelectorAll('[data-submit]').forEach(b=>b.onclick=()=>send(b.dataset.submit));app.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));app.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));app.querySelectorAll('[data-pending-save]').forEach(b=>b.onclick=()=>savePending(b.dataset.pendingSave,b.dataset.job));app.querySelectorAll('[data-pending-delete]').forEach(b=>b.onclick=()=>deletePending(b.dataset.pendingDelete));app.querySelectorAll('[data-photo-view]').forEach(b=>b.onclick=()=>view(b.dataset.photoView))}
if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js?v=worker-v29").catch(()=>{});installLoader();const linkToken=(location.hash.match(/^#link=(.+)$/)||[])[1];linkToken?linkLogin(decodeURIComponent(linkToken)):state.token&&state.user?load():pin();
