import {ApiClient} from "../js/api.js";
const api=new ApiClient(),app=document.querySelector("#app"),toastEl=document.querySelector("#toast");
const KEY="suphan.worker.portal.session",NAME_KEY="suphan.worker.portal.user";
let state={token:sessionStorage.getItem(KEY)||"",user:JSON.parse(sessionStorage.getItem(NAME_KEY)||"null"),users:[],data:null,tab:"jobs",photo:"",photoName:""};
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const money=v=>(Number(v)||0).toLocaleString("th-TH");
function toast(text){toastEl.textContent=text;toastEl.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>toastEl.classList.remove("show"),2600);}
function brand(sub="บันทึกรับงานและส่งงานให้เจ้าของตรวจ"){return `<div class="brand"><img src="../assets/icon-192.png" alt=""><h1>ช่างสุพรรณบุรีเบญจรงค์</h1><p>${sub}</p></div>`;}
function renderPin(message=""){app.innerHTML=`<div class="page"><section class="card pin">${brand("ใส่ PIN ช่าง 6 หลัก")}<input id="pin" type="password" inputmode="numeric" maxlength="6" autocomplete="one-time-code" aria-label="PIN ช่าง"><p class="hint" id="msg">${esc(message)}</p><button class="btn" id="login">เข้าสู่ระบบ</button></section></div>`;const pin=document.querySelector("#pin");pin.focus();pin.addEventListener("input",()=>{pin.value=pin.value.replace(/\D/g,"");if(pin.value.length===6)login(pin.value);});document.querySelector("#login").onclick=()=>login(pin.value);}
async function login(pin){if(!/^\d{6}$/.test(pin)){toast("กรุณาใส่ PIN 6 หลัก");return;}try{const r=await api.login(pin);if(!r.ok||r.level!=="worker")throw Error("INVALID");state.token=r.session;state.users=r.users||[];chooseWorker();}catch(e){renderPin("PIN ไม่ถูกต้อง หรือยังไม่ได้เปิดสิทธิ์ช่าง");}}
function chooseWorker(){app.innerHTML=`<div class="page">${brand("เลือกชื่อของคุณก่อนเริ่มงาน")}<section class="people">${state.users.map((u,i)=>`<button class="person" data-u="${i}"><span aria-hidden="true" style="font-size:40px">🧑‍🎨</span><strong>${esc(u.name)}</strong><small>${esc(u.role)}</small></button>`).join("")||"<p>ไม่พบรายชื่อช่างที่ทำงานอยู่</p>"}</section></div>`;app.querySelectorAll("[data-u]").forEach(b=>b.onclick=()=>selectWorker(state.users[Number(b.dataset.u)]));}
async function selectWorker(user){if(!user?.name){toast("ไม่พบรายชื่อช่าง กรุณาเข้าสู่ระบบใหม่");renderPin();return;}try{const r=await api.selectUser(state.token,user.name);if(!r.ok||!r.token||!r.session?.user?.name)throw Error(r.message||r.error||"เลือกชื่อไม่สำเร็จ");state.token=r.token;state.user={name:r.session.user.name,role:r.session.user.role||user.role||""};sessionStorage.setItem(KEY,state.token);sessionStorage.setItem(NAME_KEY,JSON.stringify(state.user));await load();}catch(e){state.token="";state.user=null;sessionStorage.removeItem(KEY);sessionStorage.removeItem(NAME_KEY);renderPin("เลือกชื่อช่างไม่สำเร็จ กรุณาใส่ PIN ใหม่");}}
async function load(){app.innerHTML=`<div class="page">${brand("กำลังโหลดงานของช่าง...")}</div>`;try{const r=await api.workerPortalBootstrap(state.token);if(!r.ok)throw Error(r.message||r.error||"เชื่อมต่อข้อมูลช่างไม่สำเร็จ");state.data=r.result;render();}catch(e){renderLoadFailure(e?.message||"เชื่อมต่อข้อมูลช่างไม่สำเร็จ");}}
function renderLoadFailure(message){app.innerHTML=`<div class="page"><section class="card pin">${brand("ยังโหลดข้อมูลงานไม่ได้")}<p class="hint">${esc(message)}</p><button class="btn" id="retry">ลองอีกครั้ง</button><button class="btn secondary" id="signOut">ออกจากระบบ</button></section></div>`;document.querySelector("#retry").onclick=load;document.querySelector("#signOut").onclick=()=>{sessionStorage.removeItem(KEY);sessionStorage.removeItem(NAME_KEY);state.token="";state.user=null;renderPin();};}
function render(){const jobs=state.data?.jobs||[];app.innerHTML=`<div class="page">${brand(`ช่าง: ${esc(state.user?.name||"")}`)}<nav class="tabs"><button data-tab="jobs" class="${state.tab==="jobs"?"active":""}">รับงาน</button><button data-tab="submit" class="${state.tab==="submit"?"active":""}">ส่งงาน</button><button data-tab="history" class="${state.tab==="history"?"active":""}">ประวัติ</button></nav><section id="content"></section></div>`;app.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();});const content=document.querySelector("#content");if(state.tab==="jobs")content.innerHTML=jobForm();else if(state.tab==="submit")content.innerHTML=submitForm(jobs);else content.innerHTML=history(jobs);bind();}
function jobForm(){const writer=/เขียนลาย/.test(state.user?.role||"");return `<section class="card"><h2>📥 รับงาน</h2><p class="hint">ข้อมูลนี้เป็นคำขอรอเจ้าของร้านเชื่อมกับของขาวและ SKU จริง</p><label class="field">ประเภทงาน<select id="workType"><option value="เบญจรงค์">เบญจรงค์</option><option value="มุก">มุก</option><option value="งานอื่น">งานอื่น</option></select></label><div class="two"><label class="field">รูปแบบงาน<input id="workStyle" placeholder="เช่น เขียนลาย / ลงสี"></label><label class="field">ชื่อสินค้า<input id="product" placeholder="ช่างระบุได้"></label></div><label class="field">ชื่อลาย / รายละเอียด<input id="pattern" placeholder="ระบุลายหรือรายละเอียดงาน"></label><div class="two"><label class="field">จำนวนรับ<input id="qty" inputmode="numeric" type="number" min="1"></label><label class="field">ราคา/หน่วย<input id="price" inputmode="decimal" type="number" min="0" step=".01"></label></div>${writer?`<label class="field">จำนวนงานติดสติกเกอร์<input id="sticker" inputmode="numeric" type="number" min="0" value="0"></label>`:""}<label class="field">วันที่รับงาน<input id="received" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label class="field">หมายเหตุ<textarea id="note" rows="2"></textarea></label><button class="btn green" id="saveJob">บันทึกรับงาน</button></section>`;}
function jobCard(j,withSubmit=false){return `<article class="card job"><div class="job-title"><h3>${esc(j.product||j.workType||"งานช่าง")}</h3><span class="badge">${esc(j.status)}</span></div><p>${esc(j.pattern||j.workStyle||"-")} · ${esc(j.role)}</p><p>รับ ${money(j.qty)} ชิ้น · คงส่ง ${money(Math.max(0,(+j.qty||0)-(+j.acceptedQty||0)-(+j.pendingQty||0)))}</p>${withSubmit?`<button class="btn" data-send="${esc(j.id)}">ส่งงาน</button>`:""}</article>`;}
function submitForm(jobs){const ready=jobs.filter(j=>Math.max(0,(+j.qty||0)-(+j.acceptedQty||0)-(+j.pendingQty||0))>0);return `<section class="card"><h2>📷 ส่งงานให้เจ้าของตรวจ</h2><p class="hint">ต้องแนบรูปผลงานทุกครั้ง และจะยังไม่ถือว่ารับงานสำเร็จจนกว่าเจ้าของร้านยืนยัน</p>${ready.map(j=>jobCard(j,true)).join("")||"<p class=\"hint\">ยังไม่มีงานที่พร้อมส่ง</p>"}</section>`;}
function history(jobs){return `<section class="card"><h2>🕘 ประวัติงาน</h2>${jobs.map(j=>jobCard(j)).join("")||"<p class=\"hint\">ยังไม่มีประวัติ</p>"}</section>`;}
function bind(){const save=document.querySelector("#saveJob");if(save)save.onclick=saveJob;app.querySelectorAll("[data-send]").forEach(b=>b.onclick=()=>openSubmit(b.dataset.send));}
async function saveJob(){const q=id=>document.querySelector(id).value;const data={workType:q("#workType"),workStyle:q("#workStyle"),product:q("#product"),pattern:q("#pattern"),qty:q("#qty"),priceEach:q("#price"),stickerQty:document.querySelector("#sticker")?.value||0,receivedDate:q("#received"),note:q("#note")};try{document.querySelector("#saveJob").disabled=true;const r=await api.workerPortalCreateJob(state.token,data);if(!r.ok)throw Error(r.message);toast(r.result?.message||"บันทึกแล้ว");await load();}catch(e){toast(e.message||"บันทึกไม่สำเร็จ");document.querySelector("#saveJob").disabled=false;}}
function openSubmit(jobId){const j=(state.data.jobs||[]).find(x=>x.id===jobId),remaining=Math.max(0,(+j.qty||0)-(+j.acceptedQty||0)-(+j.pendingQty||0));document.querySelector("#content").innerHTML=`<section class="card"><h2>ส่งงาน: ${esc(j.product||j.workType)}</h2><label class="field">จำนวนส่ง<input id="submitQty" type="number" min="1" max="${remaining}" value="${remaining}"></label><label class="field">รูปผลงาน<input id="photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"></label><img id="preview" class="photo-preview" alt="ตัวอย่างรูปผลงาน"><div class="row"><button class="btn secondary" id="cancel">ยกเลิก</button><button class="btn green" id="confirmSubmit">ส่งให้ตรวจ</button></div></section>`;document.querySelector("#cancel").onclick=render;document.querySelector("#photo").onchange=readPhoto;document.querySelector("#confirmSubmit").onclick=()=>submit(jobId);}
function readPhoto(e){const file=e.target.files?.[0];if(!file)return;if(file.size>8*1024*1024){toast("รูปต้องไม่เกิน 8 MB");e.target.value="";return;}state.photoName=file.name;const reader=new FileReader();reader.onload=()=>{state.photo=reader.result;const p=document.querySelector("#preview");p.src=state.photo;p.classList.add("show");};reader.readAsDataURL(file);}
async function submit(jobId){if(!state.photo){toast("กรุณาแนบรูปผลงาน");return;}const button=document.querySelector("#confirmSubmit");button.disabled=true;try{const r=await api.workerPortalSubmit(state.token,{jobId,qty:document.querySelector("#submitQty").value,photoData:state.photo,photoName:state.photoName,submittedDate:new Date().toISOString().slice(0,10)});if(!r.ok)throw Error(r.message);state.photo="";toast(r.result?.message||"ส่งงานแล้ว");await load();}catch(e){toast(e.message||"ส่งงานไม่สำเร็จ");button.disabled=false;}}
if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js").catch(()=>{});if(state.token&&state.user)load();else renderPin();
